import { TCustomConnOptions, TQoreAppActionFunctionContext } from '@qoretechnologies/ts-toolkit';

export const SHOPIFY_APP_NAME = 'Shopify';
export const SHOPIFY_APP_LOGO = `PD94bWwgdmVyc2lvbj0iMS4wIiBlbmNvZGluZz0idXRmLTgiPz48IS0tIFVwbG9hZGVkIHRvOiBTVkcgUmVwbywgd3d3LnN2Z3JlcG8uY29tLCBHZW5lcmF0b3I6IFNWRyBSZXBvIE1peGVyIFRvb2xzIC0tPgo8c3ZnIHdpZHRoPSI4MDBweCIgaGVpZ2h0PSI4MDBweCIgdmlld0JveD0iLTE4IDAgMjkyIDI5MiIgeG1sbnM9Imh0dHA6Ly93d3cudzMub3JnLzIwMDAvc3ZnIiBwcmVzZXJ2ZUFzcGVjdFJhdGlvPSJ4TWlkWU1pZCI+PHBhdGggZD0iTTIyMy43NzQgNTcuMzRjLS4yMDEtMS40Ni0xLjQ4LTIuMjY4LTIuNTM3LTIuMzU3LTEuMDU1LS4wODgtMjMuMzgzLTEuNzQzLTIzLjM4My0xLjc0M3MtMTUuNTA3LTE1LjM5NS0xNy4yMDktMTcuMDk5Yy0xLjcwMy0xLjcwMy01LjAyOS0xLjE4NS02LjMyLS44MDUtLjE5LjA1Ni0zLjM4OCAxLjA0My04LjY3OCAyLjY4LTUuMTgtMTQuOTA2LTE0LjMyMi0yOC42MDQtMzAuNDA1LTI4LjYwNC0uNDQ0IDAtLjkwMS4wMTgtMS4zNTguMDQ0QzEyOS4zMSAzLjQwNyAxMjMuNjQ0Ljc3OSAxMTguNzUuNzc5Yy0zNy40NjUgMC01NS4zNjQgNDYuODM1LTYwLjk3NiA3MC42MzUtMTQuNTU4IDQuNTExLTI0LjkgNy43MTgtMjYuMjIxIDguMTMzLTguMTI2IDIuNTQ5LTguMzgzIDIuODA1LTkuNDUgMTAuNDYyQzIxLjMgOTUuODA2LjAzOCAyNjAuMjM1LjAzOCAyNjAuMjM1bDE2NS42NzggMzEuMDQyIDg5Ljc3LTE5LjQyUzIyMy45NzMgNTguOCAyMjMuNzc1IDU3LjM0ek0xNTYuNDkgNDAuODQ4bC0xNC4wMTkgNC4zMzljLjAwNS0uOTg4LjAxLTEuOTYuMDEtMy4wMjMgMC05LjI2NC0xLjI4Ni0xNi43MjMtMy4zNDktMjIuNjM2IDguMjg3IDEuMDQgMTMuODA2IDEwLjQ2OSAxNy4zNTggMjEuMzJ6bS0yNy42MzgtMTkuNDgzYzIuMzA0IDUuNzczIDMuODAyIDE0LjA1OCAzLjgwMiAyNS4yMzggMCAuNTcyLS4wMDUgMS4wOTUtLjAxIDEuNjI0LTkuMTE3IDIuODI0LTE5LjAyNCA1Ljg5LTI4Ljk1MyA4Ljk2NiA1LjU3NS0yMS41MTYgMTYuMDI1LTMxLjkwOCAyNS4xNjEtMzUuODI4em0tMTEuMTMxLTEwLjUzN2MxLjYxNyAwIDMuMjQ2LjU0OSA0LjgwNSAxLjYyMi0xMi4wMDcgNS42NS0yNC44NzcgMTkuODgtMzAuMzEyIDQ4LjI5N2wtMjIuODg2IDcuMDg4Qzc1LjY5NCA0Ni4xNiA5MC44MSAxMC44MjggMTE3LjcyIDEwLjgyOHoiIGZpbGw9IiM5NUJGNDYiLz48cGF0aCBkPSJNMjIxLjIzNyA1NC45ODNjLTEuMDU1LS4wODgtMjMuMzgzLTEuNzQzLTIzLjM4My0xLjc0M3MtMTUuNTA3LTE1LjM5NS0xNy4yMDktMTcuMDk5Yy0uNjM3LS42MzQtMS40OTYtLjk1OS0yLjM5NC0xLjA5OWwtMTIuNTI3IDI1Ni4yMzMgODkuNzYyLTE5LjQxOFMyMjMuOTcyIDU4LjggMjIzLjc3NCA1Ny4zNGMtLjIwMS0xLjQ2LTEuNDgtMi4yNjgtMi41MzctMi4zNTciIGZpbGw9IiM1RThFM0UiLz48cGF0aCBkPSJNMTM1LjI0MiAxMDQuNTg1bC0xMS4wNjkgMzIuOTI2cy05LjY5OC01LjE3Ni0yMS41ODYtNS4xNzZjLTE3LjQyOCAwLTE4LjMwNSAxMC45MzctMTguMzA1IDEzLjY5MyAwIDE1LjAzOCAzOS4yIDIwLjggMzkuMiA1Ni4wMjQgMCAyNy43MTMtMTcuNTc3IDQ1LjU1OC00MS4yNzcgNDUuNTU4LTI4LjQ0IDAtNDIuOTg0LTE3LjctNDIuOTg0LTE3LjdsNy42MTUtMjUuMTZzMTQuOTUgMTIuODM1IDI3LjU2NSAxMi44MzVjOC4yNDMgMCAxMS41OTYtNi40OSAxMS41OTYtMTEuMjMyIDAtMTkuNjE2LTMyLjE2LTIwLjQ5MS0zMi4xNi01Mi43MjQgMC0yNy4xMjkgMTkuNDcyLTUzLjM4MiA1OC43NzgtNTMuMzgyIDE1LjE0NSAwIDIyLjYyNyA0LjMzOCAyMi42MjcgNC4zMzgiIGZpbGw9IiNGRkYiLz48L3N2Zz4=`;
export const SHOPIFY_CONN_OPTIONS = {
  shop: {
    display_name: 'Shop Domain',
    short_desc: 'Your Shopify store domain',
    desc: 'The domain name of your Shopify store (without https:// or .myshopify.com)',
    type: 'string',
  },
} satisfies TCustomConnOptions;

export const SHOPIFY_POST_AUTH_CODE_CONN_OPTIONS = {
  ping_headers: {
    type: 'hash',
  },
} satisfies TCustomConnOptions;

export const SHOPIFY_API_VERSION = '2025-07';

export const SHOPIFY_SCOPES = [
  'read_analytics',
  'write_assigned_fulfillment_orders',
  'read_assigned_fulfillment_orders',
  'read_customer_events',
  'write_checkout_branding_settings',
  'read_checkout_branding_settings',
  'write_custom_pixels',
  'read_custom_pixels',
  'write_customers',
  'read_customers',
  'write_discounts',
  'read_discounts',
  'write_discovery',
  'read_discovery',
  'write_draft_orders',
  'read_draft_orders',
  'write_files',
  'read_files',
  'write_fulfillments',
  'read_fulfillments',
  'write_gift_card_transactions',
  'read_gift_card_transactions',
  'write_gift_cards',
  'read_gift_cards',
  'write_inventory',
  'read_inventory',
  'write_legal_policies',
  'read_legal_policies',
  'write_locations',
  'read_locations',
  'write_marketing_events',
  'read_marketing_events',
  'write_merchant_managed_fulfillment_orders',
  'read_merchant_managed_fulfillment_orders',
  'write_metaobject_definitions',
  'read_metaobject_definitions',
  'write_online_store_navigation',
  'read_online_store_navigation',
  'write_metaobjects',
  'read_metaobjects',
  'write_online_store_pages',
  'read_online_store_pages',
  'write_order_edits',
  'read_order_edits',
  'write_orders',
  'read_orders',
  'write_packing_slip_templates',
  'read_packing_slip_templates',
  'write_payment_customizations',
  'read_payment_customizations',
  'write_payment_terms',
  'read_payment_terms',
  'write_pixels',
  'read_pixels',
  'write_price_rules',
  'read_price_rules',
  'write_product_feeds',
  'read_product_feeds',
  'write_product_listings',
  'read_product_listings',
  'read_products',
  'write_products',
  'write_publications',
  'read_publications',
  'write_purchase_options',
  'read_purchase_options',
  'write_reports',
  'read_reports',
  'write_resource_feedbacks',
  'read_resource_feedbacks',
  'write_returns',
  'read_returns',
  'write_channels',
  'read_channels',
  'write_script_tags',
  'read_script_tags',
  'write_shipping',
  'read_shipping',
  'write_locales',
  'read_locales',
  'write_markets',
  'read_markets',
  'read_shopify_payments_accounts',
  'read_shopify_payments_bank_accounts',
  'write_shopify_payments_disputes',
  'read_shopify_payments_disputes',
  'read_shopify_payments_payouts',
  'write_content',
  'read_content',
  'write_store_credit_account_transactions',
  'read_store_credit_account_transactions',
  'read_store_credit_accounts',
  'write_themes',
  'read_themes',
  'write_third_party_fulfillment_orders',
  'read_third_party_fulfillment_orders',
  'write_translations',
  'read_translations',
  'read_all_cart_transforms',
  'write_all_checkout_completion_target_customizations',
  'read_all_checkout_completion_target_customizations',
  'write_app_proxy',
  'read_app_proxy',
  'write_cart_transforms',
  'read_cart_transforms',
  'read_cash_tracking',
  'write_companies',
  'read_companies',
  'write_custom_fulfillment_services',
  'read_custom_fulfillment_services',
  'write_customer_data_erasure',
  'read_customer_data_erasure',
  'write_customer_merge',
  'read_customer_merge',
  'write_delivery_customizations',
  'read_delivery_customizations',
  'write_delivery_option_generators',
  'read_delivery_option_generators',
  'write_discounts_allocator_functions',
  'read_discounts_allocator_functions',
  'write_fulfillment_constraint_rules',
  'read_fulfillment_constraint_rules',
  'write_gates',
  'read_gates',
  'write_inventory_shipments',
  'read_inventory_shipments',
  'write_inventory_shipments_received_items',
  'read_inventory_shipments_received_items',
  'write_inventory_transfers',
  'read_inventory_transfers',
  'write_marketing_integrated_campaigns',
  'read_marketing_integrated_campaigns',
  'write_markets_home',
  'read_markets_home',
  'write_order_submission_rules',
  'read_order_submission_rules',
  'write_privacy_settings',
  'read_privacy_settings',
  'read_shopify_payments_provider_accounts_sensitive',
  'write_theme_code',
  'write_validations',
  'read_validations',
];

export type TShopifyContextWithConn =
  | TQoreAppActionFunctionContext<typeof SHOPIFY_CONN_OPTIONS>
  | undefined;
