export const intercomContactQueryFieldAllowedValues = [
  { display_name: 'ID', value: 'id' },
  { display_name: 'Role', value: 'role' },
  { display_name: 'Name', value: 'name' },
  { display_name: 'Avatar', value: 'avatar' },
  { display_name: 'Owner ID', value: 'owner_id' },
  { display_name: 'Email', value: 'email' },
  { display_name: 'Email Domain', value: 'email_domain' },
  { display_name: 'Phone', value: 'phone' },
  { display_name: 'External ID', value: 'external_id' },
  { display_name: 'Created At', value: 'created_at' },
  { display_name: 'Signed Up At', value: 'signed_up_at' },
  { display_name: 'Updated At', value: 'updated_at' },
  { display_name: 'Last Seen At', value: 'last_seen_at' },
  { display_name: 'Last Contacted At', value: 'last_contacted_at' },
  { display_name: 'Last Replied At', value: 'last_replied_at' },
  { display_name: 'Last Email Opened At', value: 'last_email_opened_at' },
  { display_name: 'Last Email Clicked At', value: 'last_email_clicked_at' },
  { display_name: 'Language Override', value: 'language_override' },
  { display_name: 'Browser', value: 'browser' },
  { display_name: 'Browser Language', value: 'browser_language' },
  { display_name: 'OS', value: 'os' },
  { display_name: 'Country', value: 'location.country' },
  { display_name: 'Region', value: 'location.region' },
  { display_name: 'City', value: 'location.city' },
  { display_name: 'Unsubscribed From Emails', value: 'unsubscribed_from_emails' },
  { display_name: 'Marked Email As Spam', value: 'marked_email_as_spam' },
  { display_name: 'Has Hard Bounced', value: 'has_hard_bounced' },
  { display_name: 'iOS Last Seen At', value: 'ios_last_seen_at' },
  { display_name: 'iOS App Version', value: 'ios_app_version' },
  { display_name: 'iOS Device', value: 'ios_device' },
  { display_name: 'iOS App Device', value: 'ios_app_device' },
  { display_name: 'iOS OS Version', value: 'ios_os_version' },
  { display_name: 'iOS App Name', value: 'ios_app_name' },
  { display_name: 'iOS SDK Version', value: 'ios_sdk_version' },
  { display_name: 'Android Last Seen At', value: 'android_last_seen_at' },
  { display_name: 'Android App Version', value: 'android_app_version' },
  { display_name: 'Android Device', value: 'android_device' },
  { display_name: 'Android App Name', value: 'android_app_name' },
  { display_name: 'Android SDK Version', value: 'android_sdk_version' },
  { display_name: 'Segment ID', value: 'segment_id' },
  { display_name: 'Tag ID', value: 'tag_id' },
];

export const intercomContactQueryFieldValues = intercomContactQueryFieldAllowedValues.map(
  (item) => item.value
);
