export const intercomConversationQueryFieldAllowedValues = [
  { display_name: 'ID', value: 'id' },
  { display_name: 'Created At', value: 'created_at' },
  { display_name: 'Updated At', value: 'updated_at' },
  { display_name: 'Source Type', value: 'source.type' },
  { display_name: 'Source ID', value: 'source.id' },
  { display_name: 'Source Delivered As', value: 'source.delivered_as' },
  { display_name: 'Source Subject', value: 'source.subject' },
  { display_name: 'Source Body', value: 'source.body' },
  { display_name: 'Source Author ID', value: 'source.author.id' },
  { display_name: 'Source Author Type', value: 'source.author.type' },
  { display_name: 'Source Author Name', value: 'source.author.name' },
  { display_name: 'Source Author Email', value: 'source.author.email' },
  { display_name: 'Source URL', value: 'source.url' },
  { display_name: 'Contact IDs', value: 'contact_ids' },
  { display_name: 'Teammate IDs', value: 'teammate_ids' },
  { display_name: 'Admin Assignee ID', value: 'admin_assignee_id' },
  { display_name: 'Team Assignee ID', value: 'team_assignee_id' },
  { display_name: 'Channel Initiated', value: 'channel_initiated' },
  { display_name: 'Open', value: 'open' },
  { display_name: 'Read', value: 'read' },
  { display_name: 'State', value: 'state' },
  { display_name: 'Waiting Since', value: 'waiting_since' },
  { display_name: 'Snoozed Until', value: 'snoozed_until' },
  { display_name: 'Tag IDs', value: 'tag_ids' },
  { display_name: 'Priority', value: 'priority' },
  { display_name: 'Time to Assignment', value: 'statistics.time_to_assignment' },
  { display_name: 'Time to Admin Reply', value: 'statistics.time_to_admin_reply' },
  { display_name: 'Time to First Close', value: 'statistics.time_to_first_close' },
  { display_name: 'Time to Last Close', value: 'statistics.time_to_last_close' },
  { display_name: 'Median Time to Reply', value: 'statistics.median_time_to_reply' },
  { display_name: 'First Contact Reply At', value: 'statistics.first_contact_reply_at' },
  { display_name: 'First Assignment At', value: 'statistics.first_assignment_at' },
  { display_name: 'First Admin Reply At', value: 'statistics.first_admin_reply_at' },
  { display_name: 'First Close At', value: 'statistics.first_close_at' },
  { display_name: 'Last Assignment At', value: 'statistics.last_assignment_at' },
  {
    display_name: 'Last Assignment Admin Reply At',
    value: 'statistics.last_assignment_admin_reply_at',
  },
  { display_name: 'Last Contact Reply At', value: 'statistics.last_contact_reply_at' },
  { display_name: 'Last Admin Reply At', value: 'statistics.last_admin_reply_at' },
  { display_name: 'Last Close At', value: 'statistics.last_close_at' },
  { display_name: 'Last Closed By ID', value: 'statistics.last_closed_by_id' },
  { display_name: 'Count Reopens', value: 'statistics.count_reopens' },
  { display_name: 'Count Assignments', value: 'statistics.count_assignments' },
  { display_name: 'Count Conversation Parts', value: 'statistics.count_conversation_parts' },
  { display_name: 'Conversation Rating Requested At', value: 'conversation_rating.requested_at' },
  { display_name: 'Conversation Rating Replied At', value: 'conversation_rating.replied_at' },
  { display_name: 'Conversation Rating Score', value: 'conversation_rating.score' },
  { display_name: 'Conversation Rating Remark', value: 'conversation_rating.remark' },
  { display_name: 'Conversation Rating Contact ID', value: 'conversation_rating.contact_id' },
  { display_name: 'Conversation Rating Admin ID', value: 'conversation_rating.admin_d' },
  { display_name: 'AI Agent Participated', value: 'ai_agent_participated' },
  { display_name: 'AI Agent Resolution State', value: 'ai_agent.resolution_state' },
  { display_name: 'AI Agent Last Answer Type', value: 'ai_agent.last_answer_type' },
  { display_name: 'AI Agent Rating', value: 'ai_agent.rating' },
  { display_name: 'AI Agent Rating Remark', value: 'ai_agent.rating_remark' },
  { display_name: 'AI Agent Source Type', value: 'ai_agent.source_type' },
  { display_name: 'AI Agent Source Title', value: 'ai_agent.source_title' },
];

export const intercomConversationQueryFieldValues = intercomConversationQueryFieldAllowedValues.map(
  (item) => item.value
);
