import { IQoreAllowedValue } from '@qoretechnologies/ts-toolkit';

export const QuickBooksInvoiceFieldsAllowedValues = [
  { value: 'AllowIPNPayment', display_name: 'Allow IPN Payment' },
  { value: 'AllowOnlinePayment', display_name: 'Allow Online Payment' },
  { value: 'AllowOnlineCreditCardPayment', display_name: 'Allow Online Credit Card Payment' },
  { value: 'AllowOnlineACHPayment', display_name: 'Allow Online ACH Payment' },
  { value: 'domain', display_name: 'Domain' },
  { value: 'sparse', display_name: 'Sparse' },
  { value: 'Id', display_name: 'Invoice ID' },
  { value: 'SyncToken', display_name: 'Sync Token' },
  { value: 'MetaData.CreateTime', display_name: 'Create Time' },
  { value: 'MetaData.LastModifiedByRef', display_name: 'Last Modified By Reference' },
  { value: 'MetaData.LastModifiedByRef.value', display_name: 'Last Modified By Value' },
  { value: 'MetaData.LastUpdatedTime', display_name: 'Last Updated Time' },
  { value: 'CustomField', display_name: 'Custom Fields' },
  { value: 'DocNumber', display_name: 'Document Number' },
  { value: 'TxnDate', display_name: 'Transaction Date' },
  { value: 'PrivateNote', display_name: 'Private Note' },
  { value: 'LinkedTxn', display_name: 'Linked Transactions' },
  { value: 'Line', display_name: 'Line Items' },
  { value: 'FreeFormAddress', display_name: 'Free Form Address' },
  { value: 'DueDate', display_name: 'Due Date' },
  { value: 'TotalAmt', display_name: 'Total Amount' },
  { value: 'ApplyTaxAfterDiscount', display_name: 'Apply Tax After Discount' },
  { value: 'PrintStatus', display_name: 'Print Status' },
  { value: 'EmailStatus', display_name: 'Email Status' },
  { value: 'Balance', display_name: 'Balance' },
] satisfies IQoreAllowedValue<string>[];
