/**
 * NetSuite Create Records
 *
 * Creates records sequentially via the REST API.
 * Extracts the created record ID from the Location response header
 * and fetches the full record via a follow-up GET.
 *
 * Copyright 2026 Qore Technologies, s.r.o.
 */

import { TQoreCreateRecordsFunction } from '@qoretechnologies/ts-toolkit';
import {
  getQoreContextRequiredValues,
  mapColumnFormatToObject,
  mapObjectToColumnFormat,
} from '../../../../global/helpers';
import { delay } from '../../../../global/helpers';
import { Debugger } from '../../../../utils/Debugger';
import { netsuiteRecordRequest, NetsuiteRecordError, REST_OPERATION_DELAY } from './constants';

/**
 * Create NetSuite records sequentially via REST API.
 * Input and output are in column format.
 */
export const createNetsuiteRecords: TQoreCreateRecordsFunction = async (
  context,
  records,
  options
) => {
  const { token, account_id } = getQoreContextRequiredValues({
    context,
    connectionFields: ['token', 'account_id'],
    ErrorClass: NetsuiteRecordError,
  });

  const recordType = options?.table;

  if (!recordType) {
    throw new NetsuiteRecordError('Table name is required to create records.');
  }

  const recordsArray = mapColumnFormatToObject(records);
  const createdRecords: Record<string, unknown>[] = [];

  for (let i = 0; i < recordsArray.length; i++) {
    const record = recordsArray[i];
    // Remove 'id' — auto-generated by NetSuite
    const { id, ...payload } = record;

    try {
      const response = await netsuiteRecordRequest({
        token,
        accountId: account_id,
        method: 'POST',
        recordType,
        data: payload as Record<string, unknown>,
      });

      // NetSuite returns 204 with Location header
      const location = response.headers?.location || '';
      const createdId = location.split('/').pop() || '';

      if (createdId) {
        try {
          const getResponse = await netsuiteRecordRequest<Record<string, unknown>>({
            token,
            accountId: account_id,
            method: 'GET',
            recordType,
            recordId: createdId,
          });
          createdRecords.push({ id: createdId, ...getResponse.data });
        } catch {
          // Fall back to returning just the ID with the original payload
          createdRecords.push({ id: createdId, ...payload });
        }
      } else {
        createdRecords.push({ id: 'unknown', ...payload });
      }
    } catch (error) {
      Debugger.log(`Failed to create ${recordType} record: ${error}`);
      throw new NetsuiteRecordError(`Failed to create ${recordType} record: ${error}`);
    }

    // Delay between creates to respect rate limits
    if (i < recordsArray.length - 1) {
      await delay(REST_OPERATION_DELAY);
    }
  }

  return mapObjectToColumnFormat(createdRecords);
};
