export const TypeformFieldTypeAllowedValues = [
  { value: 'calendly', display_name: 'Calendly' },
  { value: 'contact_info', display_name: 'Contact Info' },
  { value: 'date', display_name: 'Date' },
  { value: 'dropdown', display_name: 'Dropdown' },
  { value: 'email', display_name: 'Email' },
  { value: 'file_upload', display_name: 'File Upload' },
  { value: 'group', display_name: 'Group' },
  { value: 'legal', display_name: 'Legal' },
  { value: 'long_text', display_name: 'Long Text' },
  { value: 'matrix', display_name: 'Matrix' },
  { value: 'multiple_choice', display_name: 'Multiple Choice' },
  { value: 'nps', display_name: 'NPS' },
  { value: 'number', display_name: 'Number' },
  { value: 'opinion_scale', display_name: 'Opinion Scale' },
  { value: 'payment', display_name: 'Payment' },
  { value: 'phone_number', display_name: 'Phone Number' },
  { value: 'picture_choice', display_name: 'Picture Choice' },
  { value: 'ranking', display_name: 'Ranking' },
  { value: 'rating', display_name: 'Rating' },
  { value: 'short_text', display_name: 'Short Text' },
  { value: 'statement', display_name: 'Statement' },
  { value: 'website', display_name: 'Website' },
  { value: 'yes_no', display_name: 'Yes/No' },
];

export const TypeformFieldFormAllowedValues = [
  { value: 'cat', display_name: 'Cat' },
  { value: 'circle', display_name: 'Circle' },
  { value: 'cloud', display_name: 'Cloud' },
  { value: 'crown', display_name: 'Crown' },
  { value: 'dog', display_name: 'Dog' },
  { value: 'droplet', display_name: 'Droplet' },
  { value: 'flag', display_name: 'Flag' },
  { value: 'heart', display_name: 'Heart' },
  { value: 'lightbulb', display_name: 'Lightbulb' },
  { value: 'pencil', display_name: 'Pencil' },
  { value: 'skull', display_name: 'Skull' },
  { value: 'star', display_name: 'Star' },
  { value: 'thunderbolt', display_name: 'Thunderbolt' },
  { value: 'tick', display_name: 'Tick' },
  { value: 'trophy', display_name: 'Trophy' },
  { value: 'up', display_name: 'Up' },
  { value: 'user', display_name: 'User' },
];

export const TypeformPaymentCurrencyAllowedValues = [
  { value: 'AUD', display_name: 'AUD (Australian Dollar)' },
  { value: 'BRL', display_name: 'BRL (Brazilian Real)' },
  { value: 'CAD', display_name: 'CAD (Canadian Dollar)' },
  { value: 'CHF', display_name: 'CHF (Swiss Franc)' },
  { value: 'DKK', display_name: 'DKK (Danish Krone)' },
  { value: 'EUR', display_name: 'EUR (Euro)' },
  { value: 'GBP', display_name: 'GBP (British Pound)' },
  { value: 'MXN', display_name: 'MXN (Mexican Peso)' },
  { value: 'NOK', display_name: 'NOK (Norwegian Krone)' },
  { value: 'SEK', display_name: 'SEK (Swedish Krona)' },
  { value: 'USD', display_name: 'USD (US Dollar)' },
];

export const TypeformFormTypeAllowedValues = [
  { value: 'quiz', display_name: 'Quiz' },
  { value: 'classification', display_name: 'Classification' },
  { value: 'score', display_name: 'Score' },
  { value: 'branching', display_name: 'Branching' },
  { value: 'classification_branching', display_name: 'Classification Branching' },
  { value: 'score_branching', display_name: 'Score Branching' },
];

export const TypeformLanguageAllowedValues = [
  { value: 'en', display_name: 'English' },
  { value: 'es', display_name: 'Spanish' },
  { value: 'ca', display_name: 'Catalan' },
  { value: 'fr', display_name: 'French' },
  { value: 'de', display_name: 'German' },
  { value: 'ru', display_name: 'Russian' },
  { value: 'it', display_name: 'Italian' },
  { value: 'da', display_name: 'Danish' },
  { value: 'pt', display_name: 'Portuguese' },
  { value: 'ch', display_name: 'Chinese' },
  { value: 'zh', display_name: 'Chinese (Simplified)' },
  { value: 'nl', display_name: 'Dutch' },
  { value: 'no', display_name: 'Norwegian' },
  { value: 'uk', display_name: 'Ukrainian' },
  { value: 'ja', display_name: 'Japanese' },
  { value: 'ko', display_name: 'Korean' },
  { value: 'hr', display_name: 'Croatian' },
  { value: 'fi', display_name: 'Finnish' },
  { value: 'sv', display_name: 'Swedish' },
  { value: 'pl', display_name: 'Polish' },
  { value: 'el', display_name: 'Greek' },
  { value: 'hu', display_name: 'Hungarian' },
  { value: 'tr', display_name: 'Turkish' },
  { value: 'cs', display_name: 'Czech' },
  { value: 'et', display_name: 'Estonian' },
  { value: 'di', display_name: 'Divehi' },
];

export const TypeformFilterOperatorAllowedValues = [
  { value: 'begins_with', display_name: 'Begins With' },
  { value: 'ends_with', display_name: 'Ends With' },
  { value: 'contains', display_name: 'Contains' },
  { value: 'not_contains', display_name: 'Not Contains' },
  { value: 'lower_than', display_name: 'Lower Than' },
  { value: 'lower_equal_than', display_name: 'Lower Equal Than' },
  { value: 'greater_than', display_name: 'Greater Than' },
  { value: 'greater_equal_than', display_name: 'Greater Equal Than' },
  { value: 'is', display_name: 'Is' },
  { value: 'is_not', display_name: 'Is Not' },
  { value: 'equal', display_name: 'Equal' },
  { value: 'not_equal', display_name: 'Not Equal' },
  { value: 'always', display_name: 'Always' },
  { value: 'on', display_name: 'On' },
  { value: 'not_on', display_name: 'Not On' },
  { value: 'earlier_than', display_name: 'Earlier Than' },
  { value: 'earlier_than_or_on', display_name: 'Earlier Than Or On' },
  { value: 'later_than', display_name: 'Later Than' },
  { value: 'later_than_or_on', display_name: 'Later Than Or On' },
];
