{
  "swagger": "2.0",
  "info": {
    "description": "",
    "title": "Contacts",
    "version": "v3",
    "x-hubspot-api-use-case": "Retrieve a contact list by ID to bring that contact data into your external system.",
    "x-hubspot-documentation-banner": "NONE",
    "x-hubspot-introduction": "Use the contact lists API to create and manage contact lists.",
    "x-hubspot-product-tier-requirements": {
      "cms": "FREE",
      "marketing": "FREE",
      "sales": "FREE",
      "service": "FREE"
    },
    "x-hubspot-related-documentation": [
      {
        "name": "Contacts Overview",
        "url": "https://hubspotqa.dev/guides/api/crm/objects/contacts"
      }
    ]
  },
  "host": "api.hubapiqa.com",
  "basePath": "/",
  "schemes": [
    "https"
  ],
  "paths": {
    "/crm/v3/objects/contacts": {
      "get": {
        "security": [
          {
            "oauth2": [
              "crm.objects.contacts.read"
            ]
          },
          {
            "private_apps": [
              "crm.objects.contacts.read"
            ]
          }
        ],
        "tags": [
          "Basic"
        ],
        "description": "Read a page of contacts. Control what is returned via the `properties` query param.",
        "operationId": "get-/crm/v3/objects/contacts",
        "summary": "List"
      },
      "post": {
        "security": [
          {
            "oauth2": [
              "crm.objects.contacts.write"
            ]
          },
          {
            "private_apps": [
              "crm.objects.contacts.write"
            ]
          }
        ],
        "tags": [
          "Basic"
        ],
        "description": "Create a contact with the given properties and return a copy of the object, including the ID. Documentation and examples for creating standard contacts is provided.",
        "operationId": "post-/crm/v3/objects/contacts",
        "summary": "Create"
      }
    },
    "/crm/v3/objects/contacts/batch/archive": {
      "post": {
        "security": [
          {
            "oauth2": [
              "crm.objects.contacts.write"
            ]
          },
          {
            "private_apps": [
              "crm.objects.contacts.write"
            ]
          }
        ],
        "tags": [
          "Batch"
        ],
        "operationId": "post-/crm/v3/objects/contacts/batch/archive",
        "summary": "Archive a batch of contacts by ID"
      }
    },
    "/crm/v3/objects/contacts/batch/create": {
      "post": {
        "security": [
          {
            "oauth2": [
              "crm.objects.contacts.write"
            ]
          },
          {
            "private_apps": [
              "crm.objects.contacts.write"
            ]
          }
        ],
        "tags": [
          "Batch"
        ],
        "operationId": "post-/crm/v3/objects/contacts/batch/create",
        "summary": "Create a batch of contacts"
      }
    },
    "/crm/v3/objects/contacts/batch/read": {
      "post": {
        "security": [
          {
            "oauth2": [
              "crm.objects.contacts.read"
            ]
          },
          {
            "private_apps": [
              "crm.objects.contacts.read"
            ]
          }
        ],
        "tags": [
          "Batch"
        ],
        "operationId": "post-/crm/v3/objects/contacts/batch/read",
        "summary": "Read a batch of contacts by internal ID, or unique property values"
      }
    },
    "/crm/v3/objects/contacts/batch/update": {
      "post": {
        "security": [
          {
            "oauth2": [
              "crm.objects.contacts.write"
            ]
          },
          {
            "private_apps": [
              "crm.objects.contacts.write"
            ]
          }
        ],
        "tags": [
          "Batch"
        ],
        "operationId": "post-/crm/v3/objects/contacts/batch/update",
        "summary": "Update a batch of contacts"
      }
    },
    "/crm/v3/objects/contacts/gdpr-delete": {
      "post": {
        "security": [
          {
            "oauth2": [
              "crm.objects.contacts.write"
            ]
          },
          {
            "private_apps": [
              "crm.objects.contacts.write"
            ]
          }
        ],
        "tags": [
          "GDPR"
        ],
        "description": "Permanently delete a contact and all associated content to follow GDPR. Use optional property 'idProperty' set to 'email' to identify contact by email address. If email address is not found, the email address will be added to a blocklist and prevent it from being used in the future.",
        "operationId": "post-/crm/v3/objects/contacts/gdpr-delete",
        "summary": "GDPR DELETE"
      }
    },
    "/crm/v3/objects/contacts/merge": {
      "post": {
        "security": [
          {
            "oauth2": [
              "crm.objects.contacts.write"
            ]
          },
          {
            "private_apps": [
              "crm.objects.contacts.write"
            ]
          }
        ],
        "tags": [
          "Public_Object"
        ],
        "operationId": "post-/crm/v3/objects/contacts/merge",
        "summary": "Merge two contacts with same type"
      }
    },
    "/crm/v3/objects/contacts/search": {
      "post": {
        "security": [
          {
            "oauth2": [
              "crm.objects.contacts.read"
            ]
          },
          {
            "private_apps": [
              "crm.objects.contacts.read"
            ]
          }
        ],
        "tags": [
          "Search"
        ],
        "operationId": "post-/crm/v3/objects/contacts/search",
        "x-hubspot-rate-limit-exemptions": [
          "ten-secondly"
        ]
      }
    },
    "/crm/v3/objects/contacts/{contactId}": {
      "delete": {
        "security": [
          {
            "oauth2": [
              "crm.objects.contacts.write"
            ]
          },
          {
            "private_apps": [
              "crm.objects.contacts.write"
            ]
          }
        ],
        "tags": [
          "Basic"
        ],
        "description": "Move an Object identified by `{contactId}` to the recycling bin.",
        "operationId": "delete-/crm/v3/objects/contacts/{contactId}",
        "summary": "Archive"
      },
      "get": {
        "security": [
          {
            "oauth2": [
              "crm.objects.contacts.read"
            ]
          },
          {
            "private_apps": [
              "crm.objects.contacts.read"
            ]
          }
        ],
        "tags": [
          "Basic"
        ],
        "description": "Read an Object identified by `{contactId}`. `{contactId}` refers to the internal object ID by default, or optionally any unique property value as specified by the `idProperty` query param.  Control what is returned via the `properties` query param.",
        "operationId": "get-/crm/v3/objects/contacts/{contactId}",
        "summary": "Read"
      },
      "patch": {
        "security": [
          {
            "oauth2": [
              "crm.objects.contacts.write"
            ]
          },
          {
            "private_apps": [
              "crm.objects.contacts.write"
            ]
          }
        ],
        "tags": [
          "Basic"
        ],
        "description": "Perform a partial update of an Object identified by `{contactId}`. `{contactId}` refers to the internal object ID by default, or optionally any unique property value as specified by the `idProperty` query param. Provided property values will be overwritten. Read-only and non-existent properties will be ignored. Properties values can be cleared by passing an empty string.",
        "operationId": "patch-/crm/v3/objects/contacts/{contactId}",
        "summary": "Update"
      }
    }
  },
  "securityDefinitions": {
    "oauth2": {
      "authorizationUrl": "https://app.hubspot.com/oauth/authorize",
      "flow": "accessCode",
      "scopes": {
        "crm.objects.carts.read": "Read carts",
        "crm.objects.carts.write": "Write cart",
        "crm.objects.commercepayments.read": "Read the COMMERCE_PAYMENT object.",
        "crm.objects.companies.read": " ",
        "crm.objects.companies.write": " ",
        "crm.objects.contacts.read": " ",
        "crm.objects.contacts.write": " ",
        "crm.objects.deals.read": " ",
        "crm.objects.deals.write": " ",
        "crm.objects.invoices.read": "Read invoices objects",
        "crm.objects.line_items.read": "Line Items",
        "crm.objects.line_items.write": "Line Items",
        "crm.objects.orders.read": "Read orders",
        "crm.objects.orders.write": "Write orders",
        "crm.objects.quotes.read": "Quotes",
        "crm.objects.quotes.write": "Quotes",
        "crm.objects.subscriptions.read": "Read Commerce Subscriptions",
        "crm.objects.users.read": "Read User CRM objects",
        "crm.objects.users.write": "Write User CRM objects"
      },
      "tokenUrl": "https://api.hubapi.com/oauth/v1/token",
      "type": "oauth2"
    },
    "oauth2_legacy": {
      "authorizationUrl": "https://app.hubspot.com/oauth/authorize",
      "flow": "accessCode",
      "scopes": {
        "crm.objects.custom.read": "View custom object records",
        "crm.objects.custom.write": "Change custom object records",
        "crm.objects.goals.read": "Read goals",
        "crm.objects.goals.write": "Write goals",
        "crm.objects.leads.read": "Read lead objects",
        "crm.objects.leads.write": "Modify lead objects",
        "e-commerce": "e-commerce",
        "tickets": "Read and write tickets"
      },
      "tokenUrl": "https://api.hubapi.com/oauth/v1/token",
      "type": "oauth2"
    },
    "private_apps": {
      "flows": {
        "authorizationCode": {
          "scopes": {
            "crm.objects.contacts.read": "",
            "crm.objects.contacts.write": ""
          }
        }
      },
      "in": "header",
      "name": "private-app",
      "type": "apiKey"
    },
    "private_apps_legacy": {
      "flows": {
        "authorizationCode": {
          "scopes": {}
        }
      },
      "in": "header",
      "name": "private-app-legacy",
      "type": "apiKey"
    }
  },
  "tags": [
    {
      "name": "Batch"
    },
    {
      "name": "Basic"
    },
    {
      "name": "Public_Object"
    },
    {
      "name": "Associations"
    },
    {
      "name": "GDPR"
    },
    {
      "name": "Search"
    }
  ],
  "x-components": {
  },
  "x-hubspot-available-client-libraries": [
    "PHP",
    "Node",
    "Ruby",
    "Python"
  ],
  "x-hubspot-documentation-banner": "NONE",
  "x-hubspot-product-tier-requirements": {
    "cms": "FREE",
    "marketing": "FREE",
    "sales": "FREE",
    "service": "FREE"
  }
}
