{
  "swagger": "2.0",
  "info": {
    "description": "CRM objects such as companies, contacts, deals, line items, products, tickets, and quotes are standard objects in HubSpot’s CRM. These core building blocks support custom properties, store critical information, and play a central role in the HubSpot application.\n\n## Supported Object Types\n\nThis API provides access to collections of CRM objects, which return a map of property names to values. Each object type has its own set of default properties, which can be found by exp[...]",
    "title": "Custom Objects",
    "version": "v3",
    "x-hubspot-api-use-case": "After creating a Cars custom object, you can create a record for each car, then associate it with the contact who bought it.",
    "x-hubspot-documentation-banner": "NONE",
    "x-hubspot-introduction": "Use the objects API to create and manage records for an object. The endpoints can be used for objects included in all accounts, such as contacts and companies, as well as for custom objects in Enterprise accounts.",
    "x-hubspot-product-tier-requirements": {
      "cms": "FREE",
      "marketing": "FREE",
      "sales": "FREE",
      "service": "FREE"
    },
    "x-hubspot-related-documentation": [
      {
        "name": "Objects Guide",
        "url": "https://developers.hubspot.com/docs/guides/api/crm/using-object-apis"
      }
    ]
  },
  "host": "api.hubapi.com",
  "basePath": "/",
  "schemes": [
    "https"
  ],
  "paths": {
    "/crm/v3/objects/{objectType}": {
      "get": {
        "security": [
          {
            "private_apps": [
              "crm.objects.listings.write"
            ]
          },
          {
            "private_apps": [
              "crm.objects.services.read"
            ]
          },
          {
            "oauth2": [
              "crm.objects.listings.write"
            ]
          },
          {
            "oauth2_legacy": [
              "media_bridge.read"
            ]
          },
          {
            "private_apps": [
              "crm.objects.orders.read"
            ]
          },
          {
            "private_apps": [
              "crm.objects.appointments.write"
            ]
          },
          {
            "private_apps": [
              "crm.objects.deals.read"
            ]
          },
          {
            "oauth2": [
              "crm.objects.orders.read"
            ]
          },
          {
            "private_apps": [
              "crm.objects.subscriptions.read"
            ]
          },
          {
            "oauth2": [
              "crm.objects.deals.read"
            ]
          },
          {
            "private_apps_legacy": [
              "contacts"
            ]
          },
          {
            "oauth2": [
              "crm.objects.subscriptions.read"
            ]
          },
          {
            "private_apps": [
              "crm.objects.companies.read"
            ]
          },
          {
            "oauth2": [
              "crm.objects.companies.read"
            ]
          },
          {
            "private_apps_legacy": [
              "crm.objects.goals.read"
            ]
          },
          {
            "private_apps": [
              "crm.objects.users.write"
            ]
          },
          {
            "private_apps_legacy": [
              "media_bridge.read"
            ]
          },
          {
            "private_apps": [
              "crm.objects.companies.write"
            ]
          },
          {
            "oauth2": [
              "crm.objects.companies.write"
            ]
          },
          {
            "oauth2_legacy": [
              "tickets"
            ]
          },
          {
            "private_apps": [
              "crm.objects.users.read"
            ]
          },
          {
            "private_apps_legacy": [
              "crm.objects.custom.write"
            ]
          },
          {
            "oauth2": [
              "crm.objects.users.read"
            ]
          },
          {
            "oauth2": [
              "crm.objects.users.write"
            ]
          },
          {
            "private_apps_legacy": [
              "e-commerce"
            ]
          },
          {
            "private_apps": [
              "crm.objects.carts.write"
            ]
          },
          {
            "oauth2": [
              "crm.objects.carts.write"
            ]
          },
          {
            "oauth2_legacy": [
              "e-commerce"
            ]
          },
          {
            "private_apps_legacy": [
              "tickets"
            ]
          },
          {
            "oauth2_legacy": [
              "crm.objects.goals.read"
            ]
          },
          {
            "oauth2": [
              "crm.objects.appointments.write"
            ]
          },
          {
            "oauth2_legacy": [
              "crm.objects.custom.write"
            ]
          },
          {
            "oauth2": [
              "crm.objects.contacts.read"
            ]
          },
          {
            "private_apps": [
              "crm.objects.orders.write"
            ]
          },
          {
            "private_apps": [
              "crm.objects.services.write"
            ]
          },
          {
            "oauth2": [
              "crm.objects.services.write"
            ]
          },
          {
            "oauth2": [
              "crm.objects.orders.write"
            ]
          },
          {
            "oauth2": [
              "crm.objects.commercepayments.read"
            ]
          },
          {
            "private_apps": [
              "crm.objects.commercepayments.read"
            ]
          },
          {
            "private_apps": [
              "crm.objects.contacts.read"
            ]
          },
          {
            "private_apps": [
              "crm.objects.deals.write"
            ]
          },
          {
            "oauth2": [
              "crm.objects.deals.write"
            ]
          },
          {
            "private_apps": [
              "crm.objects.appointments.read"
            ]
          },
          {
            "oauth2": [
              "crm.objects.invoices.read"
            ]
          },
          {
            "oauth2": [
              "crm.objects.appointments.read"
            ]
          },
          {
            "private_apps": [
              "crm.objects.invoices.read"
            ]
          },
          {
            "private_apps": [
              "crm.objects.leads.write"
            ]
          },
          {
            "oauth2": [
              "crm.objects.quotes.write"
            ]
          },
          {
            "private_apps": [
              "crm.objects.quotes.write"
            ]
          },
          {
            "oauth2": [
              "crm.objects.leads.read"
            ]
          },
          {
            "oauth2": [
              "crm.objects.leads.write"
            ]
          },
          {
            "private_apps": [
              "crm.objects.courses.write"
            ]
          },
          {
            "private_apps": [
              "crm.objects.partner-clients.write"
            ]
          },
          {
            "private_apps": [
              "crm.objects.line_items.read"
            ]
          },
          {
            "oauth2": [
              "crm.objects.contacts.write"
            ]
          },
          {
            "private_apps": [
              "crm.objects.contacts.write"
            ]
          },
          {
            "oauth2": [
              "crm.objects.partner-clients.write"
            ]
          },
          {
            "oauth2": [
              "crm.objects.line_items.read"
            ]
          },
          {
            "private_apps": [
              "crm.objects.leads.read"
            ]
          },
          {
            "oauth2_legacy": [
              "crm.objects.custom.read"
            ]
          },
          {
            "private_apps_legacy": [
              "crm.objects.custom.read"
            ]
          },
          {
            "oauth2": [
              "crm.objects.line_items.write"
            ]
          },
          {
            "private_apps": [
              "crm.objects.listings.read"
            ]
          },
          {
            "private_apps": [
              "crm.objects.line_items.write"
            ]
          },
          {
            "oauth2": [
              "crm.objects.courses.read"
            ]
          },
          {
            "private_apps": [
              "crm.objects.courses.read"
            ]
          },
          {
            "oauth2": [
              "crm.objects.listings.read"
            ]
          },
          {
            "private_apps": [
              "crm.objects.carts.read"
            ]
          },
          {
            "oauth2": [
              "crm.objects.courses.write"
            ]
          },
          {
            "oauth2": [
              "crm.objects.quotes.read"
            ]
          },
          {
            "oauth2": [
              "crm.objects.partner-clients.read"
            ]
          },
          {
            "oauth2": [
              "crm.objects.services.read"
            ]
          },
          {
            "oauth2": [
              "crm.objects.carts.read"
            ]
          },
          {
            "private_apps": [
              "crm.objects.partner-clients.read"
            ]
          },
          {
            "private_apps": [
              "crm.objects.quotes.read"
            ]
          }
        ],
        "tags": [
          "Basic"
        ],
        "description": "Read a page of objects. Control what is returned via the `properties` query param.",
        "operationId": "get-/crm/v3/objects/{objectType}_getPage",
        "summary": "List"
      },
      "post": {
        "security": [
          {
            "private_apps": [
              "crm.objects.listings.write"
            ]
          },
          {
            "private_apps": [
              "crm.objects.services.read"
            ]
          },
          {
            "oauth2": [
              "crm.objects.listings.write"
            ]
          },
          {
            "oauth2_legacy": [
              "media_bridge.read"
            ]
          },
          {
            "private_apps": [
              "crm.objects.orders.read"
            ]
          },
          {
            "private_apps": [
              "crm.objects.appointments.write"
            ]
          },
          {
            "private_apps": [
              "crm.objects.deals.read"
            ]
          },
          {
            "oauth2": [
              "crm.objects.orders.read"
            ]
          },
          {
            "private_apps": [
              "crm.objects.subscriptions.read"
            ]
          },
          {
            "oauth2": [
              "crm.objects.deals.read"
            ]
          },
          {
            "private_apps_legacy": [
              "contacts"
            ]
          },
          {
            "oauth2": [
              "crm.objects.subscriptions.read"
            ]
          },
          {
            "private_apps": [
              "crm.objects.companies.read"
            ]
          },
          {
            "oauth2": [
              "crm.objects.companies.read"
            ]
          },
          {
            "private_apps_legacy": [
              "crm.objects.goals.read"
            ]
          },
          {
            "private_apps": [
              "crm.objects.users.write"
            ]
          },
          {
            "private_apps_legacy": [
              "media_bridge.read"
            ]
          },
          {
            "private_apps": [
              "crm.objects.companies.write"
            ]
          },
          {
            "oauth2": [
              "crm.objects.companies.write"
            ]
          },
          {
            "oauth2_legacy": [
              "tickets"
            ]
          },
          {
            "private_apps": [
              "crm.objects.users.read"
            ]
          },
          {
            "private_apps_legacy": [
              "crm.objects.custom.write"
            ]
          },
          {
            "oauth2": [
              "crm.objects.users.read"
            ]
          },
          {
            "oauth2": [
              "crm.objects.users.write"
            ]
          },
          {
            "private_apps_legacy": [
              "e-commerce"
            ]
          },
          {
            "private_apps": [
              "crm.objects.carts.write"
            ]
          },
          {
            "oauth2": [
              "crm.objects.carts.write"
            ]
          },
          {
            "oauth2_legacy": [
              "e-commerce"
            ]
          },
          {
            "private_apps_legacy": [
              "tickets"
            ]
          },
          {
            "oauth2_legacy": [
              "crm.objects.goals.read"
            ]
          },
          {
            "oauth2": [
              "crm.objects.appointments.write"
            ]
          },
          {
            "oauth2_legacy": [
              "crm.objects.custom.write"
            ]
          },
          {
            "oauth2": [
              "crm.objects.contacts.read"
            ]
          },
          {
            "private_apps": [
              "crm.objects.orders.write"
            ]
          },
          {
            "private_apps": [
              "crm.objects.services.write"
            ]
          },
          {
            "oauth2": [
              "crm.objects.services.write"
            ]
          },
          {
            "oauth2": [
              "crm.objects.orders.write"
            ]
          },
          {
            "oauth2": [
              "crm.objects.commercepayments.read"
            ]
          },
          {
            "private_apps": [
              "crm.objects.commercepayments.read"
            ]
          },
          {
            "private_apps": [
              "crm.objects.contacts.read"
            ]
          },
          {
            "private_apps": [
              "crm.objects.deals.write"
            ]
          },
          {
            "oauth2": [
              "crm.objects.deals.write"
            ]
          },
          {
            "private_apps": [
              "crm.objects.appointments.read"
            ]
          },
          {
            "oauth2": [
              "crm.objects.invoices.read"
            ]
          },
          {
            "oauth2": [
              "crm.objects.appointments.read"
            ]
          },
          {
            "private_apps": [
              "crm.objects.invoices.read"
            ]
          },
          {
            "private_apps": [
              "crm.objects.leads.write"
            ]
          },
          {
            "oauth2": [
              "crm.objects.quotes.write"
            ]
          },
          {
            "private_apps": [
              "crm.objects.quotes.write"
            ]
          },
          {
            "oauth2": [
              "crm.objects.leads.read"
            ]
          },
          {
            "oauth2": [
              "crm.objects.leads.write"
            ]
          },
          {
            "private_apps": [
              "crm.objects.courses.write"
            ]
          },
          {
            "private_apps": [
              "crm.objects.partner-clients.write"
            ]
          },
          {
            "private_apps": [
              "crm.objects.line_items.read"
            ]
          },
          {
            "oauth2": [
              "crm.objects.contacts.write"
            ]
          },
          {
            "private_apps": [
              "crm.objects.contacts.write"
            ]
          },
          {
            "oauth2": [
              "crm.objects.partner-clients.write"
            ]
          },
          {
            "oauth2": [
              "crm.objects.line_items.read"
            ]
          },
          {
            "private_apps": [
              "crm.objects.leads.read"
            ]
          },
          {
            "oauth2_legacy": [
              "crm.objects.custom.read"
            ]
          },
          {
            "private_apps_legacy": [
              "crm.objects.custom.read"
            ]
          },
          {
            "oauth2": [
              "crm.objects.line_items.write"
            ]
          },
          {
            "private_apps": [
              "crm.objects.listings.read"
            ]
          },
          {
            "private_apps": [
              "crm.objects.line_items.write"
            ]
          },
          {
            "oauth2": [
              "crm.objects.courses.read"
            ]
          },
          {
            "private_apps": [
              "crm.objects.courses.read"
            ]
          },
          {
            "oauth2": [
              "crm.objects.listings.read"
            ]
          },
          {
            "private_apps": [
              "crm.objects.carts.read"
            ]
          },
          {
            "oauth2": [
              "crm.objects.courses.write"
            ]
          },
          {
            "oauth2": [
              "crm.objects.quotes.read"
            ]
          },
          {
            "oauth2": [
              "crm.objects.partner-clients.read"
            ]
          },
          {
            "oauth2": [
              "crm.objects.services.read"
            ]
          },
          {
            "oauth2": [
              "crm.objects.carts.read"
            ]
          },
          {
            "private_apps": [
              "crm.objects.partner-clients.read"
            ]
          },
          {
            "private_apps": [
              "crm.objects.quotes.read"
            ]
          }
        ],
        "tags": [
          "Basic"
        ],
        "description": "Create a CRM object with the given properties and return a copy of the object, including the ID. Documentation and examples for creating standard objects is provided.",
        "operationId": "post-/crm/v3/objects/{objectType}_create",
        "summary": "Create"
      }
    },
    "/crm/v3/objects/{objectType}/batch/archive": {
      "post": {
        "security": [
          {
            "private_apps": [
              "crm.objects.listings.write"
            ]
          },
          {
            "private_apps": [
              "crm.objects.services.read"
            ]
          },
          {
            "oauth2": [
              "crm.objects.listings.write"
            ]
          },
          {
            "oauth2_legacy": [
              "media_bridge.read"
            ]
          },
          {
            "private_apps": [
              "crm.objects.orders.read"
            ]
          },
          {
            "private_apps": [
              "crm.objects.appointments.write"
            ]
          },
          {
            "private_apps": [
              "crm.objects.deals.read"
            ]
          },
          {
            "oauth2": [
              "crm.objects.orders.read"
            ]
          },
          {
            "private_apps": [
              "crm.objects.subscriptions.read"
            ]
          },
          {
            "oauth2": [
              "crm.objects.deals.read"
            ]
          },
          {
            "private_apps_legacy": [
              "contacts"
            ]
          },
          {
            "oauth2": [
              "crm.objects.subscriptions.read"
            ]
          },
          {
            "private_apps": [
              "crm.objects.companies.read"
            ]
          },
          {
            "oauth2": [
              "crm.objects.companies.read"
            ]
          },
          {
            "private_apps_legacy": [
              "crm.objects.goals.read"
            ]
          },
          {
            "private_apps": [
              "crm.objects.users.write"
            ]
          },
          {
            "private_apps_legacy": [
              "media_bridge.read"
            ]
          },
          {
            "private_apps": [
              "crm.objects.companies.write"
            ]
          },
          {
            "oauth2": [
              "crm.objects.companies.write"
            ]
          },
          {
            "oauth2_legacy": [
              "tickets"
            ]
          },
          {
            "private_apps": [
              "crm.objects.users.read"
            ]
          },
          {
            "private_apps_legacy": [
              "crm.objects.custom.write"
            ]
          },
          {
            "oauth2": [
              "crm.objects.users.read"
            ]
          },
          {
            "oauth2": [
              "crm.objects.users.write"
            ]
          },
          {
            "private_apps_legacy": [
              "e-commerce"
            ]
          },
          {
            "private_apps": [
              "crm.objects.carts.write"
            ]
          },
          {
            "oauth2": [
              "crm.objects.carts.write"
            ]
          },
          {
            "oauth2_legacy": [
              "e-commerce"
            ]
          },
          {
            "private_apps_legacy": [
              "tickets"
            ]
          },
          {
            "oauth2_legacy": [
              "crm.objects.goals.read"
            ]
          },
          {
            "oauth2": [
              "crm.objects.appointments.write"
            ]
          },
          {
            "oauth2_legacy": [
              "crm.objects.custom.write"
            ]
          },
          {
            "oauth2": [
              "crm.objects.contacts.read"
            ]
          },
          {
            "private_apps": [
              "crm.objects.orders.write"
            ]
          },
          {
            "private_apps": [
              "crm.objects.services.write"
            ]
          },
          {
            "oauth2": [
              "crm.objects.services.write"
            ]
          },
          {
            "oauth2": [
              "crm.objects.orders.write"
            ]
          },
          {
            "oauth2": [
              "crm.objects.commercepayments.read"
            ]
          },
          {
            "private_apps": [
              "crm.objects.commercepayments.read"
            ]
          },
          {
            "private_apps": [
              "crm.objects.contacts.read"
            ]
          },
          {
            "private_apps": [
              "crm.objects.deals.write"
            ]
          },
          {
            "oauth2": [
              "crm.objects.deals.write"
            ]
          },
          {
            "private_apps": [
              "crm.objects.appointments.read"
            ]
          },
          {
            "oauth2": [
              "crm.objects.invoices.read"
            ]
          },
          {
            "oauth2": [
              "crm.objects.appointments.read"
            ]
          },
          {
            "private_apps": [
              "crm.objects.invoices.read"
            ]
          },
          {
            "private_apps": [
              "crm.objects.leads.write"
            ]
          },
          {
            "oauth2": [
              "crm.objects.quotes.write"
            ]
          },
          {
            "private_apps": [
              "crm.objects.quotes.write"
            ]
          },
          {
            "oauth2": [
              "crm.objects.leads.read"
            ]
          },
          {
            "oauth2": [
              "crm.objects.leads.write"
            ]
          },
          {
            "private_apps": [
              "crm.objects.courses.write"
            ]
          },
          {
            "private_apps": [
              "crm.objects.partner-clients.write"
            ]
          },
          {
            "private_apps": [
              "crm.objects.line_items.read"
            ]
          },
          {
            "oauth2": [
              "crm.objects.contacts.write"
            ]
          },
          {
            "private_apps": [
              "crm.objects.contacts.write"
            ]
          },
          {
            "oauth2": [
              "crm.objects.partner-clients.write"
            ]
          },
          {
            "oauth2": [
              "crm.objects.line_items.read"
            ]
          },
          {
            "private_apps": [
              "crm.objects.leads.read"
            ]
          },
          {
            "oauth2_legacy": [
              "crm.objects.custom.read"
            ]
          },
          {
            "private_apps_legacy": [
              "crm.objects.custom.read"
            ]
          },
          {
            "oauth2": [
              "crm.objects.line_items.write"
            ]
          },
          {
            "private_apps": [
              "crm.objects.listings.read"
            ]
          },
          {
            "private_apps": [
              "crm.objects.line_items.write"
            ]
          },
          {
            "oauth2": [
              "crm.objects.courses.read"
            ]
          },
          {
            "private_apps": [
              "crm.objects.courses.read"
            ]
          },
          {
            "oauth2": [
              "crm.objects.listings.read"
            ]
          },
          {
            "private_apps": [
              "crm.objects.carts.read"
            ]
          },
          {
            "oauth2": [
              "crm.objects.courses.write"
            ]
          },
          {
            "oauth2": [
              "crm.objects.quotes.read"
            ]
          },
          {
            "oauth2": [
              "crm.objects.partner-clients.read"
            ]
          },
          {
            "oauth2": [
              "crm.objects.services.read"
            ]
          },
          {
            "oauth2": [
              "crm.objects.carts.read"
            ]
          },
          {
            "private_apps": [
              "crm.objects.partner-clients.read"
            ]
          },
          {
            "private_apps": [
              "crm.objects.quotes.read"
            ]
          }
        ],
        "tags": [
          "Batch"
        ],
        "operationId": "post-/crm/v3/objects/{objectType}/batch/archive_archive",
        "summary": "Archive a batch of objects by ID"
      }
    },
    "/crm/v3/objects/{objectType}/batch/create": {
      "post": {
        "security": [
          {
            "private_apps": [
              "crm.objects.listings.write"
            ]
          },
          {
            "private_apps": [
              "crm.objects.services.read"
            ]
          },
          {
            "oauth2": [
              "crm.objects.listings.write"
            ]
          },
          {
            "oauth2_legacy": [
              "media_bridge.read"
            ]
          },
          {
            "private_apps": [
              "crm.objects.orders.read"
            ]
          },
          {
            "private_apps": [
              "crm.objects.appointments.write"
            ]
          },
          {
            "private_apps": [
              "crm.objects.deals.read"
            ]
          },
          {
            "oauth2": [
              "crm.objects.orders.read"
            ]
          },
          {
            "private_apps": [
              "crm.objects.subscriptions.read"
            ]
          },
          {
            "oauth2": [
              "crm.objects.deals.read"
            ]
          },
          {
            "private_apps_legacy": [
              "contacts"
            ]
          },
          {
            "oauth2": [
              "crm.objects.subscriptions.read"
            ]
          },
          {
            "private_apps": [
              "crm.objects.companies.read"
            ]
          },
          {
            "oauth2": [
              "crm.objects.companies.read"
            ]
          },
          {
            "private_apps_legacy": [
              "crm.objects.goals.read"
            ]
          },
          {
            "private_apps": [
              "crm.objects.users.write"
            ]
          },
          {
            "private_apps_legacy": [
              "media_bridge.read"
            ]
          },
          {
            "private_apps": [
              "crm.objects.companies.write"
            ]
          },
          {
            "oauth2": [
              "crm.objects.companies.write"
            ]
          },
          {
            "oauth2_legacy": [
              "tickets"
            ]
          },
          {
            "private_apps": [
              "crm.objects.users.read"
            ]
          },
          {
            "private_apps_legacy": [
              "crm.objects.custom.write"
            ]
          },
          {
            "oauth2": [
              "crm.objects.users.read"
            ]
          },
          {
            "oauth2": [
              "crm.objects.users.write"
            ]
          },
          {
            "private_apps_legacy": [
              "e-commerce"
            ]
          },
          {
            "private_apps": [
              "crm.objects.carts.write"
            ]
          },
          {
            "oauth2": [
              "crm.objects.carts.write"
            ]
          },
          {
            "oauth2_legacy": [
              "e-commerce"
            ]
          },
          {
            "private_apps_legacy": [
              "tickets"
            ]
          },
          {
            "oauth2_legacy": [
              "crm.objects.goals.read"
            ]
          },
          {
            "oauth2": [
              "crm.objects.appointments.write"
            ]
          },
          {
            "oauth2_legacy": [
              "crm.objects.custom.write"
            ]
          },
          {
            "oauth2": [
              "crm.objects.contacts.read"
            ]
          },
          {
            "private_apps": [
              "crm.objects.orders.write"
            ]
          },
          {
            "private_apps": [
              "crm.objects.services.write"
            ]
          },
          {
            "oauth2": [
              "crm.objects.services.write"
            ]
          },
          {
            "oauth2": [
              "crm.objects.orders.write"
            ]
          },
          {
            "oauth2": [
              "crm.objects.commercepayments.read"
            ]
          },
          {
            "private_apps": [
              "crm.objects.commercepayments.read"
            ]
          },
          {
            "private_apps": [
              "crm.objects.contacts.read"
            ]
          },
          {
            "private_apps": [
              "crm.objects.deals.write"
            ]
          },
          {
            "oauth2": [
              "crm.objects.deals.write"
            ]
          },
          {
            "private_apps": [
              "crm.objects.appointments.read"
            ]
          },
          {
            "oauth2": [
              "crm.objects.invoices.read"
            ]
          },
          {
            "oauth2": [
              "crm.objects.appointments.read"
            ]
          },
          {
            "private_apps": [
              "crm.objects.invoices.read"
            ]
          },
          {
            "private_apps": [
              "crm.objects.leads.write"
            ]
          },
          {
            "oauth2": [
              "crm.objects.quotes.write"
            ]
          },
          {
            "private_apps": [
              "crm.objects.quotes.write"
            ]
          },
          {
            "oauth2": [
              "crm.objects.leads.read"
            ]
          },
          {
            "oauth2": [
              "crm.objects.leads.write"
            ]
          },
          {
            "private_apps": [
              "crm.objects.courses.write"
            ]
          },
          {
            "private_apps": [
              "crm.objects.partner-clients.write"
            ]
          },
          {
            "private_apps": [
              "crm.objects.line_items.read"
            ]
          },
          {
            "oauth2": [
              "crm.objects.contacts.write"
            ]
          },
          {
            "private_apps": [
              "crm.objects.contacts.write"
            ]
          },
          {
            "oauth2": [
              "crm.objects.partner-clients.write"
            ]
          },
          {
            "oauth2": [
              "crm.objects.line_items.read"
            ]
          },
          {
            "private_apps": [
              "crm.objects.leads.read"
            ]
          },
          {
            "oauth2_legacy": [
              "crm.objects.custom.read"
            ]
          },
          {
            "private_apps_legacy": [
              "crm.objects.custom.read"
            ]
          },
          {
            "oauth2": [
              "crm.objects.line_items.write"
            ]
          },
          {
            "private_apps": [
              "crm.objects.listings.read"
            ]
          },
          {
            "private_apps": [
              "crm.objects.line_items.write"
            ]
          },
          {
            "oauth2": [
              "crm.objects.courses.read"
            ]
          },
          {
            "private_apps": [
              "crm.objects.courses.read"
            ]
          },
          {
            "oauth2": [
              "crm.objects.listings.read"
            ]
          },
          {
            "private_apps": [
              "crm.objects.carts.read"
            ]
          },
          {
            "oauth2": [
              "crm.objects.courses.write"
            ]
          },
          {
            "oauth2": [
              "crm.objects.quotes.read"
            ]
          },
          {
            "oauth2": [
              "crm.objects.partner-clients.read"
            ]
          },
          {
            "oauth2": [
              "crm.objects.services.read"
            ]
          },
          {
            "oauth2": [
              "crm.objects.carts.read"
            ]
          },
          {
            "private_apps": [
              "crm.objects.partner-clients.read"
            ]
          },
          {
            "private_apps": [
              "crm.objects.quotes.read"
            ]
          }
        ],
        "tags": [
          "Batch"
        ],
        "operationId": "post-/crm/v3/objects/{objectType}/batch/create_create",
        "summary": "Create a batch of objects"
      }
    },
    "/crm/v3/objects/{objectType}/batch/read": {
      "post": {
        "security": [
          {
            "private_apps": [
              "crm.objects.listings.write"
            ]
          },
          {
            "private_apps": [
              "crm.objects.services.read"
            ]
          },
          {
            "oauth2": [
              "crm.objects.listings.write"
            ]
          },
          {
            "oauth2_legacy": [
              "media_bridge.read"
            ]
          },
          {
            "private_apps": [
              "crm.objects.orders.read"
            ]
          },
          {
            "private_apps": [
              "crm.objects.appointments.write"
            ]
          },
          {
            "private_apps": [
              "crm.objects.deals.read"
            ]
          },
          {
            "oauth2": [
              "crm.objects.orders.read"
            ]
          },
          {
            "private_apps": [
              "crm.objects.subscriptions.read"
            ]
          },
          {
            "oauth2": [
              "crm.objects.deals.read"
            ]
          },
          {
            "private_apps_legacy": [
              "contacts"
            ]
          },
          {
            "oauth2": [
              "crm.objects.subscriptions.read"
            ]
          },
          {
            "private_apps": [
              "crm.objects.companies.read"
            ]
          },
          {
            "oauth2": [
              "crm.objects.companies.read"
            ]
          },
          {
            "private_apps_legacy": [
              "crm.objects.goals.read"
            ]
          },
          {
            "private_apps": [
              "crm.objects.users.write"
            ]
          },
          {
            "private_apps_legacy": [
              "media_bridge.read"
            ]
          },
          {
            "private_apps": [
              "crm.objects.companies.write"
            ]
          },
          {
            "oauth2": [
              "crm.objects.companies.write"
            ]
          },
          {
            "oauth2_legacy": [
              "tickets"
            ]
          },
          {
            "private_apps": [
              "crm.objects.users.read"
            ]
          },
          {
            "private_apps_legacy": [
              "crm.objects.custom.write"
            ]
          },
          {
            "oauth2": [
              "crm.objects.users.read"
            ]
          },
          {
            "oauth2": [
              "crm.objects.users.write"
            ]
          },
          {
            "private_apps_legacy": [
              "e-commerce"
            ]
          },
          {
            "private_apps": [
              "crm.objects.carts.write"
            ]
          },
          {
            "oauth2": [
              "crm.objects.carts.write"
            ]
          },
          {
            "oauth2_legacy": [
              "e-commerce"
            ]
          },
          {
            "private_apps_legacy": [
              "tickets"
            ]
          },
          {
            "oauth2_legacy": [
              "crm.objects.goals.read"
            ]
          },
          {
            "oauth2": [
              "crm.objects.appointments.write"
            ]
          },
          {
            "oauth2_legacy": [
              "crm.objects.custom.write"
            ]
          },
          {
            "oauth2": [
              "crm.objects.contacts.read"
            ]
          },
          {
            "private_apps": [
              "crm.objects.orders.write"
            ]
          },
          {
            "private_apps": [
              "crm.objects.services.write"
            ]
          },
          {
            "oauth2": [
              "crm.objects.services.write"
            ]
          },
          {
            "oauth2": [
              "crm.objects.orders.write"
            ]
          },
          {
            "oauth2": [
              "crm.objects.commercepayments.read"
            ]
          },
          {
            "private_apps": [
              "crm.objects.commercepayments.read"
            ]
          },
          {
            "private_apps": [
              "crm.objects.contacts.read"
            ]
          },
          {
            "private_apps": [
              "crm.objects.deals.write"
            ]
          },
          {
            "oauth2": [
              "crm.objects.deals.write"
            ]
          },
          {
            "private_apps": [
              "crm.objects.appointments.read"
            ]
          },
          {
            "oauth2": [
              "crm.objects.invoices.read"
            ]
          },
          {
            "oauth2": [
              "crm.objects.appointments.read"
            ]
          },
          {
            "private_apps": [
              "crm.objects.invoices.read"
            ]
          },
          {
            "private_apps": [
              "crm.objects.leads.write"
            ]
          },
          {
            "oauth2": [
              "crm.objects.quotes.write"
            ]
          },
          {
            "private_apps": [
              "crm.objects.quotes.write"
            ]
          },
          {
            "oauth2": [
              "crm.objects.leads.read"
            ]
          },
          {
            "oauth2": [
              "crm.objects.leads.write"
            ]
          },
          {
            "private_apps": [
              "crm.objects.courses.write"
            ]
          },
          {
            "private_apps": [
              "crm.objects.partner-clients.write"
            ]
          },
          {
            "private_apps": [
              "crm.objects.line_items.read"
            ]
          },
          {
            "oauth2": [
              "crm.objects.contacts.write"
            ]
          },
          {
            "private_apps": [
              "crm.objects.contacts.write"
            ]
          },
          {
            "oauth2": [
              "crm.objects.partner-clients.write"
            ]
          },
          {
            "oauth2": [
              "crm.objects.line_items.read"
            ]
          },
          {
            "private_apps": [
              "crm.objects.leads.read"
            ]
          },
          {
            "oauth2_legacy": [
              "crm.objects.custom.read"
            ]
          },
          {
            "private_apps_legacy": [
              "crm.objects.custom.read"
            ]
          },
          {
            "oauth2": [
              "crm.objects.line_items.write"
            ]
          },
          {
            "private_apps": [
              "crm.objects.listings.read"
            ]
          },
          {
            "private_apps": [
              "crm.objects.line_items.write"
            ]
          },
          {
            "oauth2": [
              "crm.objects.courses.read"
            ]
          },
          {
            "private_apps": [
              "crm.objects.courses.read"
            ]
          },
          {
            "oauth2": [
              "crm.objects.listings.read"
            ]
          },
          {
            "private_apps": [
              "crm.objects.carts.read"
            ]
          },
          {
            "oauth2": [
              "crm.objects.courses.write"
            ]
          },
          {
            "oauth2": [
              "crm.objects.quotes.read"
            ]
          },
          {
            "oauth2": [
              "crm.objects.partner-clients.read"
            ]
          },
          {
            "oauth2": [
              "crm.objects.services.read"
            ]
          },
          {
            "oauth2": [
              "crm.objects.carts.read"
            ]
          },
          {
            "private_apps": [
              "crm.objects.partner-clients.read"
            ]
          },
          {
            "private_apps": [
              "crm.objects.quotes.read"
            ]
          }
        ],
        "tags": [
          "Batch"
        ],
        "operationId": "post-/crm/v3/objects/{objectType}/batch/read_read",
        "summary": "Read a batch of objects by internal ID, or unique property values"
      }
    },
    "/crm/v3/objects/{objectType}/batch/update": {
      "post": {
        "security": [
          {
            "private_apps": [
              "crm.objects.listings.write"
            ]
          },
          {
            "private_apps": [
              "crm.objects.services.read"
            ]
          },
          {
            "oauth2": [
              "crm.objects.listings.write"
            ]
          },
          {
            "oauth2_legacy": [
              "media_bridge.read"
            ]
          },
          {
            "private_apps": [
              "crm.objects.orders.read"
            ]
          },
          {
            "private_apps": [
              "crm.objects.appointments.write"
            ]
          },
          {
            "private_apps": [
              "crm.objects.deals.read"
            ]
          },
          {
            "oauth2": [
              "crm.objects.orders.read"
            ]
          },
          {
            "private_apps": [
              "crm.objects.subscriptions.read"
            ]
          },
          {
            "oauth2": [
              "crm.objects.deals.read"
            ]
          },
          {
            "private_apps_legacy": [
              "contacts"
            ]
          },
          {
            "oauth2": [
              "crm.objects.subscriptions.read"
            ]
          },
          {
            "private_apps": [
              "crm.objects.companies.read"
            ]
          },
          {
            "oauth2": [
              "crm.objects.companies.read"
            ]
          },
          {
            "private_apps_legacy": [
              "crm.objects.goals.read"
            ]
          },
          {
            "private_apps": [
              "crm.objects.users.write"
            ]
          },
          {
            "private_apps_legacy": [
              "media_bridge.read"
            ]
          },
          {
            "private_apps": [
              "crm.objects.companies.write"
            ]
          },
          {
            "oauth2": [
              "crm.objects.companies.write"
            ]
          },
          {
            "oauth2_legacy": [
              "tickets"
            ]
          },
          {
            "private_apps": [
              "crm.objects.users.read"
            ]
          },
          {
            "private_apps_legacy": [
              "crm.objects.custom.write"
            ]
          },
          {
            "oauth2": [
              "crm.objects.users.read"
            ]
          },
          {
            "oauth2": [
              "crm.objects.users.write"
            ]
          },
          {
            "private_apps_legacy": [
              "e-commerce"
            ]
          },
          {
            "private_apps": [
              "crm.objects.carts.write"
            ]
          },
          {
            "oauth2": [
              "crm.objects.carts.write"
            ]
          },
          {
            "oauth2_legacy": [
              "e-commerce"
            ]
          },
          {
            "private_apps_legacy": [
              "tickets"
            ]
          },
          {
            "oauth2_legacy": [
              "crm.objects.goals.read"
            ]
          },
          {
            "oauth2": [
              "crm.objects.appointments.write"
            ]
          },
          {
            "oauth2_legacy": [
              "crm.objects.custom.write"
            ]
          },
          {
            "oauth2": [
              "crm.objects.contacts.read"
            ]
          },
          {
            "private_apps": [
              "crm.objects.orders.write"
            ]
          },
          {
            "private_apps": [
              "crm.objects.services.write"
            ]
          },
          {
            "oauth2": [
              "crm.objects.services.write"
            ]
          },
          {
            "oauth2": [
              "crm.objects.orders.write"
            ]
          },
          {
            "oauth2": [
              "crm.objects.commercepayments.read"
            ]
          },
          {
            "private_apps": [
              "crm.objects.commercepayments.read"
            ]
          },
          {
            "private_apps": [
              "crm.objects.contacts.read"
            ]
          },
          {
            "private_apps": [
              "crm.objects.deals.write"
            ]
          },
          {
            "oauth2": [
              "crm.objects.deals.write"
            ]
          },
          {
            "private_apps": [
              "crm.objects.appointments.read"
            ]
          },
          {
            "oauth2": [
              "crm.objects.invoices.read"
            ]
          },
          {
            "oauth2": [
              "crm.objects.appointments.read"
            ]
          },
          {
            "private_apps": [
              "crm.objects.invoices.read"
            ]
          },
          {
            "private_apps": [
              "crm.objects.leads.write"
            ]
          },
          {
            "oauth2": [
              "crm.objects.quotes.write"
            ]
          },
          {
            "private_apps": [
              "crm.objects.quotes.write"
            ]
          },
          {
            "oauth2": [
              "crm.objects.leads.read"
            ]
          },
          {
            "oauth2": [
              "crm.objects.leads.write"
            ]
          },
          {
            "private_apps": [
              "crm.objects.courses.write"
            ]
          },
          {
            "private_apps": [
              "crm.objects.partner-clients.write"
            ]
          },
          {
            "private_apps": [
              "crm.objects.line_items.read"
            ]
          },
          {
            "oauth2": [
              "crm.objects.contacts.write"
            ]
          },
          {
            "private_apps": [
              "crm.objects.contacts.write"
            ]
          },
          {
            "oauth2": [
              "crm.objects.partner-clients.write"
            ]
          },
          {
            "oauth2": [
              "crm.objects.line_items.read"
            ]
          },
          {
            "private_apps": [
              "crm.objects.leads.read"
            ]
          },
          {
            "oauth2_legacy": [
              "crm.objects.custom.read"
            ]
          },
          {
            "private_apps_legacy": [
              "crm.objects.custom.read"
            ]
          },
          {
            "oauth2": [
              "crm.objects.line_items.write"
            ]
          },
          {
            "private_apps": [
              "crm.objects.listings.read"
            ]
          },
          {
            "private_apps": [
              "crm.objects.line_items.write"
            ]
          },
          {
            "oauth2": [
              "crm.objects.courses.read"
            ]
          },
          {
            "private_apps": [
              "crm.objects.courses.read"
            ]
          },
          {
            "oauth2": [
              "crm.objects.listings.read"
            ]
          },
          {
            "private_apps": [
              "crm.objects.carts.read"
            ]
          },
          {
            "oauth2": [
              "crm.objects.courses.write"
            ]
          },
          {
            "oauth2": [
              "crm.objects.quotes.read"
            ]
          },
          {
            "oauth2": [
              "crm.objects.partner-clients.read"
            ]
          },
          {
            "oauth2": [
              "crm.objects.services.read"
            ]
          },
          {
            "oauth2": [
              "crm.objects.carts.read"
            ]
          },
          {
            "private_apps": [
              "crm.objects.partner-clients.read"
            ]
          },
          {
            "private_apps": [
              "crm.objects.quotes.read"
            ]
          }
        ],
        "tags": [
          "Batch"
        ],
        "operationId": "post-/crm/v3/objects/{objectType}/batch/update_update",
        "summary": "Update a batch of objects"
      }
    },
    "/crm/v3/objects/{objectType}/batch/upsert": {
      "post": {
        "security": [
          {
            "private_apps": [
              "crm.objects.listings.write"
            ]
          },
          {
            "private_apps": [
              "crm.objects.services.read"
            ]
          },
          {
            "oauth2": [
              "crm.objects.listings.write"
            ]
          },
          {
            "oauth2_legacy": [
              "media_bridge.read"
            ]
          },
          {
            "private_apps": [
              "crm.objects.orders.read"
            ]
          },
          {
            "private_apps": [
              "crm.objects.appointments.write"
            ]
          },
          {
            "private_apps": [
              "crm.objects.deals.read"
            ]
          },
          {
            "oauth2": [
              "crm.objects.orders.read"
            ]
          },
          {
            "private_apps": [
              "crm.objects.subscriptions.read"
            ]
          },
          {
            "oauth2": [
              "crm.objects.deals.read"
            ]
          },
          {
            "private_apps_legacy": [
              "contacts"
            ]
          },
          {
            "oauth2": [
              "crm.objects.subscriptions.read"
            ]
          },
          {
            "private_apps": [
              "crm.objects.companies.read"
            ]
          },
          {
            "oauth2": [
              "crm.objects.companies.read"
            ]
          },
          {
            "private_apps_legacy": [
              "crm.objects.goals.read"
            ]
          },
          {
            "private_apps": [
              "crm.objects.users.write"
            ]
          },
          {
            "private_apps_legacy": [
              "media_bridge.read"
            ]
          },
          {
            "private_apps": [
              "crm.objects.companies.write"
            ]
          },
          {
            "oauth2": [
              "crm.objects.companies.write"
            ]
          },
          {
            "oauth2_legacy": [
              "tickets"
            ]
          },
          {
            "private_apps": [
              "crm.objects.users.read"
            ]
          },
          {
            "private_apps_legacy": [
              "crm.objects.custom.write"
            ]
          },
          {
            "oauth2": [
              "crm.objects.users.read"
            ]
          },
          {
            "oauth2": [
              "crm.objects.users.write"
            ]
          },
          {
            "private_apps_legacy": [
              "e-commerce"
            ]
          },
          {
            "private_apps": [
              "crm.objects.carts.write"
            ]
          },
          {
            "oauth2": [
              "crm.objects.carts.write"
            ]
          },
          {
            "oauth2_legacy": [
              "e-commerce"
            ]
          },
          {
            "private_apps_legacy": [
              "tickets"
            ]
          },
          {
            "oauth2_legacy": [
              "crm.objects.goals.read"
            ]
          },
          {
            "oauth2": [
              "crm.objects.appointments.write"
            ]
          },
          {
            "oauth2_legacy": [
              "crm.objects.custom.write"
            ]
          },
          {
            "oauth2": [
              "crm.objects.contacts.read"
            ]
          },
          {
            "private_apps": [
              "crm.objects.orders.write"
            ]
          },
          {
            "private_apps": [
              "crm.objects.services.write"
            ]
          },
          {
            "oauth2": [
              "crm.objects.services.write"
            ]
          },
          {
            "oauth2": [
              "crm.objects.orders.write"
            ]
          },
          {
            "oauth2": [
              "crm.objects.commercepayments.read"
            ]
          },
          {
            "private_apps": [
              "crm.objects.commercepayments.read"
            ]
          },
          {
            "private_apps": [
              "crm.objects.contacts.read"
            ]
          },
          {
            "private_apps": [
              "crm.objects.deals.write"
            ]
          },
          {
            "oauth2": [
              "crm.objects.deals.write"
            ]
          },
          {
            "private_apps": [
              "crm.objects.appointments.read"
            ]
          },
          {
            "oauth2": [
              "crm.objects.invoices.read"
            ]
          },
          {
            "oauth2": [
              "crm.objects.appointments.read"
            ]
          },
          {
            "private_apps": [
              "crm.objects.invoices.read"
            ]
          },
          {
            "private_apps": [
              "crm.objects.leads.write"
            ]
          },
          {
            "oauth2": [
              "crm.objects.quotes.write"
            ]
          },
          {
            "private_apps": [
              "crm.objects.quotes.write"
            ]
          },
          {
            "oauth2": [
              "crm.objects.leads.read"
            ]
          },
          {
            "oauth2": [
              "crm.objects.leads.write"
            ]
          },
          {
            "private_apps": [
              "crm.objects.courses.write"
            ]
          },
          {
            "private_apps": [
              "crm.objects.partner-clients.write"
            ]
          },
          {
            "private_apps": [
              "crm.objects.line_items.read"
            ]
          },
          {
            "oauth2": [
              "crm.objects.contacts.write"
            ]
          },
          {
            "private_apps": [
              "crm.objects.contacts.write"
            ]
          },
          {
            "oauth2": [
              "crm.objects.partner-clients.write"
            ]
          },
          {
            "oauth2": [
              "crm.objects.line_items.read"
            ]
          },
          {
            "private_apps": [
              "crm.objects.leads.read"
            ]
          },
          {
            "oauth2_legacy": [
              "crm.objects.custom.read"
            ]
          },
          {
            "private_apps_legacy": [
              "crm.objects.custom.read"
            ]
          },
          {
            "oauth2": [
              "crm.objects.line_items.write"
            ]
          },
          {
            "private_apps": [
              "crm.objects.listings.read"
            ]
          },
          {
            "private_apps": [
              "crm.objects.line_items.write"
            ]
          },
          {
            "oauth2": [
              "crm.objects.courses.read"
            ]
          },
          {
            "private_apps": [
              "crm.objects.courses.read"
            ]
          },
          {
            "oauth2": [
              "crm.objects.listings.read"
            ]
          },
          {
            "private_apps": [
              "crm.objects.carts.read"
            ]
          },
          {
            "oauth2": [
              "crm.objects.courses.write"
            ]
          },
          {
            "oauth2": [
              "crm.objects.quotes.read"
            ]
          },
          {
            "oauth2": [
              "crm.objects.partner-clients.read"
            ]
          },
          {
            "oauth2": [
              "crm.objects.services.read"
            ]
          },
          {
            "oauth2": [
              "crm.objects.carts.read"
            ]
          },
          {
            "private_apps": [
              "crm.objects.partner-clients.read"
            ]
          },
          {
            "private_apps": [
              "crm.objects.quotes.read"
            ]
          }
        ],
        "tags": [
          "Batch"
        ],
        "operationId": "post-/crm/v3/objects/{objectType}/batch/upsert",
        "summary": "Create or update a batch of objects by unique property values"
      }
    },
    "/crm/v3/objects/{objectType}/merge": {
      "post": {
        "security": [
          {
            "private_apps": [
              "crm.objects.listings.write"
            ]
          },
          {
            "private_apps": [
              "crm.objects.services.read"
            ]
          },
          {
            "oauth2": [
              "crm.objects.listings.write"
            ]
          },
          {
            "oauth2_legacy": [
              "media_bridge.read"
            ]
          },
          {
            "private_apps": [
              "crm.objects.orders.read"
            ]
          },
          {
            "private_apps": [
              "crm.objects.appointments.write"
            ]
          },
          {
            "private_apps": [
              "crm.objects.deals.read"
            ]
          },
          {
            "oauth2": [
              "crm.objects.orders.read"
            ]
          },
          {
            "private_apps": [
              "crm.objects.subscriptions.read"
            ]
          },
          {
            "oauth2": [
              "crm.objects.deals.read"
            ]
          },
          {
            "private_apps_legacy": [
              "contacts"
            ]
          },
          {
            "oauth2": [
              "crm.objects.subscriptions.read"
            ]
          },
          {
            "private_apps": [
              "crm.objects.companies.read"
            ]
          },
          {
            "oauth2": [
              "crm.objects.companies.read"
            ]
          },
          {
            "private_apps_legacy": [
              "crm.objects.goals.read"
            ]
          },
          {
            "private_apps": [
              "crm.objects.users.write"
            ]
          },
          {
            "private_apps_legacy": [
              "media_bridge.read"
            ]
          },
          {
            "private_apps": [
              "crm.objects.companies.write"
            ]
          },
          {
            "oauth2": [
              "crm.objects.companies.write"
            ]
          },
          {
            "oauth2_legacy": [
              "tickets"
            ]
          },
          {
            "private_apps": [
              "crm.objects.users.read"
            ]
          },
          {
            "private_apps_legacy": [
              "crm.objects.custom.write"
            ]
          },
          {
            "oauth2": [
              "crm.objects.users.read"
            ]
          },
          {
            "oauth2": [
              "crm.objects.users.write"
            ]
          },
          {
            "private_apps_legacy": [
              "e-commerce"
            ]
          },
          {
            "private_apps": [
              "crm.objects.carts.write"
            ]
          },
          {
            "oauth2": [
              "crm.objects.carts.write"
            ]
          },
          {
            "oauth2_legacy": [
              "e-commerce"
            ]
          },
          {
            "private_apps_legacy": [
              "tickets"
            ]
          },
          {
            "oauth2_legacy": [
              "crm.objects.goals.read"
            ]
          },
          {
            "oauth2": [
              "crm.objects.appointments.write"
            ]
          },
          {
            "oauth2_legacy": [
              "crm.objects.custom.write"
            ]
          },
          {
            "oauth2": [
              "crm.objects.contacts.read"
            ]
          },
          {
            "private_apps": [
              "crm.objects.orders.write"
            ]
          },
          {
            "private_apps": [
              "crm.objects.services.write"
            ]
          },
          {
            "oauth2": [
              "crm.objects.services.write"
            ]
          },
          {
            "oauth2": [
              "crm.objects.orders.write"
            ]
          },
          {
            "oauth2": [
              "crm.objects.commercepayments.read"
            ]
          },
          {
            "private_apps": [
              "crm.objects.commercepayments.read"
            ]
          },
          {
            "private_apps": [
              "crm.objects.contacts.read"
            ]
          },
          {
            "private_apps": [
              "crm.objects.deals.write"
            ]
          },
          {
            "oauth2": [
              "crm.objects.deals.write"
            ]
          },
          {
            "private_apps": [
              "crm.objects.appointments.read"
            ]
          },
          {
            "oauth2": [
              "crm.objects.invoices.read"
            ]
          },
          {
            "oauth2": [
              "crm.objects.appointments.read"
            ]
          },
          {
            "private_apps": [
              "crm.objects.invoices.read"
            ]
          },
          {
            "private_apps": [
              "crm.objects.leads.write"
            ]
          },
          {
            "oauth2": [
              "crm.objects.quotes.write"
            ]
          },
          {
            "private_apps": [
              "crm.objects.quotes.write"
            ]
          },
          {
            "oauth2": [
              "crm.objects.leads.read"
            ]
          },
          {
            "oauth2": [
              "crm.objects.leads.write"
            ]
          },
          {
            "private_apps": [
              "crm.objects.courses.write"
            ]
          },
          {
            "private_apps": [
              "crm.objects.partner-clients.write"
            ]
          },
          {
            "private_apps": [
              "crm.objects.line_items.read"
            ]
          },
          {
            "oauth2": [
              "crm.objects.contacts.write"
            ]
          },
          {
            "private_apps": [
              "crm.objects.contacts.write"
            ]
          },
          {
            "oauth2": [
              "crm.objects.partner-clients.write"
            ]
          },
          {
            "oauth2": [
              "crm.objects.line_items.read"
            ]
          },
          {
            "private_apps": [
              "crm.objects.leads.read"
            ]
          },
          {
            "oauth2_legacy": [
              "crm.objects.custom.read"
            ]
          },
          {
            "private_apps_legacy": [
              "crm.objects.custom.read"
            ]
          },
          {
            "oauth2": [
              "crm.objects.line_items.write"
            ]
          },
          {
            "private_apps": [
              "crm.objects.listings.read"
            ]
          },
          {
            "private_apps": [
              "crm.objects.line_items.write"
            ]
          },
          {
            "oauth2": [
              "crm.objects.courses.read"
            ]
          },
          {
            "private_apps": [
              "crm.objects.courses.read"
            ]
          },
          {
            "oauth2": [
              "crm.objects.listings.read"
            ]
          },
          {
            "private_apps": [
              "crm.objects.carts.read"
            ]
          },
          {
            "oauth2": [
              "crm.objects.courses.write"
            ]
          },
          {
            "oauth2": [
              "crm.objects.quotes.read"
            ]
          },
          {
            "oauth2": [
              "crm.objects.partner-clients.read"
            ]
          },
          {
            "oauth2": [
              "crm.objects.services.read"
            ]
          },
          {
            "oauth2": [
              "crm.objects.carts.read"
            ]
          },
          {
            "private_apps": [
              "crm.objects.partner-clients.read"
            ]
          },
          {
            "private_apps": [
              "crm.objects.quotes.read"
            ]
          }
        ],
        "tags": [
          "Basic"
        ],
        "operationId": "post-/crm/v3/objects/{objectType}/merge_merge",
        "summary": "Merge two objects with same type"
      }
    },
    "/crm/v3/objects/{objectType}/search": {
      "post": {
        "security": [
          {
            "private_apps": [
              "crm.objects.listings.write"
            ]
          },
          {
            "private_apps": [
              "crm.objects.services.read"
            ]
          },
          {
            "oauth2": [
              "crm.objects.listings.write"
            ]
          },
          {
            "oauth2_legacy": [
              "media_bridge.read"
            ]
          },
          {
            "private_apps": [
              "crm.objects.orders.read"
            ]
          },
          {
            "private_apps": [
              "crm.objects.appointments.write"
            ]
          },
          {
            "private_apps": [
              "crm.objects.deals.read"
            ]
          },
          {
            "oauth2": [
              "crm.objects.orders.read"
            ]
          },
          {
            "private_apps": [
              "crm.objects.subscriptions.read"
            ]
          },
          {
            "oauth2": [
              "crm.objects.deals.read"
            ]
          },
          {
            "private_apps_legacy": [
              "contacts"
            ]
          },
          {
            "oauth2": [
              "crm.objects.subscriptions.read"
            ]
          },
          {
            "private_apps": [
              "crm.objects.companies.read"
            ]
          },
          {
            "oauth2": [
              "crm.objects.companies.read"
            ]
          },
          {
            "private_apps_legacy": [
              "crm.objects.goals.read"
            ]
          },
          {
            "private_apps": [
              "crm.objects.users.write"
            ]
          },
          {
            "private_apps_legacy": [
              "media_bridge.read"
            ]
          },
          {
            "private_apps": [
              "crm.objects.companies.write"
            ]
          },
          {
            "oauth2": [
              "crm.objects.companies.write"
            ]
          },
          {
            "oauth2_legacy": [
              "tickets"
            ]
          },
          {
            "private_apps": [
              "crm.objects.users.read"
            ]
          },
          {
            "private_apps_legacy": [
              "crm.objects.custom.write"
            ]
          },
          {
            "oauth2": [
              "crm.objects.users.read"
            ]
          },
          {
            "oauth2": [
              "crm.objects.users.write"
            ]
          },
          {
            "private_apps_legacy": [
              "e-commerce"
            ]
          },
          {
            "private_apps": [
              "crm.objects.carts.write"
            ]
          },
          {
            "oauth2": [
              "crm.objects.carts.write"
            ]
          },
          {
            "oauth2_legacy": [
              "e-commerce"
            ]
          },
          {
            "private_apps_legacy": [
              "tickets"
            ]
          },
          {
            "oauth2_legacy": [
              "crm.objects.goals.read"
            ]
          },
          {
            "oauth2": [
              "crm.objects.appointments.write"
            ]
          },
          {
            "oauth2_legacy": [
              "crm.objects.custom.write"
            ]
          },
          {
            "oauth2": [
              "crm.objects.contacts.read"
            ]
          },
          {
            "private_apps": [
              "crm.objects.orders.write"
            ]
          },
          {
            "private_apps": [
              "crm.objects.services.write"
            ]
          },
          {
            "oauth2": [
              "crm.objects.services.write"
            ]
          },
          {
            "oauth2": [
              "crm.objects.orders.write"
            ]
          },
          {
            "oauth2": [
              "crm.objects.commercepayments.read"
            ]
          },
          {
            "private_apps": [
              "crm.objects.commercepayments.read"
            ]
          },
          {
            "private_apps": [
              "crm.objects.contacts.read"
            ]
          },
          {
            "private_apps": [
              "crm.objects.deals.write"
            ]
          },
          {
            "oauth2": [
              "crm.objects.deals.write"
            ]
          },
          {
            "private_apps": [
              "crm.objects.appointments.read"
            ]
          },
          {
            "oauth2": [
              "crm.objects.invoices.read"
            ]
          },
          {
            "oauth2": [
              "crm.objects.appointments.read"
            ]
          },
          {
            "private_apps": [
              "crm.objects.invoices.read"
            ]
          },
          {
            "private_apps": [
              "crm.objects.leads.write"
            ]
          },
          {
            "oauth2": [
              "crm.objects.quotes.write"
            ]
          },
          {
            "private_apps": [
              "crm.objects.quotes.write"
            ]
          },
          {
            "oauth2": [
              "crm.objects.leads.read"
            ]
          },
          {
            "oauth2": [
              "crm.objects.leads.write"
            ]
          },
          {
            "private_apps": [
              "crm.objects.courses.write"
            ]
          },
          {
            "private_apps": [
              "crm.objects.partner-clients.write"
            ]
          },
          {
            "private_apps": [
              "crm.objects.line_items.read"
            ]
          },
          {
            "oauth2": [
              "crm.objects.contacts.write"
            ]
          },
          {
            "private_apps": [
              "crm.objects.contacts.write"
            ]
          },
          {
            "oauth2": [
              "crm.objects.partner-clients.write"
            ]
          },
          {
            "oauth2": [
              "crm.objects.line_items.read"
            ]
          },
          {
            "private_apps": [
              "crm.objects.leads.read"
            ]
          },
          {
            "oauth2_legacy": [
              "crm.objects.custom.read"
            ]
          },
          {
            "private_apps_legacy": [
              "crm.objects.custom.read"
            ]
          },
          {
            "oauth2": [
              "crm.objects.line_items.write"
            ]
          },
          {
            "private_apps": [
              "crm.objects.listings.read"
            ]
          },
          {
            "private_apps": [
              "crm.objects.line_items.write"
            ]
          },
          {
            "oauth2": [
              "crm.objects.courses.read"
            ]
          },
          {
            "private_apps": [
              "crm.objects.courses.read"
            ]
          },
          {
            "oauth2": [
              "crm.objects.listings.read"
            ]
          },
          {
            "private_apps": [
              "crm.objects.carts.read"
            ]
          },
          {
            "oauth2": [
              "crm.objects.courses.write"
            ]
          },
          {
            "oauth2": [
              "crm.objects.quotes.read"
            ]
          },
          {
            "oauth2": [
              "crm.objects.partner-clients.read"
            ]
          },
          {
            "oauth2": [
              "crm.objects.services.read"
            ]
          },
          {
            "oauth2": [
              "crm.objects.carts.read"
            ]
          },
          {
            "private_apps": [
              "crm.objects.partner-clients.read"
            ]
          },
          {
            "private_apps": [
              "crm.objects.quotes.read"
            ]
          }
        ],
        "tags": [
          "Search"
        ],
        "operationId": "post-/crm/v3/objects/{objectType}/search_doSearch",
        "x-hubspot-rate-limit-exemptions": [
          "ten-secondly"
        ]
      }
    },
    "/crm/v3/objects/{objectType}/{objectId}": {
      "delete": {
        "security": [
          {
            "private_apps": [
              "crm.objects.listings.write"
            ]
          },
          {
            "private_apps": [
              "crm.objects.services.read"
            ]
          },
          {
            "oauth2": [
              "crm.objects.listings.write"
            ]
          },
          {
            "oauth2_legacy": [
              "media_bridge.read"
            ]
          },
          {
            "private_apps": [
              "crm.objects.orders.read"
            ]
          },
          {
            "private_apps": [
              "crm.objects.appointments.write"
            ]
          },
          {
            "private_apps": [
              "crm.objects.deals.read"
            ]
          },
          {
            "oauth2": [
              "crm.objects.orders.read"
            ]
          },
          {
            "private_apps": [
              "crm.objects.subscriptions.read"
            ]
          },
          {
            "oauth2": [
              "crm.objects.deals.read"
            ]
          },
          {
            "private_apps_legacy": [
              "contacts"
            ]
          },
          {
            "oauth2": [
              "crm.objects.subscriptions.read"
            ]
          },
          {
            "private_apps": [
              "crm.objects.companies.read"
            ]
          },
          {
            "oauth2": [
              "crm.objects.companies.read"
            ]
          },
          {
            "private_apps_legacy": [
              "crm.objects.goals.read"
            ]
          },
          {
            "private_apps": [
              "crm.objects.users.write"
            ]
          },
          {
            "private_apps_legacy": [
              "media_bridge.read"
            ]
          },
          {
            "private_apps": [
              "crm.objects.companies.write"
            ]
          },
          {
            "oauth2": [
              "crm.objects.companies.write"
            ]
          },
          {
            "oauth2_legacy": [
              "tickets"
            ]
          },
          {
            "private_apps": [
              "crm.objects.users.read"
            ]
          },
          {
            "private_apps_legacy": [
              "crm.objects.custom.write"
            ]
          },
          {
            "oauth2": [
              "crm.objects.users.read"
            ]
          },
          {
            "oauth2": [
              "crm.objects.users.write"
            ]
          },
          {
            "private_apps_legacy": [
              "e-commerce"
            ]
          },
          {
            "private_apps": [
              "crm.objects.carts.write"
            ]
          },
          {
            "oauth2": [
              "crm.objects.carts.write"
            ]
          },
          {
            "oauth2_legacy": [
              "e-commerce"
            ]
          },
          {
            "private_apps_legacy": [
              "tickets"
            ]
          },
          {
            "oauth2_legacy": [
              "crm.objects.goals.read"
            ]
          },
          {
            "oauth2": [
              "crm.objects.appointments.write"
            ]
          },
          {
            "oauth2_legacy": [
              "crm.objects.custom.write"
            ]
          },
          {
            "oauth2": [
              "crm.objects.contacts.read"
            ]
          },
          {
            "private_apps": [
              "crm.objects.orders.write"
            ]
          },
          {
            "private_apps": [
              "crm.objects.services.write"
            ]
          },
          {
            "oauth2": [
              "crm.objects.services.write"
            ]
          },
          {
            "oauth2": [
              "crm.objects.orders.write"
            ]
          },
          {
            "oauth2": [
              "crm.objects.commercepayments.read"
            ]
          },
          {
            "private_apps": [
              "crm.objects.commercepayments.read"
            ]
          },
          {
            "private_apps": [
              "crm.objects.contacts.read"
            ]
          },
          {
            "private_apps": [
              "crm.objects.deals.write"
            ]
          },
          {
            "oauth2": [
              "crm.objects.deals.write"
            ]
          },
          {
            "private_apps": [
              "crm.objects.appointments.read"
            ]
          },
          {
            "oauth2": [
              "crm.objects.invoices.read"
            ]
          },
          {
            "oauth2": [
              "crm.objects.appointments.read"
            ]
          },
          {
            "private_apps": [
              "crm.objects.invoices.read"
            ]
          },
          {
            "private_apps": [
              "crm.objects.leads.write"
            ]
          },
          {
            "oauth2": [
              "crm.objects.quotes.write"
            ]
          },
          {
            "private_apps": [
              "crm.objects.quotes.write"
            ]
          },
          {
            "oauth2": [
              "crm.objects.leads.read"
            ]
          },
          {
            "oauth2": [
              "crm.objects.leads.write"
            ]
          },
          {
            "private_apps": [
              "crm.objects.courses.write"
            ]
          },
          {
            "private_apps": [
              "crm.objects.partner-clients.write"
            ]
          },
          {
            "private_apps": [
              "crm.objects.line_items.read"
            ]
          },
          {
            "oauth2": [
              "crm.objects.contacts.write"
            ]
          },
          {
            "private_apps": [
              "crm.objects.contacts.write"
            ]
          },
          {
            "oauth2": [
              "crm.objects.partner-clients.write"
            ]
          },
          {
            "oauth2": [
              "crm.objects.line_items.read"
            ]
          },
          {
            "private_apps": [
              "crm.objects.leads.read"
            ]
          },
          {
            "oauth2_legacy": [
              "crm.objects.custom.read"
            ]
          },
          {
            "private_apps_legacy": [
              "crm.objects.custom.read"
            ]
          },
          {
            "oauth2": [
              "crm.objects.line_items.write"
            ]
          },
          {
            "private_apps": [
              "crm.objects.listings.read"
            ]
          },
          {
            "private_apps": [
              "crm.objects.line_items.write"
            ]
          },
          {
            "oauth2": [
              "crm.objects.courses.read"
            ]
          },
          {
            "private_apps": [
              "crm.objects.courses.read"
            ]
          },
          {
            "oauth2": [
              "crm.objects.listings.read"
            ]
          },
          {
            "private_apps": [
              "crm.objects.carts.read"
            ]
          },
          {
            "oauth2": [
              "crm.objects.courses.write"
            ]
          },
          {
            "oauth2": [
              "crm.objects.quotes.read"
            ]
          },
          {
            "oauth2": [
              "crm.objects.partner-clients.read"
            ]
          },
          {
            "oauth2": [
              "crm.objects.services.read"
            ]
          },
          {
            "oauth2": [
              "crm.objects.carts.read"
            ]
          },
          {
            "private_apps": [
              "crm.objects.partner-clients.read"
            ]
          },
          {
            "private_apps": [
              "crm.objects.quotes.read"
            ]
          }
        ],
        "tags": [
          "Basic"
        ],
        "description": "Move an Object identified by `{objectId}` to the recycling bin.",
        "operationId": "delete-/crm/v3/objects/{objectType}/{objectId}_archive",
        "summary": "Archive"
      },
      "get": {
        "security": [
          {
            "private_apps": [
              "crm.objects.listings.write"
            ]
          },
          {
            "private_apps": [
              "crm.objects.services.read"
            ]
          },
          {
            "oauth2": [
              "crm.objects.listings.write"
            ]
          },
          {
            "oauth2_legacy": [
              "media_bridge.read"
            ]
          },
          {
            "private_apps": [
              "crm.objects.orders.read"
            ]
          },
          {
            "private_apps": [
              "crm.objects.appointments.write"
            ]
          },
          {
            "private_apps": [
              "crm.objects.deals.read"
            ]
          },
          {
            "oauth2": [
              "crm.objects.orders.read"
            ]
          },
          {
            "private_apps": [
              "crm.objects.subscriptions.read"
            ]
          },
          {
            "oauth2": [
              "crm.objects.deals.read"
            ]
          },
          {
            "private_apps_legacy": [
              "contacts"
            ]
          },
          {
            "oauth2": [
              "crm.objects.subscriptions.read"
            ]
          },
          {
            "private_apps": [
              "crm.objects.companies.read"
            ]
          },
          {
            "oauth2": [
              "crm.objects.companies.read"
            ]
          },
          {
            "private_apps_legacy": [
              "crm.objects.goals.read"
            ]
          },
          {
            "private_apps": [
              "crm.objects.users.write"
            ]
          },
          {
            "private_apps_legacy": [
              "media_bridge.read"
            ]
          },
          {
            "private_apps": [
              "crm.objects.companies.write"
            ]
          },
          {
            "oauth2": [
              "crm.objects.companies.write"
            ]
          },
          {
            "oauth2_legacy": [
              "tickets"
            ]
          },
          {
            "private_apps": [
              "crm.objects.users.read"
            ]
          },
          {
            "private_apps_legacy": [
              "crm.objects.custom.write"
            ]
          },
          {
            "oauth2": [
              "crm.objects.users.read"
            ]
          },
          {
            "oauth2": [
              "crm.objects.users.write"
            ]
          },
          {
            "private_apps_legacy": [
              "e-commerce"
            ]
          },
          {
            "private_apps": [
              "crm.objects.carts.write"
            ]
          },
          {
            "oauth2": [
              "crm.objects.carts.write"
            ]
          },
          {
            "oauth2_legacy": [
              "e-commerce"
            ]
          },
          {
            "private_apps_legacy": [
              "tickets"
            ]
          },
          {
            "oauth2_legacy": [
              "crm.objects.goals.read"
            ]
          },
          {
            "oauth2": [
              "crm.objects.appointments.write"
            ]
          },
          {
            "oauth2_legacy": [
              "crm.objects.custom.write"
            ]
          },
          {
            "oauth2": [
              "crm.objects.contacts.read"
            ]
          },
          {
            "private_apps": [
              "crm.objects.orders.write"
            ]
          },
          {
            "private_apps": [
              "crm.objects.services.write"
            ]
          },
          {
            "oauth2": [
              "crm.objects.services.write"
            ]
          },
          {
            "oauth2": [
              "crm.objects.orders.write"
            ]
          },
          {
            "oauth2": [
              "crm.objects.commercepayments.read"
            ]
          },
          {
            "private_apps": [
              "crm.objects.commercepayments.read"
            ]
          },
          {
            "private_apps": [
              "crm.objects.contacts.read"
            ]
          },
          {
            "private_apps": [
              "crm.objects.deals.write"
            ]
          },
          {
            "oauth2": [
              "crm.objects.deals.write"
            ]
          },
          {
            "private_apps": [
              "crm.objects.appointments.read"
            ]
          },
          {
            "oauth2": [
              "crm.objects.invoices.read"
            ]
          },
          {
            "oauth2": [
              "crm.objects.appointments.read"
            ]
          },
          {
            "private_apps": [
              "crm.objects.invoices.read"
            ]
          },
          {
            "private_apps": [
              "crm.objects.leads.write"
            ]
          },
          {
            "oauth2": [
              "crm.objects.quotes.write"
            ]
          },
          {
            "private_apps": [
              "crm.objects.quotes.write"
            ]
          },
          {
            "oauth2": [
              "crm.objects.leads.read"
            ]
          },
          {
            "oauth2": [
              "crm.objects.leads.write"
            ]
          },
          {
            "private_apps": [
              "crm.objects.courses.write"
            ]
          },
          {
            "private_apps": [
              "crm.objects.partner-clients.write"
            ]
          },
          {
            "private_apps": [
              "crm.objects.line_items.read"
            ]
          },
          {
            "oauth2": [
              "crm.objects.contacts.write"
            ]
          },
          {
            "private_apps": [
              "crm.objects.contacts.write"
            ]
          },
          {
            "oauth2": [
              "crm.objects.partner-clients.write"
            ]
          },
          {
            "oauth2": [
              "crm.objects.line_items.read"
            ]
          },
          {
            "private_apps": [
              "crm.objects.leads.read"
            ]
          },
          {
            "oauth2_legacy": [
              "crm.objects.custom.read"
            ]
          },
          {
            "private_apps_legacy": [
              "crm.objects.custom.read"
            ]
          },
          {
            "oauth2": [
              "crm.objects.line_items.write"
            ]
          },
          {
            "private_apps": [
              "crm.objects.listings.read"
            ]
          },
          {
            "private_apps": [
              "crm.objects.line_items.write"
            ]
          },
          {
            "oauth2": [
              "crm.objects.courses.read"
            ]
          },
          {
            "private_apps": [
              "crm.objects.courses.read"
            ]
          },
          {
            "oauth2": [
              "crm.objects.listings.read"
            ]
          },
          {
            "private_apps": [
              "crm.objects.carts.read"
            ]
          },
          {
            "oauth2": [
              "crm.objects.courses.write"
            ]
          },
          {
            "oauth2": [
              "crm.objects.quotes.read"
            ]
          },
          {
            "oauth2": [
              "crm.objects.partner-clients.read"
            ]
          },
          {
            "oauth2": [
              "crm.objects.services.read"
            ]
          },
          {
            "oauth2": [
              "crm.objects.carts.read"
            ]
          },
          {
            "private_apps": [
              "crm.objects.partner-clients.read"
            ]
          },
          {
            "private_apps": [
              "crm.objects.quotes.read"
            ]
          }
        ],
        "tags": [
          "Basic"
        ],
        "description": "Read an Object identified by `{objectId}`. `{objectId}` refers to the internal object ID by default, or optionally any unique property value as specified by the `idProperty` query param.  Control what is returned via the `properties` query param.",
        "operationId": "get-/crm/v3/objects/{objectType}/{objectId}_getById",
        "summary": "Read"
      },
      "patch": {
        "security": [
          {
            "private_apps": [
              "crm.objects.listings.write"
            ]
          },
          {
            "private_apps": [
              "crm.objects.services.read"
            ]
          },
          {
            "oauth2": [
              "crm.objects.listings.write"
            ]
          },
          {
            "oauth2_legacy": [
              "media_bridge.read"
            ]
          },
          {
            "private_apps": [
              "crm.objects.orders.read"
            ]
          },
          {
            "private_apps": [
              "crm.objects.appointments.write"
            ]
          },
          {
            "private_apps": [
              "crm.objects.deals.read"
            ]
          },
          {
            "oauth2": [
              "crm.objects.orders.read"
            ]
          },
          {
            "private_apps": [
              "crm.objects.subscriptions.read"
            ]
          },
          {
            "oauth2": [
              "crm.objects.deals.read"
            ]
          },
          {
            "private_apps_legacy": [
              "contacts"
            ]
          },
          {
            "oauth2": [
              "crm.objects.subscriptions.read"
            ]
          },
          {
            "private_apps": [
              "crm.objects.companies.read"
            ]
          },
          {
            "oauth2": [
              "crm.objects.companies.read"
            ]
          },
          {
            "private_apps_legacy": [
              "crm.objects.goals.read"
            ]
          },
          {
            "private_apps": [
              "crm.objects.users.write"
            ]
          },
          {
            "private_apps_legacy": [
              "media_bridge.read"
            ]
          },
          {
            "private_apps": [
              "crm.objects.companies.write"
            ]
          },
          {
            "oauth2": [
              "crm.objects.companies.write"
            ]
          },
          {
            "oauth2_legacy": [
              "tickets"
            ]
          },
          {
            "private_apps": [
              "crm.objects.users.read"
            ]
          },
          {
            "private_apps_legacy": [
              "crm.objects.custom.write"
            ]
          },
          {
            "oauth2": [
              "crm.objects.users.read"
            ]
          },
          {
            "oauth2": [
              "crm.objects.users.write"
            ]
          },
          {
            "private_apps_legacy": [
              "e-commerce"
            ]
          },
          {
            "private_apps": [
              "crm.objects.carts.write"
            ]
          },
          {
            "oauth2": [
              "crm.objects.carts.write"
            ]
          },
          {
            "oauth2_legacy": [
              "e-commerce"
            ]
          },
          {
            "private_apps_legacy": [
              "tickets"
            ]
          },
          {
            "oauth2_legacy": [
              "crm.objects.goals.read"
            ]
          },
          {
            "oauth2": [
              "crm.objects.appointments.write"
            ]
          },
          {
            "oauth2_legacy": [
              "crm.objects.custom.write"
            ]
          },
          {
            "oauth2": [
              "crm.objects.contacts.read"
            ]
          },
          {
            "private_apps": [
              "crm.objects.orders.write"
            ]
          },
          {
            "private_apps": [
              "crm.objects.services.write"
            ]
          },
          {
            "oauth2": [
              "crm.objects.services.write"
            ]
          },
          {
            "oauth2": [
              "crm.objects.orders.write"
            ]
          },
          {
            "oauth2": [
              "crm.objects.commercepayments.read"
            ]
          },
          {
            "private_apps": [
              "crm.objects.commercepayments.read"
            ]
          },
          {
            "private_apps": [
              "crm.objects.contacts.read"
            ]
          },
          {
            "private_apps": [
              "crm.objects.deals.write"
            ]
          },
          {
            "oauth2": [
              "crm.objects.deals.write"
            ]
          },
          {
            "private_apps": [
              "crm.objects.appointments.read"
            ]
          },
          {
            "oauth2": [
              "crm.objects.invoices.read"
            ]
          },
          {
            "oauth2": [
              "crm.objects.appointments.read"
            ]
          },
          {
            "private_apps": [
              "crm.objects.invoices.read"
            ]
          },
          {
            "private_apps": [
              "crm.objects.leads.write"
            ]
          },
          {
            "oauth2": [
              "crm.objects.quotes.write"
            ]
          },
          {
            "private_apps": [
              "crm.objects.quotes.write"
            ]
          },
          {
            "oauth2": [
              "crm.objects.leads.read"
            ]
          },
          {
            "oauth2": [
              "crm.objects.leads.write"
            ]
          },
          {
            "private_apps": [
              "crm.objects.courses.write"
            ]
          },
          {
            "private_apps": [
              "crm.objects.partner-clients.write"
            ]
          },
          {
            "private_apps": [
              "crm.objects.line_items.read"
            ]
          },
          {
            "oauth2": [
              "crm.objects.contacts.write"
            ]
          },
          {
            "private_apps": [
              "crm.objects.contacts.write"
            ]
          },
          {
            "oauth2": [
              "crm.objects.partner-clients.write"
            ]
          },
          {
            "oauth2": [
              "crm.objects.line_items.read"
            ]
          },
          {
            "private_apps": [
              "crm.objects.leads.read"
            ]
          },
          {
            "oauth2_legacy": [
              "crm.objects.custom.read"
            ]
          },
          {
            "private_apps_legacy": [
              "crm.objects.custom.read"
            ]
          },
          {
            "oauth2": [
              "crm.objects.line_items.write"
            ]
          },
          {
            "private_apps": [
              "crm.objects.listings.read"
            ]
          },
          {
            "private_apps": [
              "crm.objects.line_items.write"
            ]
          },
          {
            "oauth2": [
              "crm.objects.courses.read"
            ]
          },
          {
            "private_apps": [
              "crm.objects.courses.read"
            ]
          },
          {
            "oauth2": [
              "crm.objects.listings.read"
            ]
          },
          {
            "private_apps": [
              "crm.objects.carts.read"
            ]
          },
          {
            "oauth2": [
              "crm.objects.courses.write"
            ]
          },
          {
            "oauth2": [
              "crm.objects.quotes.read"
            ]
          },
          {
            "oauth2": [
              "crm.objects.partner-clients.read"
            ]
          },
          {
            "oauth2": [
              "crm.objects.services.read"
            ]
          },
          {
            "oauth2": [
              "crm.objects.carts.read"
            ]
          },
          {
            "private_apps": [
              "crm.objects.partner-clients.read"
            ]
          },
          {
            "private_apps": [
              "crm.objects.quotes.read"
            ]
          }
        ],
        "tags": [
          "Basic"
        ],
        "description": "Perform a partial update of an Object identified by `{objectId}`. `{objectId}` refers to the internal object ID by default, or optionally any unique property value as specified by the `idProperty` query param. Provided property values will be overwritten. Read-only and non-existent properties will be ignored. Properties values can be cleared by passing an empty string.",
        "operationId": "patch-/crm/v3/objects/{objectType}/{objectId}_update",
        "summary": "Update"
      }
    }
  },
  "securityDefinitions": {
    "oauth2": {
      "authorizationUrl": "https://app.hubspot.com/oauth/authorize",
      "flow": "accessCode",
      "scopes": {
        "crm.objects.appointments.read": "Read appointments",
        "crm.objects.appointments.write": "Write appointments",
        "crm.objects.carts.read": "Read carts",
        "crm.objects.carts.write": "Write cart",
        "crm.objects.commercepayments.read": "Read the COMMERCE_PAYMENT object.",
        "crm.objects.companies.read": " ",
        "crm.objects.companies.write": " ",
        "crm.objects.contacts.read": " ",
        "crm.objects.contacts.write": " ",
        "crm.objects.courses.read": "Read courses",
        "crm.objects.courses.write": "Write courses",
        "crm.objects.deals.read": " ",
        "crm.objects.deals.write": " ",
        "crm.objects.invoices.read": "Read invoices objects",
        "crm.objects.leads.read": "Read lead objects",
        "crm.objects.leads.write": "Modify lead objects",
        "crm.objects.line_items.read": "Line Items",
        "crm.objects.line_items.write": "Line Items",
        "crm.objects.listings.read": "Read listings",
        "crm.objects.listings.write": "Write listings",
        "crm.objects.orders.read": "Read Orders",
        "crm.objects.orders.write": "Write orders",
        "crm.objects.partner-clients.read": "View Partner Client CRM objects",
        "crm.objects.partner-clients.write": "Modify Partner Client CRM objects",
        "crm.objects.quotes.read": "Quotes",
        "crm.objects.quotes.write": "Quotes",
        "crm.objects.services.read": "Read services",
        "crm.objects.services.write": "Write services",
        "crm.objects.subscriptions.read": "Read Commerce Subscriptions",
        "crm.objects.users.read": "Read User CRM objects",
        "crm.objects.users.write": "Write User CRM objects"
      },
      "tokenUrl": "https://api.hubapi.com/oauth/v1/token",
      "type": "oauth2"
    },
    "oauth2_legacy": {
      "authorizationUrl": "https://app.hubspot.com/oauth/authorize",
      "flow": "accessCode",
      "scopes": {
        "crm.objects.custom.read": "View custom object records",
        "crm.objects.custom.write": "Change custom object records",
        "crm.objects.goals.read": "Read goals",
        "e-commerce": "e-commerce",
        "media_bridge.read": "Read media and media events",
        "tickets": "Read and write tickets"
      },
      "tokenUrl": "https://api.hubapi.com/oauth/v1/token",
      "type": "oauth2"
    },
    "private_apps": {
      "in": "header",
      "name": "private-app",
      "type": "apiKey"
    },
    "private_apps_legacy": {
      "in": "header",
      "name": "private-app-legacy",
      "type": "apiKey"
    }
  },
  "tags": [
    {
      "name": "Batch"
    },
    {
      "name": "Basic"
    },
    {
      "name": "Search"
    }
  ],
  "x-components": {
  },
  "x-hubspot-available-client-libraries": [
    "PHP",
    "Node",
    "Ruby",
    "Python"
  ],
  "x-hubspot-documentation-banner": "NONE",
  "x-hubspot-product-tier-requirements": {
    "cms": "FREE",
    "marketing": "FREE",
    "sales": "FREE",
    "service": "FREE"
  }
}
