{
  "swagger": "2.0",
  "info": {
    "description": "",
    "title": "Leads",
    "version": "v3",
    "x-hubspot-api-use-case": "When an existing contact shows an interest in purchasing a product or service, create a lead record to track the sales prospecting journey.",
    "x-hubspot-documentation-banner": "NONE",
    "x-hubspot-introduction": "In HubSpot, leads are contacts or companies that are potential customers who have shown interest in your products or services. Use the leads API to create and manage lead records in your HubSpot account, as well as sync lead data between HubSpot and other systems.",
    "x-hubspot-product-tier-requirements": {
      "cms": "FREE",
      "marketing": "FREE",
      "sales": "PROFESSIONAL",
      "service": "FREE"
    },
    "x-hubspot-related-documentation": [
      {
        "name": "Leads Guide",
        "url": "https://developers.hubspot.com/docs/guides/api/crm/objects/leads"
      }
    ]
  },
  "host": "api.hubapi.com",
  "basePath": "/",
  "schemes": [
    "https"
  ],
  "paths": {
    "/crm/v3/objects/leads": {
      "get": {
        "security": [
          {
            "oauth2": [
              "crm.objects.leads.read"
            ]
          },
          {
            "private_apps": [
              "crm.objects.leads.read"
            ]
          }
        ],
        "tags": [
          "Basic"
        ],
        "description": "Read a page of leads. Control what is returned via the `properties` query param.",
        "operationId": "get-/crm/v3/objects/leads_getPage",
        "summary": "List"
      },
      "post": {
        "security": [
          {
            "oauth2": [
              "crm.objects.leads.write"
            ]
          },
          {
            "private_apps": [
              "crm.objects.leads.write"
            ]
          }
        ],
        "tags": [
          "Basic"
        ],
        "description": "Create a lead with the given properties and return a copy of the object, including the ID. Documentation and examples for creating standard leads is provided.",
        "operationId": "post-/crm/v3/objects/leads_create",
        "summary": "Create"
      }
    },
    "/crm/v3/objects/leads/batch/archive": {
      "post": {
        "security": [
          {
            "oauth2": [
              "crm.objects.leads.write"
            ]
          },
          {
            "private_apps": [
              "crm.objects.leads.write"
            ]
          }
        ],
        "tags": [
          "Batch"
        ],
        "operationId": "post-/crm/v3/objects/leads/batch/archive_archive",
        "summary": "Archive a batch of leads by ID"
      }
    },
    "/crm/v3/objects/leads/batch/create": {
      "post": {
        "security": [
          {
            "oauth2": [
              "crm.objects.leads.write"
            ]
          },
          {
            "private_apps": [
              "crm.objects.leads.write"
            ]
          }
        ],
        "tags": [
          "Batch"
        ],
        "operationId": "post-/crm/v3/objects/leads/batch/create_create",
        "summary": "Create a batch of leads"
      }
    },
    "/crm/v3/objects/leads/batch/read": {
      "post": {
        "security": [
          {
            "oauth2": [
              "crm.objects.leads.read"
            ]
          },
          {
            "private_apps": [
              "crm.objects.leads.read"
            ]
          }
        ],
        "tags": [
          "Batch"
        ],
        "operationId": "post-/crm/v3/objects/leads/batch/read_read",
        "summary": "Read a batch of leads by internal ID, or unique property values"
      }
    },
    "/crm/v3/objects/leads/batch/update": {
      "post": {
        "security": [
          {
            "oauth2": [
              "crm.objects.leads.write"
            ]
          },
          {
            "private_apps": [
              "crm.objects.leads.write"
            ]
          }
        ],
        "tags": [
          "Batch"
        ],
        "operationId": "post-/crm/v3/objects/leads/batch/update_update",
        "summary": "Update a batch of leads by internal ID, or unique property values"
      }
    },
    "/crm/v3/objects/leads/batch/upsert": {
      "post": {
        "security": [
          {
            "oauth2": [
              "crm.objects.leads.write"
            ]
          },
          {
            "private_apps": [
              "crm.objects.leads.write"
            ]
          }
        ],
        "tags": [
          "Batch"
        ],
        "description": "Create or update records identified by `{leadsId}` or optionally a unique property value as specified by the `idProperty` query param. `{leadsId}` refers to the internal object ID by default, and the `idProperty` query param refers to a property whose values are unique for the object.",
        "operationId": "post-/crm/v3/objects/leads/batch/upsert_upsert",
        "summary": "Create or update a batch of leads by unique property values"
      }
    },
    "/crm/v3/objects/leads/search": {
      "post": {
        "security": [
          {
            "oauth2": [
              "crm.objects.leads.read"
            ]
          },
          {
            "private_apps": [
              "crm.objects.leads.read"
            ]
          }
        ],
        "tags": [
          "Search"
        ],
        "operationId": "post-/crm/v3/objects/leads/search_doSearch",
        "x-hubspot-rate-limit-exemptions": [
          "ten-secondly"
        ]
      }
    },
    "/crm/v3/objects/leads/{leadsId}": {
      "delete": {
        "security": [
          {
            "oauth2": [
              "crm.objects.leads.write"
            ]
          },
          {
            "private_apps": [
              "crm.objects.leads.write"
            ]
          }
        ],
        "tags": [
          "Basic"
        ],
        "description": "Move an Object identified by `{leadsId}` to the recycling bin.",
        "operationId": "delete-/crm/v3/objects/leads/{leadsId}_archive",
        "summary": "Archive"
      },
      "get": {
        "security": [
          {
            "oauth2": [
              "crm.objects.leads.read"
            ]
          },
          {
            "private_apps": [
              "crm.objects.leads.read"
            ]
          }
        ],
        "tags": [
          "Basic"
        ],
        "description": "Read an Object identified by `{leadsId}`. `{leadsId}` refers to the internal object ID by default, or optionally any unique property value as specified by the `idProperty` query param.  Control what is returned via the `properties` query param.",
        "operationId": "get-/crm/v3/objects/leads/{leadsId}_getById",
        "summary": "Read"
      },
      "patch": {
        "security": [
          {
            "oauth2": [
              "crm.objects.leads.write"
            ]
          },
          {
            "private_apps": [
              "crm.objects.leads.write"
            ]
          }
        ],
        "tags": [
          "Basic"
        ],
        "description": "Perform a partial update of an Object identified by `{leadsId}`or optionally a unique property value as specified by the `idProperty` query param. `{leadsId}` refers to the internal object ID by default, and the `idProperty` query param refers to a property whose values are unique for the object. Provided property values will be overwritten. Read-only and non-existent properties will result in an error. Properties values can be cleared by passing an empty string.",
        "operationId": "patch-/crm/v3/objects/leads/{leadsId}_update",
        "summary": "Update"
      }
    }
  },
  "securityDefinitions": {
    "oauth2": {
      "authorizationUrl": "https://app.hubspot.com/oauth/authorize",
      "flow": "accessCode",
      "scopes": {
        "crm.objects.appointments.read": "Read appointments",
        "crm.objects.appointments.write": "Write appointments",
        "crm.objects.carts.read": "Read carts",
        "crm.objects.carts.write": "Write cart",
        "crm.objects.commercepayments.read": "Read the COMMERCE_PAYMENT object.",
        "crm.objects.companies.read": " ",
        "crm.objects.companies.write": " ",
        "crm.objects.contacts.read": " ",
        "crm.objects.contacts.write": " ",
        "crm.objects.courses.read": "Read courses",
        "crm.objects.courses.write": "Write courses",
        "crm.objects.deals.read": " ",
        "crm.objects.deals.write": " ",
        "crm.objects.invoices.read": "Read invoices objects",
        "crm.objects.leads.read": "Read lead objects",
        "crm.objects.leads.write": "Modify lead objects",
        "crm.objects.line_items.read": "Line Items",
        "crm.objects.line_items.write": "Line Items",
        "crm.objects.listings.read": "Read listings",
        "crm.objects.listings.write": "Write listings",
        "crm.objects.orders.read": "Read Orders",
        "crm.objects.orders.write": "Write orders",
        "crm.objects.partner-clients.read": "View Partner Client CRM objects",
        "crm.objects.partner-clients.write": "Modify Partner Client CRM objects",
        "crm.objects.quotes.read": "Quotes",
        "crm.objects.quotes.write": "Quotes",
        "crm.objects.services.read": "Read services",
        "crm.objects.services.write": "Write services",
        "crm.objects.subscriptions.read": "Read Commerce Subscriptions",
        "crm.objects.users.read": "Read User CRM objects",
        "crm.objects.users.write": "Write User CRM objects"
      },
      "tokenUrl": "https://api.hubapi.com/oauth/v1/token",
      "type": "oauth2"
    },
    "oauth2_legacy": {
      "authorizationUrl": "https://app.hubspot.com/oauth/authorize",
      "flow": "accessCode",
      "scopes": {
        "crm.objects.custom.read": "View custom object records",
        "crm.objects.custom.write": "Change custom object records",
        "crm.objects.goals.read": "Read goals",
        "e-commerce": "e-commerce",
        "media_bridge.read": "Read media and media events",
        "tickets": "Read and write tickets"
      },
      "tokenUrl": "https://api.hubapi.com/oauth/v1/token",
      "type": "oauth2"
    },
    "private_apps": {
      "in": "header",
      "name": "private-app",
      "type": "apiKey"
    },
    "private_apps_legacy": {
      "in": "header",
      "name": "private-app-legacy",
      "type": "apiKey"
    }
  },
  "tags": [
    {
      "name": "Batch"
    },
    {
      "name": "Basic"
    },
    {
      "name": "Search"
    }
  ],
  "x-components": {
  },
  "x-hubspot-available-client-libraries": [
    "PHP"
  ],
  "x-hubspot-documentation-banner": "NONE",
  "x-hubspot-product-tier-requirements": {
    "cms": "FREE",
    "marketing": "FREE",
    "sales": "PROFESSIONAL",
    "service": "FREE"
  }
}
