{
  "swagger": "2.0",
  "info": {
    "title": "Lists",
    "version": "v3",
    "x-hubspot-api-use-case": "You want to bulk add contacts to a particular list, or remove company records from a company list.",
    "x-hubspot-documentation-banner": "NONE",
    "x-hubspot-introduction": "Use the lists API to manage list memberships for object lists.",
    "x-hubspot-product-tier-requirements": {
      "cms": "STARTER",
      "marketing": "STARTER"
    },
    "x-hubspot-related-documentation": [
      {
        "name": "Lists Guide",
        "url": "https://developers.hubspot.com/docs/guides/api/crm/lists/overview"
      }
    ]
  },
  "host": "api.hubapi.com",
  "basePath": "/",
  "schemes": [
    "https"
  ],
  "paths": {
    "/crm/v3/lists/": {
      "get": {
        "security": [
          {
            "private_apps": [
              "crm.lists.read"
            ]
          },
          {
            "oauth2": [
              "crm.lists.read"
            ]
          }
        ],
        "tags": [
          "Lists"
        ],
        "description": "Fetch multiple lists in a single request by **ILS list ID**. The response will include the definitions of all lists that exist for the `listIds` provided.",
        "operationId": "get-/crm/v3/lists/_getAll",
        "summary": "Fetch Multiple Lists"
      },
      "post": {
        "security": [
          {
            "private_apps": [
              "cms.membership.access_groups.write"
            ]
          },
          {
            "oauth2": [
              "cms.membership.access_groups.write"
            ]
          },
          {
            "oauth2": [
              "crm.lists.write"
            ]
          },
          {
            "private_apps": [
              "crm.lists.write"
            ]
          }
        ],
        "tags": [
          "Lists"
        ],
        "description": "Create a new list with the provided object list definition.",
        "operationId": "create_list",
        "summary": "Create List"
      }
    },
    "/crm/v3/lists/folders": {
      "get": {
        "security": [
          {
            "private_apps": [
              "crm.lists.read"
            ]
          },
          {
            "oauth2": [
              "crm.lists.read"
            ]
          }
        ],
        "tags": [
          "Folders"
        ],
        "description": "Retrieves a folder and recursively includes all folders via the childNodes attribute.  The child lists field will be empty in all child nodes. Only the folder retrieved will include the child lists in that folder.",
        "operationId": "get-/crm/v3/lists/folders_getAll",
        "summary": "Retrieves a folder."
      },
      "post": {
        "security": [
          {
            "oauth2": [
              "cms.membership.access_groups.write",
              "crm.lists.read"
            ]
          },
          {
            "private_apps": [
              "crm.lists.write",
              "crm.lists.read"
            ]
          },
          {
            "oauth2": [
              "crm.lists.write",
              "crm.lists.read"
            ]
          },
          {
            "private_apps": [
              "cms.membership.access_groups.write",
              "crm.lists.read"
            ]
          }
        ],
        "tags": [
          "Folders"
        ],
        "description": "Creates a folder with the given information.",
        "operationId": "post-/crm/v3/lists/folders_create",
        "summary": "Creates a folder"
      }
    },
    "/crm/v3/lists/folders/move-list": {
      "put": {
        "security": [
          {
            "oauth2": [
              "cms.membership.access_groups.write",
              "crm.lists.read"
            ]
          },
          {
            "private_apps": [
              "crm.lists.write",
              "crm.lists.read"
            ]
          },
          {
            "oauth2": [
              "crm.lists.write",
              "crm.lists.read"
            ]
          },
          {
            "private_apps": [
              "cms.membership.access_groups.write",
              "crm.lists.read"
            ]
          }
        ],
        "tags": [
          "Folders"
        ],
        "description": "Given a list and a folder, the list will be moved to that folder.",
        "operationId": "put-/crm/v3/lists/folders/move-list_moveList",
        "summary": "Moves a list to a given folder"
      }
    },
    "/crm/v3/lists/folders/{folderId}": {
      "delete": {
        "security": [
          {
            "oauth2": [
              "cms.membership.access_groups.write",
              "crm.lists.read"
            ]
          },
          {
            "private_apps": [
              "crm.lists.write",
              "crm.lists.read"
            ]
          },
          {
            "oauth2": [
              "crm.lists.write",
              "crm.lists.read"
            ]
          },
          {
            "private_apps": [
              "cms.membership.access_groups.write",
              "crm.lists.read"
            ]
          }
        ],
        "tags": [
          "Folders"
        ],
        "description": "Deletes the folder with the given Id.",
        "operationId": "delete-/crm/v3/lists/folders/{folderId}_remove",
        "summary": "Deletes a folder"
      }
    },
    "/crm/v3/lists/folders/{folderId}/move/{newParentFolderId}": {
      "put": {
        "security": [
          {
            "oauth2": [
              "cms.membership.access_groups.write",
              "crm.lists.read"
            ]
          },
          {
            "private_apps": [
              "crm.lists.write",
              "crm.lists.read"
            ]
          },
          {
            "oauth2": [
              "crm.lists.write",
              "crm.lists.read"
            ]
          },
          {
            "private_apps": [
              "cms.membership.access_groups.write",
              "crm.lists.read"
            ]
          }
        ],
        "tags": [
          "Folders"
        ],
        "description": "This moves the folder from its current location to a new location. It updates the parent of this folder to the new Id given.",
        "operationId": "put-/crm/v3/lists/folders/{folderId}/move/{newParentFolderId}_move",
        "summary": "Moves a folder"
      }
    },
    "/crm/v3/lists/folders/{folderId}/rename": {
      "put": {
        "security": [
          {
            "oauth2": [
              "cms.membership.access_groups.write",
              "crm.lists.read"
            ]
          },
          {
            "private_apps": [
              "crm.lists.write",
              "crm.lists.read"
            ]
          },
          {
            "oauth2": [
              "crm.lists.write",
              "crm.lists.read"
            ]
          },
          {
            "private_apps": [
              "cms.membership.access_groups.write",
              "crm.lists.read"
            ]
          }
        ],
        "tags": [
          "Folders"
        ],
        "description": "Renames the given folderId with a new name.",
        "operationId": "put-/crm/v3/lists/folders/{folderId}/rename_rename",
        "summary": "Rename a folder"
      }
    },
    "/crm/v3/lists/idmapping": {
      "get": {
        "security": [
          {
            "private_apps": [
              "crm.lists.read"
            ]
          },
          {
            "oauth2": [
              "crm.lists.read"
            ]
          }
        ],
        "tags": [
          "Mapping"
        ],
        "description": "This API allows translation of legacy list id to list id. This is a temporary API allowed for mapping old id's to new id's and will expire on May 30th, 2025.",
        "operationId": "get-/crm/v3/lists/idmapping_translateLegacyListIdToListId",
        "summary": "Translate Legacy List Id to Modern List Id"
      },
      "post": {
        "security": [
          {
            "private_apps": [
              "crm.lists.read"
            ]
          },
          {
            "oauth2": [
              "crm.lists.read"
            ]
          }
        ],
        "tags": [
          "Mapping"
        ],
        "description": "This API allows translation of a batch of legacy list id's to list id's. This allows for a maximum of 10,000 id's. This is a temporary API allowed for mapping old id's to new id's and will expire on May 30th, 2025.",
        "operationId": "post-/crm/v3/lists/idmapping_translateLegacyListIdToListIdBatch",
        "summary": "Translate Legacy List Id to Modern List Id in Batch"
      }
    },
    "/crm/v3/lists/object-type-id/{objectTypeId}/name/{listName}": {
      "get": {
        "security": [
          {
            "private_apps": [
              "crm.lists.read"
            ]
          },
          {
            "oauth2": [
              "crm.lists.read"
            ]
          }
        ],
        "tags": [
          "Lists"
        ],
        "description": "Fetch a single list by list name and object type.",
        "operationId": "get-/crm/v3/lists/object-type-id/{objectTypeId}/name/{listName}_getByName",
        "summary": "Fetch List by Name"
      }
    },
    "/crm/v3/lists/records/{objectTypeId}/{recordId}/memberships": {
      "get": {
        "security": [
          {
            "private_apps": [
              "crm.lists.read"
            ]
          },
          {
            "oauth2": [
              "crm.lists.read"
            ]
          }
        ],
        "tags": [
          "Memberships"
        ],
        "description": "For given record provide lists this record is member of.",
        "operationId": "get-/crm/v3/lists/records/{objectTypeId}/{recordId}/memberships_getLists",
        "summary": "Get lists record is member of"
      }
    },
    "/crm/v3/lists/search": {
      "post": {
        "security": [
          {
            "private_apps": [
              "crm.lists.read"
            ]
          },
          {
            "oauth2": [
              "crm.lists.read"
            ]
          }
        ],
        "tags": [
          "Lists"
        ],
        "description": "Search lists by list name or page through all lists by providing an empty `query` value.",
        "operationId": "search_lists",
        "summary": "Search Lists"
      }
    },
    "/crm/v3/lists/{listId}": {
      "delete": {
        "security": [
          {
            "oauth2": [
              "cms.membership.access_groups.write",
              "crm.lists.read"
            ]
          },
          {
            "private_apps": [
              "crm.lists.write",
              "crm.lists.read"
            ]
          },
          {
            "oauth2": [
              "crm.lists.write",
              "crm.lists.read"
            ]
          },
          {
            "private_apps": [
              "cms.membership.access_groups.write",
              "crm.lists.read"
            ]
          }
        ],
        "tags": [
          "Lists"
        ],
        "description": "Delete a list by **ILS list ID**. Lists deleted through this endpoint can be restored up to 90-days following the delete. After 90-days, the list is purged and can no longer be restored.",
        "operationId": "delete_list",
        "summary": "Delete a List"
      },
      "get": {
        "security": [
          {
            "private_apps": [
              "crm.lists.read"
            ]
          },
          {
            "oauth2": [
              "crm.lists.read"
            ]
          }
        ],
        "tags": [
          "Lists"
        ],
        "description": "Fetch a single list by **ILS list ID**.",
        "operationId": "get_list",
        "summary": "Fetch List by ID"
      }
    },
    "/crm/v3/lists/{listId}/memberships": {
      "delete": {
        "security": [
          {
            "oauth2": [
              "cms.membership.access_groups.write",
              "crm.lists.read"
            ]
          },
          {
            "private_apps": [
              "crm.lists.write",
              "crm.lists.read"
            ]
          },
          {
            "oauth2": [
              "crm.lists.write",
              "crm.lists.read"
            ]
          },
          {
            "private_apps": [
              "cms.membership.access_groups.write",
              "crm.lists.read"
            ]
          }
        ],
        "tags": [
          "Memberships"
        ],
        "description": "Remove **all** of the records from a list. ***Note:*** *The list is not deleted.*\n\nThis endpoint only works for lists that have a `processingType` of `MANUAL` or `SNAPSHOT`.\n\nThis endpoint only supports lists that have less than 100,000 memberships.",
        "operationId": "delete-/crm/v3/lists/{listId}/memberships_removeAll",
        "summary": "Delete All Records from a List"
      },
      "get": {
        "security": [
          {
            "private_apps": [
              "crm.lists.read"
            ]
          },
          {
            "oauth2": [
              "crm.lists.read"
            ]
          }
        ],
        "tags": [
          "Memberships"
        ],
        "description": "Fetch the memberships of a list in order sorted by the `recordId` of the records in the list.\n\nThe `recordId`s are sorted in *ascending* order if an `after` offset or no offset is provided. If only a `before` offset is provided, then the records are sorted in *descending* order.\n\nThe `after` offset parameter will take precedence over the `before` offset in a case where both are provided.",
        "operationId": "get-/crm/v3/lists/{listId}/memberships_getPage",
        "summary": "Fetch List Memberships Ordered by ID"
      }
    },
    "/crm/v3/lists/{listId}/memberships/add": {
      "put": {
        "security": [
          {
            "oauth2": [
              "cms.membership.access_groups.write",
              "crm.lists.read"
            ]
          },
          {
            "private_apps": [
              "crm.lists.write",
              "crm.lists.read"
            ]
          },
          {
            "oauth2": [
              "crm.lists.write",
              "crm.lists.read"
            ]
          },
          {
            "private_apps": [
              "cms.membership.access_groups.write",
              "crm.lists.read"
            ]
          }
        ],
        "tags": [
          "Memberships"
        ],
        "description": "Add the records provided to the list. Records that do not exist or that are already members of the list are ignored.\n\nThis endpoint only works for lists that have a `processingType` of `MANUAL` or `SNAPSHOT`.",
        "operationId": "add_memberships",
        "summary": "Add Records to a List"
      }
    },
    "/crm/v3/lists/{listId}/memberships/add-and-remove": {
      "put": {
        "security": [
          {
            "oauth2": [
              "cms.membership.access_groups.write",
              "crm.lists.read"
            ]
          },
          {
            "private_apps": [
              "crm.lists.write",
              "crm.lists.read"
            ]
          },
          {
            "oauth2": [
              "crm.lists.write",
              "crm.lists.read"
            ]
          },
          {
            "private_apps": [
              "cms.membership.access_groups.write",
              "crm.lists.read"
            ]
          }
        ],
        "tags": [
          "Memberships"
        ],
        "description": "Add and/or remove records that have already been created in the system to and/or from a list.\n\nThis endpoint only works for lists that have a `processingType` of `MANUAL` or `SNAPSHOT`.",
        "operationId": "put-/crm/v3/lists/{listId}/memberships/add-and-remove_addAndRemove",
        "summary": "Add and/or Remove Records from a List"
      }
    },
    "/crm/v3/lists/{listId}/memberships/add-from/{sourceListId}": {
      "put": {
        "security": [
          {
            "oauth2": [
              "cms.membership.access_groups.write",
              "crm.lists.read"
            ]
          },
          {
            "private_apps": [
              "crm.lists.write",
              "crm.lists.read"
            ]
          },
          {
            "oauth2": [
              "crm.lists.write",
              "crm.lists.read"
            ]
          },
          {
            "private_apps": [
              "cms.membership.access_groups.write",
              "crm.lists.read"
            ]
          }
        ],
        "tags": [
          "Memberships"
        ],
        "description": "Add all of the records from a *source list* (specified by the `sourceListId`) to a *destination list* (specified by the `listId`). Records that are already members of the *destination list* will be ignored. The *destination* and *source list* IDs must be different. The *destination* and *source lists* must contain records of the same type (e.g. contacts, companies, etc.).\n\nThis endpoint only works for *destination lists* that have a `processingType` of `MANUAL` or `SNAP[...]",
        "operationId": "add_members_from_source_list",
        "summary": "Add All Records from a Source List to a Destination List"
      }
    },
    "/crm/v3/lists/{listId}/memberships/join-order": {
      "get": {
        "security": [
          {
            "private_apps": [
              "crm.lists.read"
            ]
          },
          {
            "oauth2": [
              "crm.lists.read"
            ]
          }
        ],
        "tags": [
          "Memberships"
        ],
        "description": "Fetch the memberships of a list in order sorted by the time the records were added to the list.\n\nThe `recordId`s are sorted in *ascending* order if an `after` offset or no offset is provided. If only a `before` offset is provided, then the records are sorted in *descending* order.\n\nThe `after` offset parameter will take precedence over the `before` offset in a case where both are provided.",
        "operationId": "get-/crm/v3/lists/{listId}/memberships/join-order_getPageOrderedByAddedToListDate",
        "summary": "Fetch List Memberships Ordered by Added to List Date"
      }
    },
    "/crm/v3/lists/{listId}/memberships/remove": {
      "put": {
        "security": [
          {
            "oauth2": [
              "cms.membership.access_groups.write",
              "crm.lists.read"
            ]
          },
          {
            "private_apps": [
              "crm.lists.write",
              "crm.lists.read"
            ]
          },
          {
            "oauth2": [
              "crm.lists.write",
              "crm.lists.read"
            ]
          },
          {
            "private_apps": [
              "cms.membership.access_groups.write",
              "crm.lists.read"
            ]
          }
        ],
        "tags": [
          "Memberships"
        ],
        "description": "Remove the records provided from the list. Records that do not exist or that are not members of the list are ignored.\n\nThis endpoint only works for lists that have a `processingType` of `MANUAL` or `SNAPSHOT`.",
        "operationId": "remove_members_from_list",
        "summary": "Remove Records from a List"
      }
    },
    "/crm/v3/lists/{listId}/restore": {
      "put": {
        "security": [
          {
            "oauth2": [
              "cms.membership.access_groups.write",
              "crm.lists.read"
            ]
          },
          {
            "private_apps": [
              "crm.lists.write",
              "crm.lists.read"
            ]
          },
          {
            "oauth2": [
              "crm.lists.write",
              "crm.lists.read"
            ]
          },
          {
            "private_apps": [
              "cms.membership.access_groups.write",
              "crm.lists.read"
            ]
          }
        ],
        "tags": [
          "Lists"
        ],
        "description": "Restore a previously deleted list by **ILS list ID**. Deleted lists are eligible to be restored up-to 90-days after the list has been deleted.",
        "operationId": "put-/crm/v3/lists/{listId}/restore_restore",
        "summary": "Restore a List"
      }
    },
    "/crm/v3/lists/{listId}/update-list-filters": {
      "put": {
        "security": [
          {
            "oauth2": [
              "cms.membership.access_groups.write",
              "crm.lists.read"
            ]
          },
          {
            "private_apps": [
              "crm.lists.write",
              "crm.lists.read"
            ]
          },
          {
            "oauth2": [
              "crm.lists.write",
              "crm.lists.read"
            ]
          },
          {
            "private_apps": [
              "cms.membership.access_groups.write",
              "crm.lists.read"
            ]
          }
        ],
        "tags": [
          "Lists"
        ],
        "description": "Update the filter branch definition of a `DYNAMIC` list. Once updated, the list memberships will be re-evaluated and updated to match the new definition.",
        "operationId": "put-/crm/v3/lists/{listId}/update-list-filters_updateListFilters",
        "summary": "Update List Filter Definition"
      }
    },
    "/crm/v3/lists/{listId}/update-list-name": {
      "put": {
        "security": [
          {
            "oauth2": [
              "cms.membership.access_groups.write",
              "crm.lists.read"
            ]
          },
          {
            "private_apps": [
              "crm.lists.write",
              "crm.lists.read"
            ]
          },
          {
            "oauth2": [
              "crm.lists.write",
              "crm.lists.read"
            ]
          },
          {
            "private_apps": [
              "cms.membership.access_groups.write",
              "crm.lists.read"
            ]
          }
        ],
        "tags": [
          "Lists"
        ],
        "description": "Update the name of a list. The name must be globally unique relative to all other public lists in the portal.",
        "operationId": "put-/crm/v3/lists/{listId}/update-list-name_updateName",
        "summary": "Update List Name"
      }
    }
  },
  "securityDefinitions": {
    "oauth2": {
      "authorizationUrl": "https://app.hubspot.com/oauth/authorize",
      "flow": "accessCode",
      "scopes": {
        "cms.membership.access_groups.write": "Write membership access groups.",
        "crm.lists.read": " ",
        "crm.lists.write": " "
      },
      "tokenUrl": "https://api.hubapi.com/oauth/v1/token",
      "type": "oauth2"
    },
    "private_apps": {
      "in": "header",
      "name": "private-app",
      "type": "apiKey"
    }
  },
  "tags": [
    {
      "name": "Lists"
    },
    {
      "name": "Memberships"
    },
    {
      "name": "Folders"
    },
    {
      "name": "Mapping"
    }
  ],
  "x-components": {
  },
  "x-hubspot-available-client-libraries": [
    "PHP",
    "Node",
    "Ruby",
    "Python"
  ],
  "x-hubspot-documentation-banner": "NONE",
  "x-hubspot-product-tier-requirements": {
    "cms": "STARTER",
    "marketing": "STARTER"
  }
}