import { TQoreResponseType } from '@qoretechnologies/ts-toolkit';

export const BigMlAnomalyResponseType = {
  type: 'hash',
  fields: {
    anomaly_seed: { type: 'string' },
    category: { type: 'integer' },
    code: { type: 'integer' },
    columns: { type: 'integer' },
    configuration: { type: 'string' },
    configuration_status: { type: 'bool' },
    constraints: { type: 'bool' },
    created: { type: 'string' },
    creator: { type: 'string' },
    dataset: { type: 'string' },
    dataset_field_types: {
      type: {
        type: 'hash',
        fields: {
          categorical: { type: 'integer' },
          datetime: { type: 'integer' },
          image: { type: 'integer' },
          items: { type: 'integer' },
          numeric: { type: 'integer' },
          path: { type: 'integer' },
          preferred: { type: 'integer' },
          regions: { type: 'integer' },
          text: { type: 'integer' },
          total: { type: 'integer' },
        },
      },
    },
    dataset_status: { type: 'bool' },
    description: { type: 'string' },
    forest_size: { type: 'integer' },
    id_fields: {
      type: {
        type: 'list',
        element_type: 'string',
      },
    },
    learning_rate: { type: 'number' },
    locale: { type: 'string' },
    max_columns: { type: 'integer' },
    max_rows: { type: 'integer' },
    name: { type: 'string' },
    name_options: { type: 'string' },
    normalize_repeats: { type: 'bool' },
    number_of_anomalyscores: { type: 'integer' },
    number_of_batchanomalyscores: { type: 'integer' },
    number_of_public_anomalyscores: { type: 'integer' },
    ordering: { type: 'integer' },
    out_of_bag: { type: 'bool' },
    parent_anomaly: { type: 'string' },
    parent_anomaly_status: { type: 'bool' },
    price: { type: 'number' },
    private: { type: 'bool' },
    project: { type: 'string' },
    range: { type: 'string' },
    replacement: { type: 'bool' },
    resource: { type: 'string' },
    rows: { type: 'integer' },
    sample_rate: { type: 'number' },
    sample_size: { type: 'integer' },
    shared: { type: 'bool' },
    size: { type: 'integer' },
    source: { type: 'string' },
    source_status: { type: 'bool' },
    status: {
      type: {
        type: 'hash',
        fields: {
          code: { type: 'integer' },
          elapsed: { type: 'integer' },
          message: { type: 'string' },
          progress: { type: 'number' },
        },
      },
    },
    subscription: { type: 'bool' },
    tags: {
      type: {
        type: 'list',
        element_type: 'string',
      },
    },
    top_n: { type: 'integer' },
    type: { type: 'integer' },
    updated: { type: 'string' },
    white_box: { type: 'bool' },
  },
} satisfies TQoreResponseType;
