import { TQoreResponseType } from '@qoretechnologies/ts-toolkit';

export const BigMlClusterResponseType = {
  type: 'hash',
  fields: {
    balance_fields: { type: 'bool' },
    category: { type: 'integer' },
    cluster_datasets: { type: 'hash' },
    cluster_models: { type: 'hash' },
    code: { type: 'integer' },
    columns: { type: 'integer' },
    configuration: { type: 'string' },
    configuration_status: { type: 'bool' },
    created: { type: 'string' },
    creator: { type: 'string' },
    critical_value: { type: 'number' },
    dataset: { type: 'string' },
    dataset_field_types: {
      type: {
        type: 'hash',
        fields: {
          categorical: { type: 'integer' },
          datetime: { type: 'integer' },
          image: { type: 'integer' },
          items: { type: 'integer' },
          numeric: { type: 'integer' },
          path: { type: 'integer' },
          preferred: { type: 'integer' },
          regions: { type: 'integer' },
          text: { type: 'integer' },
          total: { type: 'integer' },
        },
      },
    },
    dataset_status: { type: 'bool' },
    description: { type: 'string' },
    field_scales: { type: 'hash' },
    k: { type: 'integer' },
    locale: { type: 'string' },
    max_columns: { type: 'integer' },
    max_rows: { type: 'integer' },
    model_clusters: { type: 'bool' },
    name: { type: 'string' },
    name_options: { type: 'string' },
    number_of_batchcentroids: { type: 'integer' },
    number_of_centroids: { type: 'integer' },
    number_of_public_centroids: { type: 'integer' },
    ordering: { type: 'integer' },
    out_of_bag: { type: 'bool' },
    price: { type: 'number' },
    private: { type: 'bool' },
    project: { type: 'string' },
    range: { type: 'string' },
    replacement: { type: 'bool' },
    resource: { type: 'string' },
    rows: { type: 'integer' },
    sample_rate: { type: 'number' },
    scales: { type: 'string' },
    shared: { type: 'bool' },
    size: { type: 'integer' },
    source: { type: 'string' },
    source_status: { type: 'bool' },
    status: {
      type: {
        type: 'hash',
        fields: {
          code: { type: 'integer' },
          elapsed: { type: 'integer' },
          message: { type: 'string' },
          progress: { type: 'number' },
        },
      },
    },
    subscription: { type: 'bool' },
    summary_fields: {
      type: {
        type: 'list',
        element_type: 'string',
      },
    },
    tags: {
      type: {
        type: 'list',
        element_type: 'string',
      },
    },
    type: { type: 'integer' },
    updated: { type: 'string' },
    weight_field: { type: 'string' },
    white_box: { type: 'bool' },
  },
} satisfies TQoreResponseType;
