import { TQoreResponseType } from '@qoretechnologies/ts-toolkit';

export const BigMlEnsembleResponseType = {
  type: 'hash',
  fields: {
    boosting: { type: 'string' },
    category: { type: 'integer' },
    code: { type: 'integer' },
    columns: { type: 'integer' },
    configuration: { type: 'string' },
    configuration_status: { type: 'bool' },
    created: { type: 'string' },
    creator: { type: 'string' },
    dataset: { type: 'string' },
    dataset_field_types: {
      type: {
        type: 'hash',
        fields: {
          categorical: { type: 'integer' },
          datetime: { type: 'integer' },
          image: { type: 'integer' },
          items: { type: 'integer' },
          numeric: { type: 'integer' },
          path: { type: 'integer' },
          preferred: { type: 'integer' },
          regions: { type: 'integer' },
          text: { type: 'integer' },
          total: { type: 'integer' },
        },
      },
    },
    dataset_status: { type: 'bool' },
    depth_threshold: { type: 'integer' },
    description: { type: 'string' },
    ensemble: { type: 'hash' },
    ensemble_sample: {
      type: {
        type: 'hash',
        fields: {
          rate: { type: 'number' },
          replacement: { type: 'bool' },
          seed: { type: 'string' },
        },
      },
    },
    error_models: { type: 'integer' },
    finished_models: { type: 'integer' },
    focus_field: { type: 'string' },
    focus_field_name: { type: 'string' },
    importance: { type: 'hash' },
    locale: { type: 'string' },
    max_columns: { type: 'integer' },
    max_rows: { type: 'integer' },
    missing_splits: { type: 'bool' },
    name: { type: 'string' },
    name_options: { type: 'string' },
    node_threshold: { type: 'integer' },
    number_of_batchpredictions: { type: 'integer' },
    number_of_evaluations: { type: 'integer' },
    number_of_models: { type: 'integer' },
    number_of_predictions: { type: 'integer' },
    number_of_public_predictions: { type: 'integer' },
    objective_field: { type: 'string' },
    objective_field_details: {
      type: {
        type: 'hash',
        fields: {
          column_number: { type: 'integer' },
          datatype: { type: 'string' },
          name: { type: 'string' },
          optype: { type: 'string' },
          order: { type: 'integer' },
        },
      },
    },
    objective_field_name: { type: 'string' },
    objective_field_type: { type: 'string' },
    objective_fields: {
      type: {
        type: 'list',
        element_type: 'string',
      },
    },
    optiml: { type: 'string' },
    optiml_status: { type: 'bool' },
    ordering: { type: 'integer' },
    out_of_bag: { type: 'bool' },
    price: { type: 'number' },
    private: { type: 'bool' },
    project: { type: 'string' },
    randomize: { type: 'bool' },
    range: { type: 'string' },
    replacement: { type: 'bool' },
    resource: { type: 'string' },
    rows: { type: 'integer' },
    sample_rate: { type: 'number' },
    selective_pruning: { type: 'bool' },
    shared: { type: 'bool' },
    size: { type: 'integer' },
    source: { type: 'string' },
    source_status: { type: 'bool' },
    split_candidates: { type: 'integer' },
    split_field: { type: 'string' },
    split_field_name: { type: 'string' },
    stat_pruning: { type: 'bool' },
    status: {
      type: {
        type: 'hash',
        fields: {
          code: { type: 'integer' },
          elapsed: { type: 'integer' },
          message: { type: 'string' },
          progress: { type: 'number' },
        },
      },
    },
    subscription: { type: 'bool' },
    support_threshold: { type: 'number' },
    tags: {
      type: {
        type: 'list',
        element_type: 'string',
      },
    },
    type: { type: 'integer' },
    updated: { type: 'string' },
    white_box: { type: 'bool' },
  },
} satisfies TQoreResponseType;
