import { IQoreAllowedValue } from '@qoretechnologies/ts-toolkit';

export const PaddleCountryAllowedValues = [
  { value: 'AD', display_name: 'AD - Andorra', desc: 'Andorra' },
  { value: 'AE', display_name: 'AE - United Arab Emirates', desc: 'United Arab Emirates' },
  { value: 'AG', display_name: 'AG - Antigua and Barbuda', desc: 'Antigua and Barbuda' },
  { value: 'AI', display_name: 'AI - Anguilla', desc: 'Anguilla' },
  { value: 'AL', display_name: 'AL - Albania', desc: 'Albania' },
  { value: 'AM', display_name: 'AM - Armenia', desc: 'Armenia' },
  { value: 'AO', display_name: 'AO - Angola', desc: 'Angola' },
  { value: 'AR', display_name: 'AR - Argentina', desc: 'Argentina' },
  { value: 'AS', display_name: 'AS - American Samoa', desc: 'American Samoa' },
  { value: 'AT', display_name: 'AT - Austria', desc: 'Austria' },
  { value: 'AU', display_name: 'AU - Australia', desc: 'Australia' },
  { value: 'AW', display_name: 'AW - Aruba', desc: 'Aruba' },
  { value: 'AX', display_name: 'AX - Åland Islands', desc: 'Åland Islands' },
  { value: 'AZ', display_name: 'AZ - Azerbaijan', desc: 'Azerbaijan' },
  { value: 'BA', display_name: 'BA - Bosnia and Herzegovina', desc: 'Bosnia and Herzegovina' },
  { value: 'BB', display_name: 'BB - Barbados', desc: 'Barbados' },
  { value: 'BD', display_name: 'BD - Bangladesh', desc: 'Bangladesh' },
  { value: 'BE', display_name: 'BE - Belgium', desc: 'Belgium' },
  { value: 'BF', display_name: 'BF - Burkina Faso', desc: 'Burkina Faso' },
  { value: 'BG', display_name: 'BG - Bulgaria', desc: 'Bulgaria' },
  { value: 'BH', display_name: 'BH - Bahrain', desc: 'Bahrain' },
  { value: 'BI', display_name: 'BI - Burundi', desc: 'Burundi' },
  { value: 'BJ', display_name: 'BJ - Benin', desc: 'Benin' },
  { value: 'BL', display_name: 'BL - Saint Barthélemy', desc: 'Saint Barthélemy' },
  { value: 'BM', display_name: 'BM - Bermuda', desc: 'Bermuda' },
  { value: 'BN', display_name: 'BN - Brunei', desc: 'Brunei' },
  { value: 'BO', display_name: 'BO - Bolivia', desc: 'Bolivia' },
  {
    value: 'BQ',
    display_name: 'BQ - Caribbean Netherlands',
    desc: 'Caribbean Netherlands (Bonaire, Sint Eustatius, and Saba)',
  },
  { value: 'BR', display_name: 'BR - Brazil', desc: 'Brazil' },
  { value: 'BS', display_name: 'BS - Bahamas', desc: 'Bahamas' },
  { value: 'BT', display_name: 'BT - Bhutan', desc: 'Bhutan' },
  { value: 'BV', display_name: 'BV - Bouvet Island', desc: 'Bouvet Island' },
  { value: 'BW', display_name: 'BW - Botswana', desc: 'Botswana' },
  { value: 'BZ', display_name: 'BZ - Belize', desc: 'Belize' },
  { value: 'CA', display_name: 'CA - Canada', desc: 'Canada' },
  { value: 'CC', display_name: 'CC - Cocos Islands', desc: 'Cocos Islands' },
  { value: 'CG', display_name: 'CG - Republic of Congo', desc: 'Republic of Congo' },
  { value: 'CH', display_name: 'CH - Switzerland', desc: 'Switzerland' },
  { value: 'CI', display_name: "CI - Côte d'Ivoire", desc: "Côte d'Ivoire (Ivory Coast)" },
  { value: 'CK', display_name: 'CK - Cook Islands', desc: 'Cook Islands' },
  { value: 'CL', display_name: 'CL - Chile', desc: 'Chile' },
  { value: 'CM', display_name: 'CM - Cameroon', desc: 'Cameroon' },
  { value: 'CN', display_name: 'CN - China', desc: 'China' },
  { value: 'CO', display_name: 'CO - Colombia', desc: 'Colombia' },
  { value: 'CR', display_name: 'CR - Costa Rica', desc: 'Costa Rica' },
  { value: 'CV', display_name: 'CV - Cape Verde', desc: 'Cape Verde' },
  { value: 'CW', display_name: 'CW - Curaçao', desc: 'Curaçao' },
  { value: 'CX', display_name: 'CX - Christmas Island', desc: 'Christmas Island' },
  { value: 'CY', display_name: 'CY - Cyprus', desc: 'Cyprus' },
  { value: 'CZ', display_name: 'CZ - Czechia', desc: 'Czechia (Czech Republic)' },
  { value: 'DE', display_name: 'DE - Germany', desc: 'Germany' },
  { value: 'DJ', display_name: 'DJ - Djibouti', desc: 'Djibouti' },
  { value: 'DK', display_name: 'DK - Denmark', desc: 'Denmark' },
  { value: 'DM', display_name: 'DM - Dominica', desc: 'Dominica' },
  { value: 'DO', display_name: 'DO - Dominican Republic', desc: 'Dominican Republic' },
  { value: 'DZ', display_name: 'DZ - Algeria', desc: 'Algeria' },
  { value: 'EC', display_name: 'EC - Ecuador', desc: 'Ecuador' },
  { value: 'EE', display_name: 'EE - Estonia', desc: 'Estonia' },
  { value: 'EG', display_name: 'EG - Egypt', desc: 'Egypt' },
  { value: 'EH', display_name: 'EH - Western Sahara', desc: 'Western Sahara' },
  { value: 'ER', display_name: 'ER - Eritrea', desc: 'Eritrea' },
  { value: 'ES', display_name: 'ES - Spain', desc: 'Spain' },
  { value: 'ET', display_name: 'ET - Ethiopia', desc: 'Ethiopia' },
  { value: 'FI', display_name: 'FI - Finland', desc: 'Finland' },
  { value: 'FJ', display_name: 'FJ - Fiji', desc: 'Fiji' },
  { value: 'FK', display_name: 'FK - Falkland Islands', desc: 'Falkland Islands' },
  { value: 'FM', display_name: 'FM - Micronesia', desc: 'Micronesia' },
  { value: 'FO', display_name: 'FO - Faroe Islands', desc: 'Faroe Islands' },
  { value: 'FR', display_name: 'FR - France', desc: 'France' },
  { value: 'GA', display_name: 'GA - Gabon', desc: 'Gabon' },
  { value: 'GB', display_name: 'GB - United Kingdom', desc: 'United Kingdom' },
  { value: 'GD', display_name: 'GD - Grenada', desc: 'Grenada' },
  { value: 'GE', display_name: 'GE - Georgia', desc: 'Georgia' },
  { value: 'GF', display_name: 'GF - French Guiana', desc: 'French Guiana' },
  { value: 'GG', display_name: 'GG - Guernsey', desc: 'Guernsey' },
  { value: 'GH', display_name: 'GH - Ghana', desc: 'Ghana' },
  { value: 'GI', display_name: 'GI - Gibraltar', desc: 'Gibraltar' },
  { value: 'GL', display_name: 'GL - Greenland', desc: 'Greenland' },
  { value: 'GM', display_name: 'GM - Gambia', desc: 'Gambia' },
  { value: 'GN', display_name: 'GN - Guinea', desc: 'Guinea' },
  { value: 'GP', display_name: 'GP - Guadeloupe', desc: 'Guadeloupe' },
  { value: 'GQ', display_name: 'GQ - Equatorial Guinea', desc: 'Equatorial Guinea' },
  { value: 'GR', display_name: 'GR - Greece', desc: 'Greece' },
  {
    value: 'GS',
    display_name: 'GS - South Georgia and the South Sandwich Islands',
    desc: 'South Georgia and the South Sandwich Islands',
  },
  { value: 'GT', display_name: 'GT - Guatemala', desc: 'Guatemala' },
  { value: 'GU', display_name: 'GU - Guam', desc: 'Guam' },
  { value: 'GW', display_name: 'GW - Guinea-Bissau', desc: 'Guinea-Bissau' },
  { value: 'GY', display_name: 'GY - Guyana', desc: 'Guyana' },
  { value: 'HK', display_name: 'HK - Hong Kong', desc: 'Hong Kong' },
  {
    value: 'HM',
    display_name: 'HM - Heard Island and McDonald Islands',
    desc: 'Heard Island and McDonald Islands',
  },
  { value: 'HN', display_name: 'HN - Honduras', desc: 'Honduras' },
  { value: 'HR', display_name: 'HR - Croatia', desc: 'Croatia' },
  { value: 'HU', display_name: 'HU - Hungary', desc: 'Hungary' },
  { value: 'ID', display_name: 'ID - Indonesia', desc: 'Indonesia' },
  { value: 'IE', display_name: 'IE - Ireland', desc: 'Ireland' },
  { value: 'IL', display_name: 'IL - Israel', desc: 'Israel' },
  { value: 'IM', display_name: 'IM - Isle of Man', desc: 'Isle of Man' },
  { value: 'IN', display_name: 'IN - India', desc: 'India' },
  {
    value: 'IO',
    display_name: 'IO - British Indian Ocean Territory',
    desc: 'British Indian Ocean Territory',
  },
  { value: 'IQ', display_name: 'IQ - Iraq', desc: 'Iraq' },
  { value: 'IS', display_name: 'IS - Iceland', desc: 'Iceland' },
  { value: 'IT', display_name: 'IT - Italy', desc: 'Italy' },
  { value: 'JE', display_name: 'JE - Jersey', desc: 'Jersey' },
  { value: 'JM', display_name: 'JM - Jamaica', desc: 'Jamaica' },
  { value: 'JO', display_name: 'JO - Jordan', desc: 'Jordan' },
  { value: 'JP', display_name: 'JP - Japan', desc: 'Japan' },
  { value: 'KE', display_name: 'KE - Kenya', desc: 'Kenya' },
  { value: 'KG', display_name: 'KG - Kyrgyzstan', desc: 'Kyrgyzstan' },
  { value: 'KH', display_name: 'KH - Cambodia', desc: 'Cambodia' },
  { value: 'KI', display_name: 'KI - Kiribati', desc: 'Kiribati' },
  { value: 'KM', display_name: 'KM - Comoros', desc: 'Comoros' },
  { value: 'KN', display_name: 'KN - Saint Kitts and Nevis', desc: 'Saint Kitts and Nevis' },
  { value: 'KR', display_name: 'KR - South Korea', desc: 'South Korea' },
  { value: 'KW', display_name: 'KW - Kuwait', desc: 'Kuwait' },
  { value: 'KY', display_name: 'KY - Cayman Islands', desc: 'Cayman Islands' },
  { value: 'KZ', display_name: 'KZ - Kazakhstan', desc: 'Kazakhstan' },
  { value: 'LA', display_name: 'LA - Laos', desc: "Lao People's Democratic Republic (Laos)" },
  { value: 'LB', display_name: 'LB - Lebanon', desc: 'Lebanon' },
  { value: 'LC', display_name: 'LC - Saint Lucia', desc: 'Saint Lucia' },
  { value: 'LI', display_name: 'LI - Liechtenstein', desc: 'Liechtenstein' },
  { value: 'LK', display_name: 'LK - Sri Lanka', desc: 'Sri Lanka' },
  { value: 'LR', display_name: 'LR - Liberia', desc: 'Liberia' },
  { value: 'LS', display_name: 'LS - Lesotho', desc: 'Lesotho' },
  { value: 'LT', display_name: 'LT - Lithuania', desc: 'Lithuania' },
  { value: 'LU', display_name: 'LU - Luxembourg', desc: 'Luxembourg' },
  { value: 'LV', display_name: 'LV - Latvia', desc: 'Latvia' },
  { value: 'MA', display_name: 'MA - Morocco', desc: 'Morocco' },
  { value: 'MC', display_name: 'MC - Monaco', desc: 'Monaco' },
  { value: 'MD', display_name: 'MD - Moldova', desc: 'Moldova' },
  { value: 'ME', display_name: 'ME - Montenegro', desc: 'Montenegro' },
  { value: 'MF', display_name: 'MF - Saint Martin', desc: 'Saint Martin' },
  { value: 'MG', display_name: 'MG - Madagascar', desc: 'Madagascar' },
  { value: 'MH', display_name: 'MH - Marshall Islands', desc: 'Marshall Islands' },
  { value: 'MK', display_name: 'MK - Macedonia', desc: 'Macedonia' },
  { value: 'MN', display_name: 'MN - Mongolia', desc: 'Mongolia' },
  { value: 'MO', display_name: 'MO - Macao', desc: 'Macao' },
  { value: 'MP', display_name: 'MP - Northern Mariana Islands', desc: 'Northern Mariana Islands' },
  { value: 'MQ', display_name: 'MQ - Martinique', desc: 'Martinique' },
  { value: 'MR', display_name: 'MR - Mauritania', desc: 'Mauritania' },
  { value: 'MS', display_name: 'MS - Montserrat', desc: 'Montserrat' },
  { value: 'MT', display_name: 'MT - Malta', desc: 'Malta' },
  { value: 'MU', display_name: 'MU - Mauritius', desc: 'Mauritius' },
  { value: 'MV', display_name: 'MV - Maldives', desc: 'Maldives' },
  { value: 'MW', display_name: 'MW - Malawi', desc: 'Malawi' },
  { value: 'MX', display_name: 'MX - Mexico', desc: 'Mexico' },
  { value: 'MY', display_name: 'MY - Malaysia', desc: 'Malaysia' },
  { value: 'MZ', display_name: 'MZ - Mozambique', desc: 'Mozambique' },
  { value: 'NA', display_name: 'NA - Namibia', desc: 'Namibia' },
  { value: 'NC', display_name: 'NC - New Caledonia', desc: 'New Caledonia' },
  { value: 'NE', display_name: 'NE - Niger', desc: 'Niger' },
  { value: 'NF', display_name: 'NF - Norfolk Island', desc: 'Norfolk Island' },
  { value: 'NG', display_name: 'NG - Nigeria', desc: 'Nigeria' },
  { value: 'NL', display_name: 'NL - Netherlands', desc: 'Netherlands' },
  { value: 'NO', display_name: 'NO - Norway', desc: 'Norway' },
  { value: 'NP', display_name: 'NP - Nepal', desc: 'Nepal' },
  { value: 'NR', display_name: 'NR - Nauru', desc: 'Nauru' },
  { value: 'NU', display_name: 'NU - Niue', desc: 'Niue' },
  { value: 'NZ', display_name: 'NZ - New Zealand', desc: 'New Zealand' },
  { value: 'OM', display_name: 'OM - Oman', desc: 'Oman' },
  { value: 'PA', display_name: 'PA - Panama', desc: 'Panama' },
  { value: 'PE', display_name: 'PE - Peru', desc: 'Peru' },
  { value: 'PF', display_name: 'PF - French Polynesia', desc: 'French Polynesia' },
  { value: 'PG', display_name: 'PG - Papua New Guinea', desc: 'Papua New Guinea' },
  { value: 'PH', display_name: 'PH - Philippines', desc: 'Philippines' },
  { value: 'PK', display_name: 'PK - Pakistan', desc: 'Pakistan' },
  { value: 'PL', display_name: 'PL - Poland', desc: 'Poland' },
  {
    value: 'PM',
    display_name: 'PM - Saint Pierre and Miquelon',
    desc: 'Saint Pierre and Miquelon',
  },
  { value: 'PN', display_name: 'PN - Pitcairn', desc: 'Pitcairn' },
  { value: 'PR', display_name: 'PR - Puerto Rico', desc: 'Puerto Rico' },
  { value: 'PS', display_name: 'PS - Palestinian territories', desc: 'Palestinian territories' },
  { value: 'PT', display_name: 'PT - Portugal', desc: 'Portugal' },
  { value: 'PW', display_name: 'PW - Palau', desc: 'Palau' },
  { value: 'PY', display_name: 'PY - Paraguay', desc: 'Paraguay' },
  { value: 'QA', display_name: 'QA - Qatar', desc: 'Qatar' },
  { value: 'RE', display_name: 'RE - Reunion', desc: 'Reunion' },
  { value: 'RO', display_name: 'RO - Romania', desc: 'Romania' },
  { value: 'RS', display_name: 'RS - Republic of Serbia', desc: 'Republic of Serbia' },
  { value: 'RW', display_name: 'RW - Rwanda', desc: 'Rwanda' },
  { value: 'SA', display_name: 'SA - Saudi Arabia', desc: 'Saudi Arabia' },
  { value: 'SB', display_name: 'SB - Solomon Islands', desc: 'Solomon Islands' },
  { value: 'SC', display_name: 'SC - Seychelles', desc: 'Seychelles' },
  { value: 'SE', display_name: 'SE - Sweden', desc: 'Sweden' },
  { value: 'SG', display_name: 'SG - Singapore', desc: 'Singapore' },
  { value: 'SH', display_name: 'SH - Saint Helena', desc: 'Saint Helena' },
  { value: 'SI', display_name: 'SI - Slovenia', desc: 'Slovenia' },
  { value: 'SJ', display_name: 'SJ - Svalbard and Jan Mayen', desc: 'Svalbard and Jan Mayen' },
  { value: 'SK', display_name: 'SK - Slovakia', desc: 'Slovakia' },
  { value: 'SL', display_name: 'SL - Sierra Leone', desc: 'Sierra Leone' },
  { value: 'SM', display_name: 'SM - San Marino', desc: 'San Marino' },
  { value: 'SN', display_name: 'SN - Senegal', desc: 'Senegal' },
  { value: 'SR', display_name: 'SR - Suriname', desc: 'Suriname' },
  { value: 'ST', display_name: 'ST - São Tomé and Príncipe', desc: 'São Tomé and Príncipe' },
  { value: 'SV', display_name: 'SV - El Salvador', desc: 'El Salvador' },
  { value: 'SX', display_name: 'SX - Sint Maarten', desc: 'Sint Maarten' },
  { value: 'SZ', display_name: 'SZ - Swaziland', desc: 'Swaziland' },
  { value: 'TC', display_name: 'TC - Turks and Caicos Islands', desc: 'Turks and Caicos Islands' },
  { value: 'TD', display_name: 'TD - Chad', desc: 'Chad' },
  {
    value: 'TF',
    display_name: 'TF - French Southern and Antarctic Lands',
    desc: 'French Southern and Antarctic Lands',
  },
  { value: 'TG', display_name: 'TG - Togo', desc: 'Togo' },
  { value: 'TH', display_name: 'TH - Thailand', desc: 'Thailand' },
  { value: 'TJ', display_name: 'TJ - Tajikistan', desc: 'Tajikistan' },
  { value: 'TK', display_name: 'TK - Tokelau', desc: 'Tokelau' },
  { value: 'TL', display_name: 'TL - Timor-Leste', desc: 'Timor-Leste' },
  { value: 'TM', display_name: 'TM - Turkmenistan', desc: 'Turkmenistan' },
  { value: 'TN', display_name: 'TN - Tunisia', desc: 'Tunisia' },
  { value: 'TO', display_name: 'TO - Tonga', desc: 'Tonga' },
  { value: 'TR', display_name: 'TR - Turkey', desc: 'Turkey' },
  { value: 'TT', display_name: 'TT - Trinidad and Tobago', desc: 'Trinidad and Tobago' },
  { value: 'TV', display_name: 'TV - Tuvalu', desc: 'Tuvalu' },
  { value: 'TW', display_name: 'TW - Taiwan', desc: 'Taiwan' },
  { value: 'TZ', display_name: 'TZ - Tanzania', desc: 'Tanzania' },
  { value: 'UA', display_name: 'UA - Ukraine', desc: 'Ukraine' },
  { value: 'UG', display_name: 'UG - Uganda', desc: 'Uganda' },
  {
    value: 'UM',
    display_name: 'UM - United States Minor Outlying Islands',
    desc: 'United States Minor Outlying Islands',
  },
  { value: 'US', display_name: 'US - United States', desc: 'United States' },
  { value: 'UY', display_name: 'UY - Uruguay', desc: 'Uruguay' },
  { value: 'UZ', display_name: 'UZ - Uzbekistan', desc: 'Uzbekistan' },
  { value: 'VA', display_name: 'VA - Holy See (Vatican City)', desc: 'Holy See (Vatican City)' },
  {
    value: 'VC',
    display_name: 'VC - Saint Vincent and the Grenadines',
    desc: 'Saint Vincent and the Grenadines',
  },
  { value: 'VG', display_name: 'VG - British Virgin Islands', desc: 'British Virgin Islands' },
  { value: 'VI', display_name: 'VI - U.S. Virgin Islands', desc: 'U.S. Virgin Islands' },
  { value: 'VN', display_name: 'VN - Vietnam', desc: 'Vietnam' },
  { value: 'VU', display_name: 'VU - Vanuatu', desc: 'Vanuatu' },
  { value: 'WF', display_name: 'WF - Wallis and Futuna', desc: 'Wallis and Futuna' },
  { value: 'WS', display_name: 'WS - Samoa', desc: 'Samoa' },
  { value: 'XK', display_name: 'XK - Kosovo', desc: 'Kosovo' },
  { value: 'YT', display_name: 'YT - Mayotte', desc: 'Mayotte' },
  { value: 'ZA', display_name: 'ZA - South Africa', desc: 'South Africa' },
  { value: 'ZM', display_name: 'ZM - Zambia', desc: 'Zambia' },
] satisfies IQoreAllowedValue<string>[];
