import { IQorePartialAppActionWithSwaggerPath } from '@qoretechnologies/ts-toolkit';
import { createSwaggerPaths } from '../../../global/helpers';
import { BITBUCKET_COMMITS_ACTIONS, BITBUCKET_COMMITS_ALLOWED_PATHS } from './commits';
import { BITBUCKET_DEPLOYMENTS_ACTIONS, BITBUCKET_DEPLOYMENTS_ALLOWED_PATHS } from './deployments';
import {
  BITBUCKET_PULL_REQUESTS_ACTIONS,
  BITBUCKET_PULL_REQUESTS_ALLOWED_PATHS,
} from './pull-requests';
import {
  BITBUCKET_REPOSITORIES_ACTIONS,
  BITBUCKET_REPOSITORIES_ALLOWED_PATHS,
} from './repositories';
import { BITBUCKET_SEARCH_ACTIONS, BITBUCKET_SEARCH_ALLOWED_PATHS } from './search';
import { BITBUCKET_WORKSPACES_ACTIONS, BITBUCKET_WORKSPACES_ALLOWED_PATHS } from './workspaces';

export const BITBUCKET_ACTIONS = [
  ...BITBUCKET_COMMITS_ACTIONS,
  ...BITBUCKET_DEPLOYMENTS_ACTIONS,
  ...BITBUCKET_PULL_REQUESTS_ACTIONS,
  ...BITBUCKET_REPOSITORIES_ACTIONS,
  ...BITBUCKET_SEARCH_ACTIONS,
  ...BITBUCKET_WORKSPACES_ACTIONS,
] satisfies IQorePartialAppActionWithSwaggerPath[];

export const BITBUCKET_ALLOWED_PATHS = [
  ...createSwaggerPaths(BITBUCKET_COMMITS_ALLOWED_PATHS),
  ...createSwaggerPaths(BITBUCKET_DEPLOYMENTS_ALLOWED_PATHS),
  ...createSwaggerPaths(BITBUCKET_PULL_REQUESTS_ALLOWED_PATHS),
  ...createSwaggerPaths(BITBUCKET_REPOSITORIES_ALLOWED_PATHS),
  ...createSwaggerPaths(BITBUCKET_SEARCH_ALLOWED_PATHS),
  ...createSwaggerPaths(BITBUCKET_WORKSPACES_ALLOWED_PATHS),
];
