#!/bin/sh
# Copyright (C) 2026 David Nichols
# SPDX-License-Identifier: MIT
set -eu
for suite in test/*.qtest; do
    timeout 600 /usr/bin/qore --enable-debug \
        -l "$QORE_V8_TEST_MODULE_DIR/v8-api-$(/usr/bin/qore --latest-module-api).qmod" \
        -l "$QORE_V8_TEST_QMOD_DIR/TypeScriptProxy/TypeScriptProxy.qmod" \
        -l "$QORE_V8_TEST_QMOD_DIR/TypeScriptActionInterface/TypeScriptActionInterface.qmod" \
        "$suite" -v
done
