import { createAllowedPaths } from '../../global/helpers';

export const ASANA_APP_NAME = 'Asana';
export const ASANA_ALLOWED_PATHS = createAllowedPaths([
  '/tasks',
  '/tasks/{task_gid}',
  '/tasks/{task_gid}/subtasks',
  '/tasks/{task_gid}/dependencies',
  '/tasks/{task_gid}/dependents',
  '/tasks/{task_gid}/stories',
  '/workspaces',
  '/workspaces/{workspace_gid}',
  '/users',
  '/users/{user_gid}',
  '/projects',
  '/projects/{project_gid}',
  '/projects/{project_gid}/tasks',
  '/projects/{project_gid}/sections',
  '/time_periods',
  '/sections/{section_gid}',
  '/sections/{section_gid}/tasks',
  '/tags',
  '/tags/{tag_gid}',
  '/tags/{tag_gid}/tasks',
  '/teams:GET',
  '/teams/{team_gid}/projects',
  '/events',
  '/goals',
  '/goals/{goal_gid}',
  // '/teams/{team_gid}',
  // '/webhooks',
  // '/webhooks/{webhook_gid}',
  // '/portfolio_memberships',
  // '/portfolios',
  // '/portfolios/{portfolio_gid}',
]);
export const ASANA_SWAGGER_API_PATH = '';
