import { IQoreAllowedValue } from '@qoretechnologies/ts-toolkit';

export const AirtableTimezoneAllowedValues = [
  { value: 'utc', display_name: 'UTC' },
  { value: 'client', display_name: 'Client' },
  { value: 'Africa/Abidjan', display_name: 'Africa/Abidjan' },
  { value: 'Africa/Accra', display_name: 'Africa/Accra' },
  { value: 'Africa/Addis_Ababa', display_name: 'Africa/Addis Ababa' },
  { value: 'Africa/Algiers', display_name: 'Africa/Algiers' },
  { value: 'Africa/Asmara', display_name: 'Africa/Asmara' },
  { value: 'Africa/Bamako', display_name: 'Africa/Bamako' },
  { value: 'Africa/Bangui', display_name: 'Africa/Bangui' },
  { value: 'Africa/Banjul', display_name: 'Africa/Banjul' },
  { value: 'Africa/Bissau', display_name: 'Africa/Bissau' },
  { value: 'Africa/Blantyre', display_name: 'Africa/Blantyre' },
  { value: 'Africa/Brazzaville', display_name: 'Africa/Brazzaville' },
  { value: 'Africa/Bujumbura', display_name: 'Africa/Bujumbura' },
  { value: 'Africa/Cairo', display_name: 'Africa/Cairo' },
  { value: 'Africa/Casablanca', display_name: 'Africa/Casablanca' },
  { value: 'Africa/Ceuta', display_name: 'Africa/Ceuta' },
  { value: 'Africa/Conakry', display_name: 'Africa/Conakry' },
  { value: 'Africa/Dakar', display_name: 'Africa/Dakar' },
  { value: 'Africa/Dar_es_Salaam', display_name: 'Africa/Dar es Salaam' },
  { value: 'Africa/Djibouti', display_name: 'Africa/Djibouti' },
  { value: 'Africa/Douala', display_name: 'Africa/Douala' },
  { value: 'Africa/El_Aaiun', display_name: 'Africa/El Aaiun' },
  { value: 'Africa/Freetown', display_name: 'Africa/Freetown' },
  { value: 'Africa/Gaborone', display_name: 'Africa/Gaborone' },
  { value: 'Africa/Harare', display_name: 'Africa/Harare' },
  { value: 'Africa/Johannesburg', display_name: 'Africa/Johannesburg' },
  { value: 'Africa/Juba', display_name: 'Africa/Juba' },
  { value: 'Africa/Kampala', display_name: 'Africa/Kampala' },
  { value: 'Africa/Khartoum', display_name: 'Africa/Khartoum' },
  { value: 'Africa/Kigali', display_name: 'Africa/Kigali' },
  { value: 'Africa/Kinshasa', display_name: 'Africa/Kinshasa' },
  { value: 'Africa/Lagos', display_name: 'Africa/Lagos' },
  { value: 'Africa/Libreville', display_name: 'Africa/Libreville' },
  { value: 'Africa/Lome', display_name: 'Africa/Lome' },
  { value: 'Africa/Luanda', display_name: 'Africa/Luanda' },
  { value: 'Africa/Lubumbashi', display_name: 'Africa/Lubumbashi' },
  { value: 'Africa/Lusaka', display_name: 'Africa/Lusaka' },
  { value: 'Africa/Malabo', display_name: 'Africa/Malabo' },
  { value: 'Africa/Maputo', display_name: 'Africa/Maputo' },
  { value: 'Africa/Maseru', display_name: 'Africa/Maseru' },
  { value: 'Africa/Mbabane', display_name: 'Africa/Mbabane' },
  { value: 'Africa/Mogadishu', display_name: 'Africa/Mogadishu' },
  { value: 'Africa/Monrovia', display_name: 'Africa/Monrovia' },
  { value: 'Africa/Nairobi', display_name: 'Africa/Nairobi' },
  { value: 'Africa/Ndjamena', display_name: 'Africa/Ndjamena' },
  { value: 'Africa/Niamey', display_name: 'Africa/Niamey' },
  { value: 'Africa/Nouakchott', display_name: 'Africa/Nouakchott' },
  { value: 'Africa/Ouagadougou', display_name: 'Africa/Ouagadougou' },
  { value: 'Africa/Porto-Novo', display_name: 'Africa/Porto-Novo' },
  { value: 'Africa/Sao_Tome', display_name: 'Africa/Sao Tome' },
  { value: 'Africa/Tripoli', display_name: 'Africa/Tripoli' },
  { value: 'Africa/Tunis', display_name: 'Africa/Tunis' },
  { value: 'Africa/Windhoek', display_name: 'Africa/Windhoek' },
  { value: 'America/Adak', display_name: 'America/Adak' },
  { value: 'America/Anchorage', display_name: 'America/Anchorage' },
  { value: 'America/Anguilla', display_name: 'America/Anguilla' },
  { value: 'America/Antigua', display_name: 'America/Antigua' },
  { value: 'America/Araguaina', display_name: 'America/Araguaina' },
  { value: 'America/Argentina/Buenos_Aires', display_name: 'America/Argentina/Buenos Aires' },
  { value: 'America/Argentina/Catamarca', display_name: 'America/Argentina/Catamarca' },
  { value: 'America/Argentina/Cordoba', display_name: 'America/Argentina/Cordoba' },
  { value: 'America/Argentina/Jujuy', display_name: 'America/Argentina/Jujuy' },
  { value: 'America/Argentina/La_Rioja', display_name: 'America/Argentina/La Rioja' },
  { value: 'America/Argentina/Mendoza', display_name: 'America/Argentina/Mendoza' },
  { value: 'America/Argentina/Rio_Gallegos', display_name: 'America/Argentina/Rio Gallegos' },
  { value: 'America/Argentina/Salta', display_name: 'America/Argentina/Salta' },
  { value: 'America/Argentina/San_Juan', display_name: 'America/Argentina/San Juan' },
  { value: 'America/Argentina/San_Luis', display_name: 'America/Argentina/San Luis' },
  { value: 'America/Argentina/Tucuman', display_name: 'America/Argentina/Tucuman' },
  { value: 'America/Argentina/Ushuaia', display_name: 'America/Argentina/Ushuaia' },
  { value: 'America/Aruba', display_name: 'America/Aruba' },
  { value: 'America/Asuncion', display_name: 'America/Asuncion' },
  { value: 'America/Atikokan', display_name: 'America/Atikokan' },
  { value: 'America/Bahia', display_name: 'America/Bahia' },
  { value: 'America/Bahia_Banderas', display_name: 'America/Bahia Banderas' },
  { value: 'America/Barbados', display_name: 'America/Barbados' },
  { value: 'America/Belem', display_name: 'America/Belem' },
  { value: 'America/Belize', display_name: 'America/Belize' },
  { value: 'America/Blanc-Sablon', display_name: 'America/Blanc-Sablon' },
  { value: 'America/Boa_Vista', display_name: 'America/Boa Vista' },
  { value: 'America/Bogota', display_name: 'America/Bogota' },
  { value: 'America/Boise', display_name: 'America/Boise' },
  { value: 'America/Cambridge_Bay', display_name: 'America/Cambridge Bay' },
  { value: 'America/Campo_Grande', display_name: 'America/Campo Grande' },
  { value: 'America/Cancun', display_name: 'America/Cancun' },
  { value: 'America/Caracas', display_name: 'America/Caracas' },
  { value: 'America/Cayenne', display_name: 'America/Cayenne' },
  { value: 'America/Cayman', display_name: 'America/Cayman' },
  { value: 'America/Chicago', display_name: 'America/Chicago' },
  { value: 'America/Chihuahua', display_name: 'America/Chihuahua' },
  { value: 'America/Costa_Rica', display_name: 'America/Costa Rica' },
  { value: 'America/Creston', display_name: 'America/Creston' },
  { value: 'America/Cuiaba', display_name: 'America/Cuiaba' },
  { value: 'America/Curacao', display_name: 'America/Curacao' },
  { value: 'America/Danmarkshavn', display_name: 'America/Danmarkshavn' },
  { value: 'America/Dawson', display_name: 'America/Dawson' },
  { value: 'America/Dawson_Creek', display_name: 'America/Dawson Creek' },
  { value: 'America/Denver', display_name: 'America/Denver' },
  { value: 'America/Detroit', display_name: 'America/Detroit' },
  { value: 'America/Dominica', display_name: 'America/Dominica' },
  { value: 'America/Edmonton', display_name: 'America/Edmonton' },
  { value: 'America/Eirunepe', display_name: 'America/Eirunepe' },
  { value: 'America/El_Salvador', display_name: 'America/El Salvador' },
  { value: 'America/Fort_Nelson', display_name: 'America/Fort Nelson' },
  { value: 'America/Fortaleza', display_name: 'America/Fortaleza' },
  { value: 'America/Glace_Bay', display_name: 'America/Glace Bay' },
  { value: 'America/Godthab', display_name: 'America/Godthab' },
  { value: 'America/Goose_Bay', display_name: 'America/Goose Bay' },
  { value: 'America/Grand_Turk', display_name: 'America/Grand Turk' },
  { value: 'America/Grenada', display_name: 'America/Grenada' },
  { value: 'America/Guadeloupe', display_name: 'America/Guadeloupe' },
  { value: 'America/Guatemala', display_name: 'America/Guatemala' },
  { value: 'America/Guayaquil', display_name: 'America/Guayaquil' },
  { value: 'America/Guyana', display_name: 'America/Guyana' },
  { value: 'America/Halifax', display_name: 'America/Halifax' },
  { value: 'America/Havana', display_name: 'America/Havana' },
  { value: 'America/Hermosillo', display_name: 'America/Hermosillo' },
  { value: 'America/Indiana/Indianapolis', display_name: 'America/Indiana/Indianapolis' },
  { value: 'America/Indiana/Knox', display_name: 'America/Indiana/Knox' },
  { value: 'America/Indiana/Marengo', display_name: 'America/Indiana/Marengo' },
  { value: 'America/Indiana/Petersburg', display_name: 'America/Indiana/Petersburg' },
  { value: 'America/Indiana/Tell_City', display_name: 'America/Indiana/Tell City' },
  { value: 'America/Indiana/Vevay', display_name: 'America/Indiana/Vevay' },
  { value: 'America/Indiana/Vincennes', display_name: 'America/Indiana/Vincennes' },
  { value: 'America/Indiana/Winamac', display_name: 'America/Indiana/Winamac' },
  { value: 'America/Inuvik', display_name: 'America/Inuvik' },
  { value: 'America/Iqaluit', display_name: 'America/Iqaluit' },
  { value: 'America/Jamaica', display_name: 'America/Jamaica' },
  { value: 'America/Juneau', display_name: 'America/Juneau' },
  { value: 'America/Kentucky/Louisville', display_name: 'America/Kentucky/Louisville' },
  { value: 'America/Kentucky/Monticello', display_name: 'America/Kentucky/Monticello' },
  { value: 'America/Kralendijk', display_name: 'America/Kralendijk' },
  { value: 'America/La_Paz', display_name: 'America/La Paz' },
  { value: 'America/Lima', display_name: 'America/Lima' },
  { value: 'America/Los_Angeles', display_name: 'America/Los Angeles' },
  { value: 'America/Lower_Princes', display_name: 'America/Lower Princes' },
  { value: 'America/Maceio', display_name: 'America/Maceio' },
  { value: 'America/Managua', display_name: 'America/Managua' },
  { value: 'America/Manaus', display_name: 'America/Manaus' },
  { value: 'America/Marigot', display_name: 'America/Marigot' },
  { value: 'America/Martinique', display_name: 'America/Martinique' },
  { value: 'America/Matamoros', display_name: 'America/Matamoros' },
  { value: 'America/Mazatlan', display_name: 'America/Mazatlan' },
  { value: 'America/Menominee', display_name: 'America/Menominee' },
  { value: 'America/Merida', display_name: 'America/Merida' },
  { value: 'America/Metlakatla', display_name: 'America/Metlakatla' },
  { value: 'America/Mexico_City', display_name: 'America/Mexico City' },
  { value: 'America/Miquelon', display_name: 'America/Miquelon' },
  { value: 'America/Moncton', display_name: 'America/Moncton' },
  { value: 'America/Monterrey', display_name: 'America/Monterrey' },
  { value: 'America/Montevideo', display_name: 'America/Montevideo' },
  { value: 'America/Montserrat', display_name: 'America/Montserrat' },
  { value: 'America/Nassau', display_name: 'America/Nassau' },
  { value: 'America/New_York', display_name: 'America/New York' },
  { value: 'America/Nipigon', display_name: 'America/Nipigon' },
  { value: 'America/Nome', display_name: 'America/Nome' },
  { value: 'America/Noronha', display_name: 'America/Noronha' },
  { value: 'America/North_Dakota/Beulah', display_name: 'America/North Dakota/Beulah' },
  { value: 'America/North_Dakota/Center', display_name: 'America/North Dakota/Center' },
  { value: 'America/North_Dakota/New_Salem', display_name: 'America/North Dakota/New Salem' },
  { value: 'America/Nuuk', display_name: 'America/Nuuk' },
  { value: 'America/Ojinaga', display_name: 'America/Ojinaga' },
  { value: 'America/Panama', display_name: 'America/Panama' },
  { value: 'America/Pangnirtung', display_name: 'America/Pangnirtung' },
  { value: 'America/Paramaribo', display_name: 'America/Paramaribo' },
  { value: 'America/Phoenix', display_name: 'America/Phoenix' },
  { value: 'America/Port-au-Prince', display_name: 'America/Port-au-Prince' },
  { value: 'America/Port_of_Spain', display_name: 'America/Port of Spain' },
  { value: 'America/Porto_Velho', display_name: 'America/Porto Velho' },
  { value: 'America/Puerto_Rico', display_name: 'America/Puerto Rico' },
  { value: 'America/Punta_Arenas', display_name: 'America/Punta Arenas' },
  { value: 'America/Rainy_River', display_name: 'America/Rainy River' },
  { value: 'America/Rankin_Inlet', display_name: 'America/Rankin Inlet' },
  { value: 'America/Recife', display_name: 'America/Recife' },
  { value: 'America/Regina', display_name: 'America/Regina' },
  { value: 'America/Resolute', display_name: 'America/Resolute' },
  { value: 'America/Rio_Branco', display_name: 'America/Rio Branco' },
  { value: 'America/Santarem', display_name: 'America/Santarem' },
  { value: 'America/Santiago', display_name: 'America/Santiago' },
  { value: 'America/Santo_Domingo', display_name: 'America/Santo Domingo' },
  { value: 'America/Sao_Paulo', display_name: 'America/Sao Paulo' },
  { value: 'America/Scoresbysund', display_name: 'America/Scoresbysund' },
  { value: 'America/Sitka', display_name: 'America/Sitka' },
  { value: 'America/St_Barthelemy', display_name: 'America/St Barthelemy' },
  { value: 'America/St_Johns', display_name: 'America/St Johns' },
  { value: 'America/St_Kitts', display_name: 'America/St Kitts' },
  { value: 'America/St_Lucia', display_name: 'America/St Lucia' },
  { value: 'America/St_Thomas', display_name: 'America/St Thomas' },
  { value: 'America/St_Vincent', display_name: 'America/St Vincent' },
  { value: 'America/Swift_Current', display_name: 'America/Swift Current' },
  { value: 'America/Tegucigalpa', display_name: 'America/Tegucigalpa' },
  { value: 'America/Thule', display_name: 'America/Thule' },
  { value: 'America/Thunder_Bay', display_name: 'America/Thunder Bay' },
  { value: 'America/Tijuana', display_name: 'America/Tijuana' },
  { value: 'America/Toronto', display_name: 'America/Toronto' },
  { value: 'America/Tortola', display_name: 'America/Tortola' },
  { value: 'America/Vancouver', display_name: 'America/Vancouver' },
  { value: 'America/Whitehorse', display_name: 'America/Whitehorse' },
  { value: 'America/Winnipeg', display_name: 'America/Winnipeg' },
  { value: 'America/Yakutat', display_name: 'America/Yakutat' },
  { value: 'America/Yellowknife', display_name: 'America/Yellowknife' },
  { value: 'Antarctica/Casey', display_name: 'Antarctica/Casey' },
  { value: 'Antarctica/Davis', display_name: 'Antarctica/Davis' },
  { value: 'Antarctica/DumontDUrville', display_name: 'Antarctica/DumontDUrville' },
  { value: 'Antarctica/Macquarie', display_name: 'Antarctica/Macquarie' },
  { value: 'Antarctica/Mawson', display_name: 'Antarctica/Mawson' },
  { value: 'Antarctica/McMurdo', display_name: 'Antarctica/McMurdo' },
  { value: 'Antarctica/Palmer', display_name: 'Antarctica/Palmer' },
  { value: 'Antarctica/Rothera', display_name: 'Antarctica/Rothera' },
  { value: 'Antarctica/Syowa', display_name: 'Antarctica/Syowa' },
  { value: 'Antarctica/Troll', display_name: 'Antarctica/Troll' },
  { value: 'Antarctica/Vostok', display_name: 'Antarctica/Vostok' },
  { value: 'Arctic/Longyearbyen', display_name: 'Arctic/Longyearbyen' },
  { value: 'Asia/Aden', display_name: 'Asia/Aden' },
  { value: 'Asia/Almaty', display_name: 'Asia/Almaty' },
  { value: 'Asia/Amman', display_name: 'Asia/Amman' },
  { value: 'Asia/Anadyr', display_name: 'Asia/Anadyr' },
  { value: 'Asia/Aqtau', display_name: 'Asia/Aqtau' },
  { value: 'Asia/Aqtobe', display_name: 'Asia/Aqtobe' },
  { value: 'Asia/Ashgabat', display_name: 'Asia/Ashgabat' },
  { value: 'Asia/Atyrau', display_name: 'Asia/Atyrau' },
  { value: 'Asia/Baghdad', display_name: 'Asia/Baghdad' },
  { value: 'Asia/Bahrain', display_name: 'Asia/Bahrain' },
  { value: 'Asia/Baku', display_name: 'Asia/Baku' },
  { value: 'Asia/Bangkok', display_name: 'Asia/Bangkok' },
  { value: 'Asia/Barnaul', display_name: 'Asia/Barnaul' },
  { value: 'Asia/Beirut', display_name: 'Asia/Beirut' },
  { value: 'Asia/Bishkek', display_name: 'Asia/Bishkek' },
  { value: 'Asia/Brunei', display_name: 'Asia/Brunei' },
  { value: 'Asia/Chita', display_name: 'Asia/Chita' },
  { value: 'Asia/Choibalsan', display_name: 'Asia/Choibalsan' },
  { value: 'Asia/Colombo', display_name: 'Asia/Colombo' },
  { value: 'Asia/Damascus', display_name: 'Asia/Damascus' },
  { value: 'Asia/Dhaka', display_name: 'Asia/Dhaka' },
  { value: 'Asia/Dili', display_name: 'Asia/Dili' },
  { value: 'Asia/Dubai', display_name: 'Asia/Dubai' },
  { value: 'Asia/Dushanbe', display_name: 'Asia/Dushanbe' },
  { value: 'Asia/Famagusta', display_name: 'Asia/Famagusta' },
  { value: 'Asia/Gaza', display_name: 'Asia/Gaza' },
  { value: 'Asia/Hebron', display_name: 'Asia/Hebron' },
  { value: 'Asia/Ho_Chi_Minh', display_name: 'Asia/Ho Chi Minh' },
  { value: 'Asia/Hong_Kong', display_name: 'Asia/Hong Kong' },
  { value: 'Asia/Hovd', display_name: 'Asia/Hovd' },
  { value: 'Asia/Irkutsk', display_name: 'Asia/Irkutsk' },
  { value: 'Asia/Istanbul', display_name: 'Asia/Istanbul' },
  { value: 'Asia/Jakarta', display_name: 'Asia/Jakarta' },
  { value: 'Asia/Jayapura', display_name: 'Asia/Jayapura' },
  { value: 'Asia/Jerusalem', display_name: 'Asia/Jerusalem' },
  { value: 'Asia/Kabul', display_name: 'Asia/Kabul' },
  { value: 'Asia/Kamchatka', display_name: 'Asia/Kamchatka' },
  { value: 'Asia/Karachi', display_name: 'Asia/Karachi' },
  { value: 'Asia/Kathmandu', display_name: 'Asia/Kathmandu' },
  { value: 'Asia/Khandyga', display_name: 'Asia/Khandyga' },
  { value: 'Asia/Kolkata', display_name: 'Asia/Kolkata' },
  { value: 'Asia/Krasnoyarsk', display_name: 'Asia/Krasnoyarsk' },
  { value: 'Asia/Kuala_Lumpur', display_name: 'Asia/Kuala Lumpur' },
  { value: 'Asia/Kuching', display_name: 'Asia/Kuching' },
  { value: 'Asia/Kuwait', display_name: 'Asia/Kuwait' },
  { value: 'Asia/Macau', display_name: 'Asia/Macau' },
  { value: 'Asia/Magadan', display_name: 'Asia/Magadan' },
  { value: 'Asia/Makassar', display_name: 'Asia/Makassar' },
  { value: 'Asia/Manila', display_name: 'Asia/Manila' },
  { value: 'Asia/Muscat', display_name: 'Asia/Muscat' },
  { value: 'Asia/Nicosia', display_name: 'Asia/Nicosia' },
  { value: 'Asia/Novokuznetsk', display_name: 'Asia/Novokuznetsk' },
  { value: 'Asia/Novosibirsk', display_name: 'Asia/Novosibirsk' },
  { value: 'Asia/Omsk', display_name: 'Asia/Omsk' },
  { value: 'Asia/Oral', display_name: 'Asia/Oral' },
  { value: 'Asia/Phnom_Penh', display_name: 'Asia/Phnom Penh' },
  { value: 'Asia/Pontianak', display_name: 'Asia/Pontianak' },
  { value: 'Asia/Pyongyang', display_name: 'Asia/Pyongyang' },
  { value: 'Asia/Qatar', display_name: 'Asia/Qatar' },
  { value: 'Asia/Qostanay', display_name: 'Asia/Qostanay' },
  { value: 'Asia/Qyzylorda', display_name: 'Asia/Qyzylorda' },
  { value: 'Asia/Rangoon', display_name: 'Asia/Rangoon' },
  { value: 'Asia/Riyadh', display_name: 'Asia/Riyadh' },
  { value: 'Asia/Sakhalin', display_name: 'Asia/Sakhalin' },
  { value: 'Asia/Samarkand', display_name: 'Asia/Samarkand' },
  { value: 'Asia/Seoul', display_name: 'Asia/Seoul' },
  { value: 'Asia/Shanghai', display_name: 'Asia/Shanghai' },
  { value: 'Asia/Singapore', display_name: 'Asia/Singapore' },
  { value: 'Asia/Srednekolymsk', display_name: 'Asia/Srednekolymsk' },
  { value: 'Asia/Taipei', display_name: 'Asia/Taipei' },
  { value: 'Asia/Tashkent', display_name: 'Asia/Tashkent' },
  { value: 'Asia/Tbilisi', display_name: 'Asia/Tbilisi' },
  { value: 'Asia/Tehran', display_name: 'Asia/Tehran' },
  { value: 'Asia/Thimphu', display_name: 'Asia/Thimphu' },
  { value: 'Asia/Tokyo', display_name: 'Asia/Tokyo' },
  { value: 'Asia/Tomsk', display_name: 'Asia/Tomsk' },
  { value: 'Asia/Ulaanbaatar', display_name: 'Asia/Ulaanbaatar' },
  { value: 'Asia/Urumqi', display_name: 'Asia/Urumqi' },
  { value: 'Asia/Ust-Nera', display_name: 'Asia/Ust-Nera' },
  { value: 'Asia/Vientiane', display_name: 'Asia/Vientiane' },
  { value: 'Asia/Vladivostok', display_name: 'Asia/Vladivostok' },
  { value: 'Asia/Yakutsk', display_name: 'Asia/Yakutsk' },
  { value: 'Asia/Yangon', display_name: 'Asia/Yangon' },
  { value: 'Asia/Yekaterinburg', display_name: 'Asia/Yekaterinburg' },
  { value: 'Asia/Yerevan', display_name: 'Asia/Yerevan' },
  { value: 'Atlantic/Azores', display_name: 'Atlantic/Azores' },
  { value: 'Atlantic/Bermuda', display_name: 'Atlantic/Bermuda' },
  { value: 'Atlantic/Canary', display_name: 'Atlantic/Canary' },
  { value: 'Atlantic/Cape_Verde', display_name: 'Atlantic/Cape Verde' },
  { value: 'Atlantic/Faroe', display_name: 'Atlantic/Faroe' },
  { value: 'Atlantic/Madeira', display_name: 'Atlantic/Madeira' },
  { value: 'Atlantic/Reykjavik', display_name: 'Atlantic/Reykjavik' },
  { value: 'Atlantic/South_Georgia', display_name: 'Atlantic/South Georgia' },
  { value: 'Atlantic/St_Helena', display_name: 'Atlantic/St Helena' },
  { value: 'Atlantic/Stanley', display_name: 'Atlantic/Stanley' },
  { value: 'Australia/Adelaide', display_name: 'Australia/Adelaide' },
  { value: 'Australia/Brisbane', display_name: 'Australia/Brisbane' },
  { value: 'Australia/Broken_Hill', display_name: 'Australia/Broken Hill' },
  { value: 'Australia/Currie', display_name: 'Australia/Currie' },
  { value: 'Australia/Darwin', display_name: 'Australia/Darwin' },
  { value: 'Australia/Eucla', display_name: 'Australia/Eucla' },
  { value: 'Australia/Hobart', display_name: 'Australia/Hobart' },
  { value: 'Australia/Lindeman', display_name: 'Australia/Lindeman' },
  { value: 'Australia/Lord_Howe', display_name: 'Australia/Lord Howe' },
  { value: 'Australia/Melbourne', display_name: 'Australia/Melbourne' },
  { value: 'Australia/Perth', display_name: 'Australia/Perth' },
  { value: 'Australia/Sydney', display_name: 'Australia/Sydney' },
  { value: 'Europe/Amsterdam', display_name: 'Europe/Amsterdam' },
  { value: 'Europe/Andorra', display_name: 'Europe/Andorra' },
  { value: 'Europe/Astrakhan', display_name: 'Europe/Astrakhan' },
  { value: 'Europe/Athens', display_name: 'Europe/Athens' },
  { value: 'Europe/Belgrade', display_name: 'Europe/Belgrade' },
  { value: 'Europe/Berlin', display_name: 'Europe/Berlin' },
  { value: 'Europe/Bratislava', display_name: 'Europe/Bratislava' },
  { value: 'Europe/Brussels', display_name: 'Europe/Brussels' },
  { value: 'Europe/Bucharest', display_name: 'Europe/Bucharest' },
  { value: 'Europe/Budapest', display_name: 'Europe/Budapest' },
  { value: 'Europe/Busingen', display_name: 'Europe/Busingen' },
  { value: 'Europe/Chisinau', display_name: 'Europe/Chisinau' },
  { value: 'Europe/Copenhagen', display_name: 'Europe/Copenhagen' },
  { value: 'Europe/Dublin', display_name: 'Europe/Dublin' },
  { value: 'Europe/Gibraltar', display_name: 'Europe/Gibraltar' },
  { value: 'Europe/Guernsey', display_name: 'Europe/Guernsey' },
  { value: 'Europe/Helsinki', display_name: 'Europe/Helsinki' },
  { value: 'Europe/Isle_of_Man', display_name: 'Europe/Isle of Man' },
  { value: 'Europe/Istanbul', display_name: 'Europe/Istanbul' },
  { value: 'Europe/Jersey', display_name: 'Europe/Jersey' },
  { value: 'Europe/Kaliningrad', display_name: 'Europe/Kaliningrad' },
  { value: 'Europe/Kiev', display_name: 'Europe/Kiev' },
  { value: 'Europe/Kirov', display_name: 'Europe/Kirov' },
  { value: 'Europe/Lisbon', display_name: 'Europe/Lisbon' },
  { value: 'Europe/Ljubljana', display_name: 'Europe/Ljubljana' },
  { value: 'Europe/London', display_name: 'Europe/London' },
  { value: 'Europe/Luxembourg', display_name: 'Europe/Luxembourg' },
  { value: 'Europe/Madrid', display_name: 'Europe/Madrid' },
  { value: 'Europe/Malta', display_name: 'Europe/Malta' },
  { value: 'Europe/Mariehamn', display_name: 'Europe/Mariehamn' },
  { value: 'Europe/Minsk', display_name: 'Europe/Minsk' },
  { value: 'Europe/Monaco', display_name: 'Europe/Monaco' },
  { value: 'Europe/Moscow', display_name: 'Europe/Moscow' },
  { value: 'Europe/Nicosia', display_name: 'Europe/Nicosia' },
  { value: 'Europe/Oslo', display_name: 'Europe/Oslo' },
  { value: 'Europe/Paris', display_name: 'Europe/Paris' },
  { value: 'Europe/Podgorica', display_name: 'Europe/Podgorica' },
  { value: 'Europe/Prague', display_name: 'Europe/Prague' },
  { value: 'Europe/Riga', display_name: 'Europe/Riga' },
  { value: 'Europe/Rome', display_name: 'Europe/Rome' },
  { value: 'Europe/Samara', display_name: 'Europe/Samara' },
  { value: 'Europe/San_Marino', display_name: 'Europe/San Marino' },
  { value: 'Europe/Sarajevo', display_name: 'Europe/Sarajevo' },
  { value: 'Europe/Saratov', display_name: 'Europe/Saratov' },
  { value: 'Europe/Simferopol', display_name: 'Europe/Simferopol' },
  { value: 'Europe/Skopje', display_name: 'Europe/Skopje' },
  { value: 'Europe/Sofia', display_name: 'Europe/Sofia' },
  { value: 'Europe/Stockholm', display_name: 'Europe/Stockholm' },
  { value: 'Europe/Tallinn', display_name: 'Europe/Tallinn' },
  { value: 'Europe/Tirane', display_name: 'Europe/Tirane' },
  { value: 'Europe/Ulyanovsk', display_name: 'Europe/Ulyanovsk' },
  { value: 'Europe/Uzhgorod', display_name: 'Europe/Uzhgorod' },
  { value: 'Europe/Vaduz', display_name: 'Europe/Vaduz' },
  { value: 'Europe/Vatican', display_name: 'Europe/Vatican' },
  { value: 'Europe/Vienna', display_name: 'Europe/Vienna' },
  { value: 'Europe/Vilnius', display_name: 'Europe/Vilnius' },
  { value: 'Europe/Volgograd', display_name: 'Europe/Volgograd' },
  { value: 'Europe/Warsaw', display_name: 'Europe/Warsaw' },
  { value: 'Europe/Zagreb', display_name: 'Europe/Zagreb' },
  { value: 'Europe/Zaporozhye', display_name: 'Europe/Zaporozhye' },
  { value: 'Europe/Zurich', display_name: 'Europe/Zurich' },
  { value: 'Indian/Antananarivo', display_name: 'Indian/Antananarivo' },
  { value: 'Indian/Chagos', display_name: 'Indian/Chagos' },
  { value: 'Indian/Christmas', display_name: 'Indian/Christmas' },
  { value: 'Indian/Cocos', display_name: 'Indian/Cocos' },
  { value: 'Indian/Comoro', display_name: 'Indian/Comoro' },
  { value: 'Indian/Kerguelen', display_name: 'Indian/Kerguelen' },
  { value: 'Indian/Mahe', display_name: 'Indian/Mahe' },
  { value: 'Indian/Maldives', display_name: 'Indian/Maldives' },
  { value: 'Indian/Mauritius', display_name: 'Indian/Mauritius' },
  { value: 'Indian/Mayotte', display_name: 'Indian/Mayotte' },
  { value: 'Indian/Reunion', display_name: 'Indian/Reunion' },
  { value: 'Pacific/Apia', display_name: 'Pacific/Apia' },
  { value: 'Pacific/Auckland', display_name: 'Pacific/Auckland' },
  { value: 'Pacific/Bougainville', display_name: 'Pacific/Bougainville' },
  { value: 'Pacific/Chatham', display_name: 'Pacific/Chatham' },
  { value: 'Pacific/Chuuk', display_name: 'Pacific/Chuuk' },
  { value: 'Pacific/Easter', display_name: 'Pacific/Easter' },
  { value: 'Pacific/Efate', display_name: 'Pacific/Efate' },
  { value: 'Pacific/Enderbury', display_name: 'Pacific/Enderbury' },
  { value: 'Pacific/Fakaofo', display_name: 'Pacific/Fakaofo' },
  { value: 'Pacific/Fiji', display_name: 'Pacific/Fiji' },
  { value: 'Pacific/Funafuti', display_name: 'Pacific/Funafuti' },
  { value: 'Pacific/Galapagos', display_name: 'Pacific/Galapagos' },
  { value: 'Pacific/Gambier', display_name: 'Pacific/Gambier' },
  { value: 'Pacific/Guadalcanal', display_name: 'Pacific/Guadalcanal' },
  { value: 'Pacific/Guam', display_name: 'Pacific/Guam' },
  { value: 'Pacific/Honolulu', display_name: 'Pacific/Honolulu' },
  { value: 'Pacific/Kanton', display_name: 'Pacific/Kanton' },
  { value: 'Pacific/Kiritimati', display_name: 'Pacific/Kiritimati' },
  { value: 'Pacific/Kosrae', display_name: 'Pacific/Kosrae' },
  { value: 'Pacific/Kwajalein', display_name: 'Pacific/Kwajalein' },
  { value: 'Pacific/Majuro', display_name: 'Pacific/Majuro' },
  { value: 'Pacific/Marquesas', display_name: 'Pacific/Marquesas' },
  { value: 'Pacific/Midway', display_name: 'Pacific/Midway' },
  { value: 'Pacific/Nauru', display_name: 'Pacific/Nauru' },
  { value: 'Pacific/Niue', display_name: 'Pacific/Niue' },
  { value: 'Pacific/Norfolk', display_name: 'Pacific/Norfolk' },
  { value: 'Pacific/Noumea', display_name: 'Pacific/Noumea' },
  { value: 'Pacific/Pago_Pago', display_name: 'Pacific/Pago Pago' },
  { value: 'Pacific/Palau', display_name: 'Pacific/Palau' },
  { value: 'Pacific/Pitcairn', display_name: 'Pacific/Pitcairn' },
  { value: 'Pacific/Pohnpei', display_name: 'Pacific/Pohnpei' },
  { value: 'Pacific/Port_Moresby', display_name: 'Pacific/Port Moresby' },
  { value: 'Pacific/Rarotonga', display_name: 'Pacific/Rarotonga' },
  { value: 'Pacific/Saipan', display_name: 'Pacific/Saipan' },
  { value: 'Pacific/Tahiti', display_name: 'Pacific/Tahiti' },
  { value: 'Pacific/Tarawa', display_name: 'Pacific/Tarawa' },
  { value: 'Pacific/Tongatapu', display_name: 'Pacific/Tongatapu' },
  { value: 'Pacific/Wake', display_name: 'Pacific/Wake' },
  { value: 'Pacific/Wallis', display_name: 'Pacific/Wallis' },
] satisfies IQoreAllowedValue<string>[];
