/* eslint-disable max-len */
import { IQoreAllowedValue } from '@qoretechnologies/ts-toolkit';

export const hubspotListTypeAllowedValues = [
  {
    display_name: 'Manual List',
    value: 'MANUAL',
    desc: 'A static list where you manually add or remove records. Good for fixed groups like event attendees, VIPs, or one-off campaign targets. Records must be explicitly added or removed via API or UI.',
  },
  {
    display_name: 'Dynamic List',
    value: 'DYNAMIC',
    desc: 'An active list that updates automatically based on filters you define. Useful for targeting records that meet evolving criteria. Records are automatically added/removed as their properties change to match or not match the list filters.',
  },
  {
    display_name: 'Snapshot List (Deprecated)',
    value: 'SNAPSHOT',
    desc: 'A legacy list type generated by a one-time snapshot of records that met certain criteria at creation time. The list does not update automatically and cannot be manually modified afterward. This type is deprecated and rarely used in modern workflows.',
  },
] satisfies IQoreAllowedValue<string>[];
