export const YouTubeReportMetricsAllowedValues = [
  { value: 'views', display_name: 'Views' },
  { value: 'estimatedMinutesWatched', display_name: 'Estimated Minutes Watched' },
  { value: 'averageViewDuration', display_name: 'Average View Duration' },
  { value: 'averageViewPercentage', display_name: 'Average View Percentage' },
  { value: 'comments', display_name: 'Comments' },
  { value: 'likes', display_name: 'Likes' },
  { value: 'dislikes', display_name: 'Dislikes' },
  { value: 'shares', display_name: 'Shares' },
  { value: 'subscribersGained', display_name: 'Subscribers Gained' },
  { value: 'subscribersLost', display_name: 'Subscribers Lost' },
  { value: 'videosAddedToPlaylists', display_name: 'Videos Added To Playlists' },
  { value: 'videosRemovedFromPlaylists', display_name: 'Videos Removed From Playlists' },
  { value: 'annotationImpressions', display_name: 'Annotation Impressions' },
  { value: 'annotationClickableImpressions', display_name: 'Annotation Clickable Impressions' },
  { value: 'annotationClicks', display_name: 'Annotation Clicks' },
  { value: 'annotationClickThroughRate', display_name: 'Annotation Click Through Rate' },
  { value: 'annotationClosableImpressions', display_name: 'Annotation Closable Impressions' },
  { value: 'annotationCloses', display_name: 'Annotation Closes' },
  { value: 'annotationCloseRate', display_name: 'Annotation Close Rate' },
  { value: 'cardImpressions', display_name: 'Card Impressions' },
  { value: 'cardClicks', display_name: 'Card Clicks' },
  { value: 'cardClickRate', display_name: 'Card Click Rate' },
  { value: 'cardTeaserImpressions', display_name: 'Card Teaser Impressions' },
  { value: 'cardTeaserClicks', display_name: 'Card Teaser Clicks' },
  { value: 'cardTeaserClickRate', display_name: 'Card Teaser Click Rate' },
];
